### ISSUE TITLE
cat 后台一直会报NullPointerException 

### ISSUE THREAD

**Issue by kanhai001** [dianping/cat#1018]
[07-20 17:28:01.515] [ERROR] [Thread] null
java.lang.NullPointerException
	at com.dianping.cat.report.page.dependency.graph.TopologyGraphManager$DependencyReloadTask.queryAllDomains(TopologyGraphManager.java:239)
	at com.dianping.cat.report.page.dependency.graph.TopologyGraphManager$DependencyReloadTask.run(TopologyGraphManager.java:254)
	at java.lang.Thread.run(Thread.java:745)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)

查看源码　会有些cat-home下的类找不到我用的是master其它分支看了　也一样．　求教

**Comment by blacklong** [comment]
同问，咋回事哈？
