### ISSUE TITLE
单机启动异常：Duplicated name(home)

### ISSUE THREAD

**Issue by 0915240** [dianping/cat#1026]
搜了下issues，看了下好多小伙伴启动异常，主要是 Duplicated name(home) 问题。

>java.lang.RuntimeException: Duplicated name(home) found between handleInbound() of class com.dianping.cat.report.page.home.Handler and handleInbound() of class com.dianping.cat.report.ReportModule

完全按照项目中的README例子下来的。

# enviroment:
+ windows 7 x64
+ jdk1.7.0_80
+ apache-tomcat-7.0.40-windows-x64
+ /data 权限都有

求指导给出解决办法，谢谢。

# 异常错误：
```
严重: Allocate exception for servlet mvc-servlet
java.lang.RuntimeException: Duplicated name(home) found between handleInbound() of class com.dianping.cat.report.page.home.Handler and handleInbound() of class com.dianping.cat.report.ReportModule
	at org.unidal.web.mvc.model.ModelManager.buildInbound(ModelManager.java:105)
	at org.unidal.web.mvc.model.ModelManager.buildModuleFromMethods(ModelManager.java:197)
	at org.unidal.web.mvc.model.ModelManager.buildModuleFromHandlers(ModelManager.java:167)
	at org.unidal.web.mvc.model.ModelManager.buildModule(ModelManager.java:157)
	at org.unidal.web.mvc.model.ModelManager.build(ModelManager.java:79)
	at org.unidal.web.mvc.model.ModelManager.register(ModelManager.java:321)
	at org.unidal.web.mvc.model.ModelManager.initialize(ModelManager.java:304)
	at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
	at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:96)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:283)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:129)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:497)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:371)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:286)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:123)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:497)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:371)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:286)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:123)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:388)
	at org.unidal.web.AbstractContainerServlet.lookup(AbstractContainerServlet.java:72)
	at org.unidal.web.MVC.initComponents(MVC.java:35)
	at org.unidal.web.AbstractContainerServlet.init(AbstractContainerServlet.java:51)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1280)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1193)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:865)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:136)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1008)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tanxd2002** [comment]
我原来也是这个问题，不过我当时是用java8编译的，改成java7后就好了。

**Comment by youyong205** [comment]
改为jdk7 79以下版本，这个是jdk 几个小版本有个bug~

**Comment by vincentchen** [comment]
能说啥bug嘛 到1.8都不行

**Comment by zhangkang1521** [comment]
用1.8编译接口方法org.unidal.web.mvc.PageHandler#handleInbound也能拿到@InboundActionMeta注解，用1.7拿不到注解
![image](https://user-images.githubusercontent.com/18444827/98907839-6fbccc00-24fa-11eb-916c-9c50c8bde991.png)


![image](https://user-images.githubusercontent.com/18444827/98907823-6895be00-24fa-11eb-9ad1-bb4b25140600.png)
