### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Glowdable** [dianping/cat#1039]
我按照文档搭建了一个cat，成功了，只部署cat.war，cat只在一个服务器上，然后我在另一机器上访问

刚开始没有问题，什么都可以显示，指标也可以访问，然后我一直循环某个Transaction，过了一段时间（半个小时左右），网页就不能打开了，看日志就一直报下面的错误。

然后重启就好了

[10-25 19:12:18.680] [ERROR] [Thread] null
java.lang.NullPointerException
    at com.dianping.cat.report.page.dependency.graph.TopologyGraphManager$DependencyReloadTask.queryAllDomains(TopologyGraphManager.java:239)
    at com.dianping.cat.report.page.dependency.graph.TopologyGraphManager$DependencyReloadTask.run(TopologyGraphManager.java:254)
    at java.lang.Thread.run(Thread.java:745)
    at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)

**Comment by youyong205** [comment]
这个报错是后台一个刷新异步线程，和页面没关系，你可以把这个TopologyGraphManager 启动线程关闭，试试，其实没有影响。打不开应该是其他问题
