### ISSUE TITLE
第一次访问就出错了。Duplicated name(home) found between handleInbound() of class com.dianping.cat.report.page.home.Handler and handleInbound() of class 

### ISSUE THREAD

**Issue by fqtyfz** [dianping/cat#1042]
Caused by: org.apache.xbean.recipe.ConstructionException: Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.unidal.web.mvc.model.ModelManager for injection private org.unidal.web.mvc.model.ModelManager org.unidal.web.mvc.lifecycle.DefaultRequestContextBuilder.m_modelManager
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:503)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:371)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:286)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
	... 45 more
Caused by: java.lang.RuntimeException: Duplicated name(home) found between handleInbound() of class com.dianping.cat.report.page.home.Handler and handleInbound() of class com.dianping.cat.report.ReportModule
	at org.unidal.web.mvc.model.ModelManager.buildInbound(ModelManager.java:105)
	at org.unidal.web.mvc.model.ModelManager.buildModuleFromMethods(ModelManager.java:197)
	at org.unidal.web.mvc.model.ModelManager.buildModuleFromHandlers(ModelManager.java:167)
	at org.unidal.web.mvc.model.ModelManager.buildModule(ModelManager.java:157)
	at org.unidal.web.mvc.model.ModelManager.build(ModelManager.java:79)
	at org.unidal.web.mvc.model.ModelManager.register(ModelManager.java:321)
	at org.unidal.web.mvc.model.ModelManager.initialize(ModelManager.java:304)
	at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
	at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:96)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:283)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:129)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:497)
	... 51 more

**Comment by youyong205** [comment]
jdk 版本 1.7 79 小版本以下，才可以~你试试换个版本

**Comment by fqtyfz** [comment]
看到修正1.8的问题了，试了一下，果然正常了。
