### ISSUE TITLE
启动没问题，提交日志没问题，但实时查看，没数据

### ISSUE THREAD

**Issue by fqtyfz** [dianping/cat#1048]
public static void main(String[] args) {
		Cat.newTransaction("logTransaction", "logTransaction");
		Cat.newEvent("logEvent", "logEvent");
		Cat.newTrace("logTrace", "logTrace");
		Cat.newHeartbeat("logHeartbeat", "logHeartbeat");
		Throwable cause = new Throwable();
		Cat.logError(cause);
		Cat.logError("message", cause);
		Cat.logTrace("logTrace", "<trace>");
		Cat.logTrace("logTrace", "<trace>", Trace.SUCCESS, "data");
		Cat.logMetric("logMetric", "test", "test");
		Cat.logMetricForCount("logMetricForCount");
		Cat.logMetricForCount("logMetricForCount", 4);
		Cat.logMetricForDuration("logMetricForDuration", 100);
		Cat.logMetricForSum("logMetricForSum", 100);
		Cat.logMetricForSum("logMetricForSum", 100, 100);
		Cat.logEvent("RemoteLink", "Call", Message.SUCCESS, "Cat-0a010680-384736-2061");
		Cat.logEvent("EventType", "EventName");
		Cat.logHeartbeat("logHeartbeat", "logHeartbeat", Message.SUCCESS, null);
	}
以上程序测试，输出：
Logger file D:\data\applogs\cat\cat_20161117.log
[11-17 15:12:28.028] [WARN] [cat] Cat is lazy initialized!
Task(cat-TcpSocketSender) is shutdown! 
Task(cat-TcpSocketSender-ChannelManager) is shutdown! 
Task(cat-merge-atomic-task) is shutdown! 
Task(cat-StatusUpdateTask) is shutdown! 

但是在监控端，进行实时查看时却没有任何数据，查看日志如下：
[11-17 14:55:00.506] [ERROR] [Thread] null
java.lang.NullPointerException
	at com.dianping.cat.report.page.dependency.graph.TopologyGraphManager$DependencyReloadTask.queryAllDomains(TopologyGraphManager.java:239)
	at com.dianping.cat.report.page.dependency.graph.TopologyGraphManager$DependencyReloadTask.run(TopologyGraphManager.java:254)
	at java.lang.Thread.run(Thread.java:745)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
是不是那里的配置有问题？

**Comment by qmwu2000** [comment]
cat是异步发消息的，你需要sleep一会

发自我的 iPhone

**Comment by fqtyfz** [comment]
Thread.sleep(300000);
我对发送的 数据抓包看了下：
GET /cat/s/router?domain=ICFSERVER&ip=192.168.1.8&op=json HTTP/1.1
User-Agent: Java/1.8.0_73
Host:192.168.1.153:7070
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive


HTTP/1.1 200 
Content-Type: text/html;charset=UTF-8
Content-Length: 52
Date: Fri, 18 Nov 2016 00:55:06 GMT

{"kvs":{"routers":"127.0.0.1:2280;","sample":"1.0"}}

不断的在请求这个url，但好像没看到有发送日志的包

**Comment by fqtyfz** [comment]
我发现是查看event的时候，500了
cat/r/e?domain=cat&ip=All&date=2016111813&reportType=day&op=view
然后transaction就看不到数据了
[11-18 13:11:25.909] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/e
java.lang.RuntimeException: Error occured during handling outbound action(e)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:404)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:314)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:202)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:110)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(e)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
	... 40 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.event.Handler.handleOutbound(com.dianping.cat.report.page.event.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.event.Context@43f62a26])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:52)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 42 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.event.transform.AllMachineMerger.visitEventReport(AllMachineMerger.java:30)
	at com.dianping.cat.report.page.event.transform.EventMergeHelper.mergeAllIps(EventMergeHelper.java:12)
	at com.dianping.cat.report.page.event.Handler.handleOutbound(Handler.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 43 more
[11-18 13:12:00.503] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-16) ...
[11-18 13:12:00.504] [ERROR] [Thread] null
java.lang.NullPointerException
	at com.dianping.cat.report.page.dependency.graph.TopologyGraphManager$DependencyReloadTask.queryAllDomains(TopologyGraphManager.java:239)
	at com.dianping.cat.report.page.dependency.graph.TopologyGraphManager$DependencyReloadTask.run(TopologyGraphManager.java:254)
	at java.lang.Thread.run(Thread.java:745)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
[11-18 13:13:00.504] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-17) ...
[11-18 13:13:00.505] [ERROR] [Thread] null

**Comment by lytofb** [comment]
你好，这个问题我也遇到了，请问怎么解决的
