### ISSUE TITLE
配置CatFilter后，异常！是该自己写个拦截器，不用catFilter?

### ISSUE THREAD

**Issue by fqtyfz** [dianping/cat#1050]
WARN - Caught an exception while evaluating expression 'cat-page-uri' against value stack
java.lang.NumberFormatException: For input string: "com.gs.common.base.utils.PageManager@582446f8
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at ognl.OgnlOps.longValue(OgnlOps.java:220)
        at ognl.OgnlOps.subtract(OgnlOps.java:887)
        at ognl.ASTSubtract.getValueBody(ASTSubtract.java:51)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.ASTSubtract.getValueBody(ASTSubtract.java:49)
        at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
        at ognl.SimpleNode.getValue(SimpleNode.java:258)
        at ognl.Ognl.getValue(Ognl.java:467)
        at ognl.Ognl.getValue(Ognl.java:431)
        at com.opensymphony.xwork2.ognl.OgnlUtil$2.execute(OgnlUtil.java:344)
        at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecute(OgnlUtil.java:383)
        at com.opensymphony.xwork2.ognl.OgnlUtil.getValue(OgnlUtil.java:342)
        at com.opensymphony.xwork2.ognl.OgnlValueStack.getValueUsingOgnl(OgnlValueStack.java:294)
        at com.opensymphony.xwork2.ognl.OgnlValueStack.tryFindValue(OgnlValueStack.java:277)
        at com.opensymphony.xwork2.ognl.OgnlValueStack.tryFindValueWhenExpressionIsNotNull(OgnlVal
        at com.opensymphony.xwork2.ognl.OgnlValueStack.findValue(OgnlValueStack.java:239)
        at com.opensymphony.xwork2.ognl.OgnlValueStack.findValue(OgnlValueStack.java:301)
        at org.apache.struts2.dispatcher.StrutsRequestWrapper.getAttribute(StrutsRequestWrapper.ja
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.customizeUri(CatFilter.java:275)
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:333)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
        at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:202)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
        at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:110)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
        at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:48)

**Comment by qmwu2000** [comment]
应该是你的Filter有问题，request.getAttribute("cat-page-uri")应该返回一个String类型的结果，最好不要用struts的OGNL表达式计算。
