### ISSUE TITLE
The valid characters are defined in RFC 7230 and RFC 3986

### ISSUE THREAD

**Issue by fqtyfz** [dianping/cat#1051]
在修改机器分组配置的时候，
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
       at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:467)
       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667)
       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
       at java.lang.Thread.run(Thread.java:745)

修改不了。

**Comment by qmwu2000** [comment]
应该是你输入内容中有HTTP协议不支持的字符，换一个浏览器试试。

**Comment by youyong205** [comment]
.../conf/catalina.properties中，找到最后注释掉的一行 ＃tomcat.util.http.parser.HttpParser.requestTargetAllow=| 　，改成tomcat.util.http.parser.HttpParser.requestTargetAllow=|{}，表示把｛｝放行

**Comment by youyong205** [comment]
https://www.cnblogs.com/wsygdb/p/7661220.html 解决链接
