### ISSUE TITLE
mvn cat:install  时 mysql 语句报错

### ISSUE THREAD

**Issue by sangszhou** [dianping/cat#1067]
在 closed issues 中看到有人提出过这个问题，似乎还是时间的 default 值问题

mysql version 5.7.16

```
[INFO] Creating tables ...
[ERROR]
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid default value for 'creation_date'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2677)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2627)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:841)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:681)
	at com.dianping.cat.plugin.InstallMojo.createTables(InstallMojo.java:90)
	at com.dianping.cat.plugin.InstallMojo.setupDatabase(InstallMojo.java:195)
	at com.dianping.cat.plugin.InstallMojo.execute(InstallMojo.java:107)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by sangszhou** [comment]
出问题的 table 是 

```
CREATE TABLE `businessReport` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` tinyint(4) NOT NULL COMMENT '报表类型 报表数据格式, 1/Binary, 2/xml , 3/json',
  `name` varchar(20) NOT NULL COMMENT '报表名称',
  `ip` varchar(50) NOT NULL COMMENT '报表来自于哪台机器',
  `productLine` varchar(50) NOT NULL COMMENT '指标来源于哪个产品组',
  `period` timestamp NOT NULL COMMENT '报表时间段',
  `content` longblob COMMENT '用于存放报表的具体内容',
  `creation_date` timestamp NOT NULL COMMENT '报表创建时间',
  PRIMARY KEY (`id`),
  KEY `IX_Period_productLine_name` (`period`,`productLine`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPRESSED COMMENT='用于存放业务监控实时报表信息，处理之后的结果';
```

**Comment by kangyonggan** [comment]
我也报这个错，我的解决方案是手动执行sql，具体做法如下：
### 1. 修改`cat-maven-plugin`模块下的`InstallMojo.java`:
form:

```
@Override
public void execute() throws MojoExecutionException, MojoFailureException {
	getLog().info("Preparing Cat environment...");

	validate();

	if (setupDatabase() && setupConfigurationFiles()) {
		getLog().info("Preparing Cat environment ... DONE");
		getLog().info("Use following command line to start local Cat server:");
		getLog().info("   cd cat-home; mvn jetty:run");
		getLog().info("Please open http://localhost:2281/cat in your browser");
	}
}
```

to:

```
@Override
public void execute() throws MojoExecutionException, MojoFailureException {
	getLog().info("Preparing Cat environment...");

	validate();

	if (setupConfigurationFiles()) {
		getLog().info("Preparing Cat environment ... DONE");
		getLog().info("Use following command line to start local Cat server:");
		getLog().info("   cd cat-home; mvn jetty:run");
		getLog().info("Please open http://localhost:2281/cat in your browser");
	}
}
```

### 2. cd到`cat-maven-plugin`目录下`mvn clean install`,然后重新执行`mvn cat:install`

### 3. 最后手动执行`Cat.sql`里面的sql（手动执行不会报错）

**Comment by sangszhou** [comment]
@kangyonggan 我记得手动执行也报错了。按照之前的一个 issue, 把 timestamp 改成了 datetime 才正常

**Comment by landys** [comment]
这是因为mysql设置了strict模式，会设置`NO_ZERO_DATE`，使得timstamp的default value不能为0引起的。看看my.cnf里的sql_mode是不是有`STRICT_TRANS_TABLES`或者`TRADITIONAL`，这两个都是strict模式，改为`ANSI`，再重启下mysql就可以了。或者把sql中creation_date的default值显示指定为其他非0值也可以。@sangszhou

**Comment by youyong205** [comment]
收到
