### ISSUE TITLE
java.io.UnixFileSystem.createFileExclusively

### ISSUE THREAD

**Issue by liwenxian** [dianping/cat#1072]
java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at org.unidal.lookup.ContainerLoader$ContainerConfigurationDecorator.process(ContainerLoader.java:222)
        at org.unidal.lookup.ContainerLoader.preConstruction(ContainerLoader.java:155)
        at org.unidal.lookup.ContainerLoader.getDefaultContainer(ContainerLoader.java:104)
        at org.unidal.lookup.ContainerLoader.getDefaultContainer(ContainerLoader.java:89)
        at com.dianping.cat.Cat.initialize(Cat.java:105)
        at com.dianping.cat.Cat.checkAndInitialize(Cat.java:48)
        at com.dianping.cat.Cat.getProducer(Cat.java:98)
        at com.dianping.cat.Cat.newTransaction(Cat.java:315)

**Comment by qmwu2000** [comment]
运行cat的普通用户没有创建临时文件的权限，试试在jvm参数中加：-Djava.io.tmpdir=...



发自我的 iPhone
