### ISSUE TITLE
看着服务起来了，但后面报错：Unable to get component: class com.dianping.cat.report.task.DefaultTaskConsumer.

### ISSUE THREAD

**Issue by fqtyfz** [dianping/cat#1078]
[01-10 10:58:02.311] [INFO] [ServerConfigManager] Loading configuration file(E:\data\appdatas\cat\server.xml) ...
[01-10 10:58:02.324] [INFO] [ServerConfigManager] CAT server is running with hdfs,false
[01-10 10:58:02.398] [INFO] [ServerConfigManager] CAT server is running with alert,false
[01-10 10:58:02.398] [INFO] [ServerConfigManager] CAT server is running with job,true
[01-10 10:58:02.399] [INFO] [ServerConfigManager] <?xml version="1.0" encoding="utf-8"?>
<config local-mode="false" job-machine="true" alert-machine="false" hdfs-machine="false" send-machine="true">
   <storage local-base-dir="/data/appdatas/cat/bucket/" upload-thread="5" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7">
   </storage>
   <consumer>
      <long-config default-url-threshold="1000" default-sql-threshold="100" default-service-threshold="50">
      </long-config>
   </consumer>
   <console default-domain="/" show-cat-domain="true">
      <remote-servers>127.0.0.1:2280</remote-servers>
   </console>
</config>

[01-10 10:58:02.631] [INFO] [TcpSocketReceiver] start netty server!
[01-10 10:58:02.631] [INFO] [DefaultModuleContext] Current working directory is E:\apache-tomcat-8.5.8\bin
[01-10 10:58:02.646] [INFO] [DefaultClientConfigManager] Global config file(\data\appdatas\cat\client.xml) found.
[01-10 10:58:02.646] [INFO] [DefaultClientConfigManager] Find domain name cat from app.properties.
[01-10 10:58:02.654] [INFO] [DefaultTransportManager] Remote CAT servers: [/127.0.0.1:2280]
[01-10 10:58:04.706] [INFO] [ChannelManager] Connected to CAT server at /127.0.0.1:2280
[01-10 10:58:04.707] [INFO] [ChannelManager] success when init CAT server, new active holderactive future :/127.0.0.1:2280 index:0 ip:127.0.0.1 server config:null
[01-10 10:58:04.708] [INFO] [DefaultModuleContext] Thread group(cat) created.
[01-10 10:58:04.709] [INFO] [DefaultModuleContext] Starting thread(cat-TcpSocketSender) ...
[01-10 10:58:04.709] [INFO] [DefaultModuleContext] Starting thread(cat-TcpSocketSender-ChannelManager) ...
[01-10 10:58:04.709] [INFO] [DefaultModuleContext] Starting thread(cat-merge-atomic-task) ...
[01-10 10:58:04.716] [INFO] [DefaultModuleContext] Starting thread(cat-StatusUpdateTask) ...
[01-10 10:58:04.771] [INFO] [DefaultDataSourceProvider] Loading data sources from \data\appdatas\cat\datasources.xml ...
[01-10 10:58:04.910] [INFO] [JdbcDataSource] Connecting to JDBC data source(cat) with properties(driver=com.mysql.jdbc.Driver, url=jdbc:mysql://202.100.92.148:3306/cat?useUnicode=true&autoReconnect=true, user=root) ...
[01-10 10:58:05.198] [INFO] [JdbcDataSource] Connected to JDBC data source(cat).
[01-10 10:58:05.234] [INFO] [DefaultModuleContext] Starting thread(cat-Server-Filter-Config-Reload) ...
[01-10 10:58:05.272] [INFO] [DefaultModuleContext] Starting thread(cat-LocalMessageBucketManager-BlockDumper) ...
[01-10 10:58:05.273] [INFO] [DefaultModuleContext] Starting thread(cat-LocalMessageBucketManager-OldMessageMover) ...
[01-10 10:58:05.274] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-0) ...
[01-10 10:58:05.274] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-1) ...
[01-10 10:58:05.275] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-2) ...
[01-10 10:58:05.275] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-4) ...
[01-10 10:58:05.275] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-3) ...
[01-10 10:58:05.275] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-5) ...
[01-10 10:58:05.275] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-6) ...
[01-10 10:58:05.275] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-8) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-10) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-7) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-11) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-16) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-17) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-9) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-12) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-13) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-14) ...
[01-10 10:58:05.276] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-15) ...
[01-10 10:58:05.277] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-18) ...
[01-10 10:58:05.277] [INFO] [DefaultModuleContext] Starting thread(cat-Message-Gzip-19) ...
[01-10 10:58:05.407] [INFO] [Period] Starting 10 tasks in period [2017-01-10 10:00:00, 2017-01-10 10:59:59]
[01-10 10:58:05.407] [INFO] [DefaultModuleContext] Thread group(Cat-RealtimeConsumer) created.
[01-10 10:58:05.408] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-ProblemAnalyzer-10-0) ...
[01-10 10:58:05.408] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-ProblemAnalyzer-10-1) ...
[01-10 10:58:05.408] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-HeartbeatAnalyzer-10-0) ...
[01-10 10:58:05.408] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-TopAnalyzer-10-0) ...
[01-10 10:58:05.409] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-MetricAnalyzer-10-0) ...
[01-10 10:58:05.409] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-CrossAnalyzer-10-0) ...
[01-10 10:58:05.409] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-DumpAnalyzer-10-0) ...
[01-10 10:58:05.409] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-CrossAnalyzer-10-1) ...
[01-10 10:58:05.410] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-DumpAnalyzer-10-1) ...
[01-10 10:58:05.410] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-EventAnalyzer-10-1) ...
[01-10 10:58:05.410] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-TransactionAnalyzer-10-0) ...
[01-10 10:58:05.410] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-EventAnalyzer-10-0) ...
[01-10 10:58:05.410] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-StorageAnalyzer-10-0) ...
[01-10 10:58:05.410] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-StateAnalyzer-10-0) ...
[01-10 10:58:05.410] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-TransactionAnalyzer-10-1) ...
[01-10 10:58:05.410] [INFO] [DefaultModuleContext] Starting thread(cat-RealtimeConsumer-PeriodManager) ...
[01-10 10:58:05.445] [INFO] [DefaultModuleContext] Starting thread(cat-Config-Reload) ...
[01-10 10:58:05.455] [INFO] [Period] Starting 10 tasks in period [2017-01-10 11:00:00, 2017-01-10 11:59:59]
[01-10 10:58:05.456] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-TopAnalyzer-11-0) ...
[01-10 10:58:05.456] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-ProblemAnalyzer-11-1) ...
[01-10 10:58:05.456] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-ProblemAnalyzer-11-0) ...
[01-10 10:58:05.456] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-MetricAnalyzer-11-0) ...
[01-10 10:58:05.456] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-HeartbeatAnalyzer-11-0) ...
[01-10 10:58:05.456] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-CrossAnalyzer-11-1) ...
[01-10 10:58:05.457] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-CrossAnalyzer-11-0) ...
[01-10 10:58:05.457] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-DumpAnalyzer-11-0) ...
[01-10 10:58:05.457] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-DumpAnalyzer-11-1) ...
[01-10 10:58:05.457] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-StorageAnalyzer-11-0) ...
[01-10 10:58:05.458] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-StateAnalyzer-11-0) ...
[01-10 10:58:05.458] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-EventAnalyzer-11-1) ...
[01-10 10:58:05.458] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-EventAnalyzer-11-0) ...
[01-10 10:58:05.458] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-TransactionAnalyzer-11-0) ...
[01-10 10:58:05.458] [INFO] [DefaultModuleContext] Starting thread(Cat-RealtimeConsumer-TransactionAnalyzer-11-1) ...
[01-10 10:58:05.607] [ERROR] [StandardWrapper] Servlet initializing failed. javax.servlet.ServletException: java.lang.RuntimeException: Error when initializing modules! Exception: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.report.task.DefaultTaskConsumer.
javax.servlet.ServletException: java.lang.RuntimeException: Error when initializing modules! Exception: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.report.task.DefaultTaskConsumer.
	at com.dianping.cat.servlet.CatServlet.initComponents(CatServlet.java:52)
	at org.unidal.web.AbstractContainerServlet.init(AbstractContainerServlet.java:51)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:989)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4913)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5223)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error when initializing modules! Exception: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.report.task.DefaultTaskConsumer.
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:46)
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:24)
	at com.dianping.cat.servlet.CatServlet.initComponents(CatServlet.java:48)
	... 17 more
Caused by: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.report.task.DefaultTaskConsumer.
	at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:98)
	at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:90)
	at com.dianping.cat.CatHomeModule.execute(CatHomeModule.java:45)
	at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10)
	at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:59)
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42)
	... 19 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'com.dianping.cat.report.task.DefaultTaskConsumer', it could not be started.
      role: com.dianping.cat.report.task.DefaultTaskConsumer
  roleHint: default
classRealm: plexus.core

**Comment by youyong205** [comment]
用jdk8 tomcat8 用标准环境跑跑试试，另外打包用标准mvn install

**Comment by liliang8858** [comment]
[04-23 20:09:01.239] [ERROR] [TcpSocketSender] Error when try connecting to /127.0.0.1:28850
java.lang.RuntimeException: Unable to get component: class com.dianping.cat.report.task.DefaultTaskConsumer.
[04-23 20:09:01.844] [ERROR] [StandardWrapper] Servlet initializing failed. javax.servlet.ServletException: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.report.task.DefaultTaskConsumer.
javax.servlet.ServletException: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.report.task.DefaultTaskConsumer.
        at com.dianping.cat.servlet.CatServlet.initComponents(CatServlet.java:52)
        at org.unidal.web.AbstractContainerServlet.init(AbstractContainerServlet.java:47)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4962)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5274)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1856)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.report.task.DefaultTaskConsumer.
        at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:95)
        at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:87)
        at com.dianping.cat.CatHomeModule.execute(CatHomeModule.java:47)
        at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10)
        at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:63)
        at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42)
        at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:24)
        at com.dianping.cat.servlet.CatServlet.initComponents(CatServlet.java:48)
        ... 17 more
Caused by: org.unidal.lookup.ComponentLookupException: Error when initializing component!
      role: com.dianping.cat.report.task.ReportFacade
  roleHint: default
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:93)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
