### ISSUE TITLE
cat埋点，栈溢出问题

### ISSUE THREAD

**Issue by ztajy** [dianping/cat#1130]
您好，在用cat的过程中，当一个方法里面有for循环，且循环次数比较多的情况下，每次循环cat都埋点，会有栈溢出的异常，请问，这种问题cat里面有没有比较好的解决办法，急盼，谢谢。

**Comment by 54ebb** [comment]
需要每次循环都埋点？采样？

**Comment by ztajy** [comment]
我这边是写了几个拦截器，有spring mvc的interceptor，拦截service的aop，dubbo服务的filter，这样对所有项目中写的代码都可现实链路跟踪，有些场景，开发人员就需要多次的for循环，才出现了栈溢出的情况，虽然也可以从各拦截器的配置上排除对某些方法的拦截，但都比较事后，想问问cat上有没有好的解决办法。

**Comment by ztajy** [comment]
貌似cat上有个递归，最后栈溢出了。

Caused by: java.lang.StackOverflowError 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526) 
at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526)

**Comment by youyong205** [comment]
这个问题并不是堆栈溢出，而是你埋点的transaction 并没有关闭，transction的complete 必须在fianlly里面

**Comment by zgy202135** [comment]
各位大佬，你们是怎么解决的啊 @youyong205
