### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by wenzuojing** [dianping/cat#1140]
环境: tomcat 8  jdk 7
日志异常：
[05-19 16:42:34.500] [ERROR] [Thread] Error when sending message over TCP socket!
java.lang.IllegalStateException: Can't overwrite cause with java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already.  Could not load io.netty.channel.AbstractChannelHandlerContext$10.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
        at java.lang.Throwable.initCause(Throwable.java:456)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1304)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1184)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1145)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged(DefaultChannelPipeline.java:802)
        at io.netty.channel.ChannelOutboundBuffer.setUnwritable(ChannelOutboundBuffer.java:526)
        at io.netty.channel.ChannelOutboundBuffer.incrementPendingOutboundBytes(ChannelOutboundBuffer.java:171)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:726)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:243)
        at com.dianping.cat.message.io.TcpSocketSender.sendInternal(TcpSocketSender.java:245)
        at com.dianping.cat.message.io.TcpSocketSender.run(TcpSocketSender.java:179)
        at java.lang.Thread.run(Thread.java:745)
        at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
Caused by: java.lang.ClassNotFoundException
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1303)
        ... 15 more
[05-19 16:43:24.517] [INFO] [ChannelManager] close channel /10.135.41.32:2280

由于发送失败，MessageQueue 积累大量的对象，应用内存益处崩溃

**Comment by jianf109** [comment]
请问这个问题是有解决了么，我现在遇到一个情况，cat系统挂了，然后cat-client端会发大量的连接错误日志：[ChannelManager] Error when try connecting to /10.164.x.x:2280 ，如果没注意cat系统的话，DefaultMessageQueue对象积累到GC也回收不了，最终挂掉。如下图
![image](https://user-images.githubusercontent.com/14845710/56728078-9387b800-6784-11e9-8ce9-8ee350fda484.png)
![image](https://user-images.githubusercontent.com/14845710/56728084-98e50280-6784-11e9-81c9-316e0ccf1c60.png)

**Comment by trendhu** [comment]
我看该问题已经关闭了，但解决方案是什么？
