### ISSUE TITLE
机器分组配置无法添加，编辑

### ISSUE THREAD

**Issue by liangrui1988** [dianping/cat#1156]
http://192.168.20.243:7061/cat/s/config?op=domainGroupConfigSubmit&domain=xC&content={%22id%22:%22xC%22,%22groups%22:{}}

`Request URL:http://192.168.20.243:7061/cat/s/config?op=domainGroupConfigSubmit&domain=xC&content={%22id%22:%22xC%22,%22groups%22:{}}
Request Method:GET
Status Code:400 Bad Request
Remote Address:192.168.20.243:7061
Referrer Policy:no-referrer-when-downgrade`

400：语法不对吗，

**Comment by liangrui1988** [comment]
![qq 20170801165047](https://user-images.githubusercontent.com/7435076/28817037-8f7414ae-76d9-11e7-9a04-ad01d217c5c8.png) 为什么第二条无法修改，我打开都是空白的，我就写完信息，提交上去，结果新增了一条，还有修改第一条警告信息时，又出现400，是参数太长了吗？感觉在测BUG呢？

`

Name
--


`

**Comment by liangrui1988** [comment]
点击 业务大盘出错，这个是什么原因呢
[08-01 16:58:07.290] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/metric
java.lang.RuntimeException: Error occured during handling outbound action(metric)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:332)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:120)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:330)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:137)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:330)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:266)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:330)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:73)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:330)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:40)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(metric)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
	... 39 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.metric.Handler.handleOutbound(com.dianping.cat.report.page.metric.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.metric.Context@7b23d228])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:52)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 41 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.consumer.metric.model.transform.BaseVisitor.visitMetricReport(BaseVisitor.java:41)
	at com.dianping.cat.report.graph.metric.impl.MetricDataFetcherImpl$MetricDataBuilder.visitMetricReport(MetricDataFetcherImpl.java:72)
	at com.dianping.cat.report.graph.metric.impl.MetricDataFetcherImpl.buildGraphData(MetricDataFetcherImpl.java:19)
	at com.dianping.cat.report.page.metric.GraphCreator.buildGraphData(GraphCreator.java:125)
	at com.dianping.cat.report.page.metric.GraphCreator.queryMetricValueByDate(GraphCreator.java:249)
	at com.dianping.cat.report.page.metric.GraphCreator.prepareAllData(GraphCreator.java:216)
	at com.dianping.cat.report.page.metric.GraphCreator.buildChartsByProductLine(GraphCreator.java:63)
	at com.dianping.cat.report.page.metric.GraphCreator.buildDashboardByTag(GraphCreator.java:103)
	at com.dianping.cat.report.page.metric.Handler.buildLineCharts(Handler.java:53)
	at com.dianping.cat.report.page.metric.Handler.handleOutbound(Handler.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 42 more

**Comment by youyong205** [comment]
感觉自己查查问题。http的code 4xx，就是这个请求根本没有到服务端。5xx的错误才是服务端内部错误。另外你得想想，为什么其他人都可以，是不是我哪里用错了

**Comment by youyong205** [comment]
另外业务指标的key，不要用乱七八糟的中文，都是英文字符，一些特殊字符也不要带。
