### ISSUE TITLE
Cat偶现NPE问题

### ISSUE THREAD

**Issue by zhaojiandong** [dianping/cat#1174]
### 问题描述
Cat.newTransaction的时候会出现NPE的问题，深入调用是getProducer()方法获取了一个null的m_producer；一般会在应用启动的时候立刻出现

### 报错异常
```
Caused by: java.nio.BufferUnderflowException
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.DirectByteBuffer.getLong(DirectByteBuffer.java:772)
```
### 代码分析

MessageIdFactory.initialize
```
public void initialize(String domain) throws IOException {
  .....
  File mark = createMarkFile(domain);
  m_markFile = new RandomAccessFile(mark, "rw");
  m_byteBuffer = m_markFile.getChannel().map(MapMode.READ_WRITE, 0, 20);

  if (m_byteBuffer.limit() > 0) {
    int index = m_byteBuffer.getInt();
    // 此处getLong会有报字节不够的情况，position理论上在getInt之后会是4，但是有可能是16，所以getLong报错 
    long lastTimestamp = m_byteBuffer.getLong();
    if (lastTimestamp == m_timestamp) { 
       m_index = new AtomicInteger(index + 10000);
    } else {
       m_index = new AtomicInteger(0);
     }
  }
  saveMark();
}
```

ChannelManager.run，异步线程一直在向m_byteBuffer中写入数据，修改了他position的值
```
public void run() {
  while (m_active) {
    // 此处有个异步线程一直在saveMask,向m_byteBuffer写入数据，修改了position的值
    m_idfactory.saveMark();
    checkServerChanged();
    ChannelFuture activeFuture = m_activeChannelHolder.getActiveFuture();
    List<InetSocketAddress> serverAddresses = m_activeChannelHolder.getServerAddresses();
    doubleCheckActiveServer(activeFuture);
    reconnectDefaultServer(activeFuture, serverAddresses);
    .....
  }
}
```

### 修改建议

MessageIdFactory中增加一个变量volatitle bool m_init=false。异步线程需要在MessageIdFactory.initialize()方法执行完毕之后才能访问saveMask()方法

```
public void run() {
  while (m_active) {
    if(m_idfactory.isInit()){
      m_idfactory.saveMark();
      checkServerChanged();
      ChannelFuture activeFuture = m_activeChannelHolder.getActiveFuture();
      List<InetSocketAddress> serverAddresses = m_activeChannelHolder.getServerAddresses();
      doubleCheckActiveServer(activeFuture);
      reconnectDefaultServer(activeFuture, serverAddresses);
      .....
    }
  }
}
```

**Comment by youyong205** [comment]
这个我们研究下

**Comment by youyong205** [comment]
可能/data/目录没有权限相关吧
