### ISSUE TITLE
请问从cat-alpha-1.4.0升级到2.0 是否是无损兼容升级的？还是说完全不兼容？ 谢谢

### ISSUE THREAD

**Issue by shllove** [dianping/cat#1190]
如标题

**Comment by qmwu2000** [comment]
应该兼容的


发自我的 iPhone

**Comment by shllove** [comment]
我在升级替换过程中报错，是否需要调整什么配置？

[11-02 16:04:50.731] [ERROR] [ByteToMessageDecoder] Unable to lookup component(com.dianping.cat.analysis.MessageConsumer:default).
org.unidal.lookup.LookupException: Unable to lookup component(com.dianping.cat.analysis.MessageConsumer:default).
        at org.unidal.lookup.ContainerHolder.lookup(ContainerHolder.java:37)
        at org.unidal.lookup.ContainerHolder.lookup(ContainerHolder.java:28)
        at com.dianping.cat.analysis.DefaultMessageHandler.handle(DefaultMessageHandler.java:24)
        at com.dianping.cat.analysis.TcpSocketReceiver$MessageDecoder.decode(TcpSocketReceiver.java:147)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.lookup.ComponentLookupException: Error when initializing component!
      role: com.dianping.cat.analysis.MessageAnalyzerManager
  roleHint: default
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:92)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.MyPlexusContainer.lookup(MyPlexusContainer.java:83)
        at org.unidal.lookup.ContainerHolder.lookup(ContainerHolder.java:33)
        ... 14 more
Caused by: org.unidal.lookup.LookupException: Unable to lookup component map(com.dianping.cat.analysis.MessageAnalyzer).
        at org.unidal.lookup.ContainerHolder.lookupMap(ContainerHolder.java:57)
        at com.dianping.cat.analysis.DefaultMessageAnalyzerManager.initialize(DefaultMessageAnalyzerManager.java:101)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88)
        ... 26 more
Caused by: org.unidal.lookup.ComponentLookupException: Error when initializing component!
      role: com.dianping.cat.config.server.ServerFilterConfigManager

**Comment by duguyixiaono1** [comment]
升级后，配置页面无法登录，https://github.com/dianping/cat/pull/1170

**Comment by tanxd2002** [comment]
我碰到和楼主一样的问题

**Comment by zhuhuogeng** [comment]
我也遇到这个问题了，请问一下你找到原因了吗

**Comment by balingmo403** [comment]
解决方法：　server端的client.xml 有问题，我的解决方法是：把本机ip改成127.0.0.1。<?xml version="1.0" encoding="utf-8"?>

<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
	<servers>
		
		<server ip="127.0.0.1" port="2280" http-port="8076" />
		
		
	</servers>
</config>
