### ISSUE TITLE
编译无法通过，也是醉了。是你们maven仓库的问题吧？

### ISSUE THREAD

**Issue by netyjq** [dianping/cat#1232]
C:\dev\projects\cat>mvn clean install -DskipTests -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] parent
[INFO] cat-client
[INFO] cat-core
[INFO] cat-hadoop
[INFO] cat-consumer
[INFO] cat-home
[INFO] cat-maven-plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building parent 2.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ parent ---
[INFO]
[INFO] --- maven-source-plugin:2.2:jar-no-fork (attach-sources) @ parent ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ parent ---
[INFO] Installing C:\dev\projects\cat\pom.xml to C:\Users\netyj\.m2\repository\com\dianping\cat\parent\2.0.0\parent-2.0.0.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building cat-client 2.0.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b07-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b08-SNAPSHOT is missing, no dependency information available
Downloading: http://unidal.org/nexus/content/repositories/releases/org/unidal/framework/foundation-service/4.0.0/foundation-service-4.0.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent ............................................. SUCCESS [  0.413 s]
[INFO] cat-client ......................................... FAILURE [  0.806 s]
[INFO] cat-core ........................................... SKIPPED
[INFO] cat-hadoop ......................................... SKIPPED
[INFO] cat-consumer ....................................... SKIPPED
[INFO] cat-home ........................................... SKIPPED
[INFO] cat-maven-plugin ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.368 s
[INFO] Finished at: 2018-04-12T13:30:18+08:00
[INFO] Final Memory: 12M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cat-client: Could not resolve dependencies for project com.dianping.cat:cat-client:jar:2.0.0: Could not transfer artifact
org.unidal.framework:foundation-service:jar:4.0.0 from/to unidal.releases (http://unidal.org/nexus/content/repositories/releases/): GET request of: org/unidal/frame
work/foundation-service/4.0.0/foundation-service-4.0.0.jar from unidal.releases failed: Premature end of Content-Length delimited message body (expected: 323194; re
ceived: 66259 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project cat-client: Could not resolve dependencies for project com.dianping.cat:ca
t-client:jar:2.0.0: Could not transfer artifact org.unidal.framework:foundation-service:jar:4.0.0 from/to unidal.releases (http://unidal.org/nexus/content/repositor
ies/releases/): GET request of: org/unidal/framework/foundation-service/4.0.0/foundation-service-4.0.0.jar from unidal.releases failed
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.dianping.cat:cat-client:jar:2.0.0: Could not trans
fer artifact org.unidal.framework:foundation-service:jar:4.0.0 from/to unidal.releases (http://unidal.org/nexus/content/repositories/releases/): GET request of: org
/unidal/framework/foundation-service/4.0.0/foundation-service-4.0.0.jar from unidal.releases failed
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not transfer artifact org.unidal.framework:foundation-service:jar:4.0.0 from/to unidal
.releases (http://unidal.org/nexus/content/repositories/releases/): GET request of: org/unidal/framework/foundation-service/4.0.0/foundation-service-4.0.0.jar from
unidal.releases failed
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.unidal.framework:foundation-service:jar:4.0.0 from/to unidal.r
eleases (http://unidal.org/nexus/content/repositories/releases/): GET request of: org/unidal/framework/foundation-service/4.0.0/foundation-service-4.0.0.jar from un
idal.releases failed
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.unidal.framework:foundation-service:jar:4.0.0 from/to unidal.relea
ses (http://unidal.org/nexus/content/repositories/releases/): GET request of: org/unidal/framework/foundation-service/4.0.0/foundation-service-4.0.0.jar from unidal
.releases failed
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 27 more
Caused by: org.apache.maven.wagon.TransferFailedException: GET request of: org/unidal/framework/foundation-service/4.0.0/foundation-service-4.0.0.jar from unidal.re
leases failed
        at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:363)
        at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:316)
        at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:285)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:97)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
        ... 32 more
Caused by: org.apache.maven.wagon.providers.http.httpclient.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 323194; rec
eived: 66259
        at org.apache.maven.wagon.providers.http.httpclient.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
        at org.apache.maven.wagon.providers.http.httpclient.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
        at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:531)
        at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:353)
        ... 41 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cat-client

**Comment by qmwu2000** [comment]
应该是。我现在在外面，一会回公司看一下。

发自我的 iPhone

**Comment by netyjq** [comment]
作者已修复该问题，非常感谢。
