### ISSUE TITLE
正常启动但是界面不显示监控信息，tomcat日志一直报错

### ISSUE THREAD

**Issue by yaoayao** [dianping/cat#1233]
界面能正常访问，但是监控信息不显示，tomcat8+jdk8+cat2.0.0
tomcat一直滚动报错信息如下：

13-Apr-2018 11:25:17.567 信息 [Cat-RealtimeConsumer-HeartbeatAnalyzer-11-0] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [META-INF/services/javax.xml.parsers.SAXParserFactory]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [META-INF/services/javax.xml.parsers.SAXParserFactory]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1305)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResources(WebappClassLoaderBase.java:933)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1142)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
	at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
	at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
	at com.dianping.cat.status.model.transform.DefaultSaxParser.parseEntity(DefaultSaxParser.java:85)
	at com.dianping.cat.status.model.transform.DefaultSaxParser.parse(DefaultSaxParser.java:62)
	at com.dianping.cat.status.model.transform.DefaultSaxParser.parse(DefaultSaxParser.java:74)
	at com.dianping.cat.consumer.heartbeat.HeartbeatAnalyzer.buildHeartBeatInfo(HeartbeatAnalyzer.java:48)
	at com.dianping.cat.consumer.heartbeat.HeartbeatAnalyzer.processHeartbeat(HeartbeatAnalyzer.java:135)
	at com.dianping.cat.consumer.heartbeat.HeartbeatAnalyzer.processTransaction(HeartbeatAnalyzer.java:156)
	at com.dianping.cat.consumer.heartbeat.HeartbeatAnalyzer.process(HeartbeatAnalyzer.java:127)
	at com.dianping.cat.analysis.AbstractMessageAnalyzer.analyze(AbstractMessageAnalyzer.java:44)
	at com.dianping.cat.analysis.PeriodTask.run(PeriodTask.java:91)
	at java.lang.Thread.run(Thread.java:748)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)

**Comment by LincolnPei** [comment]
@yaoayao 请问下怎么解决的，遇到同样问题，而且导致cpu直接满载了
