### ISSUE TITLE
启动没有问题，第一次访问出现问题

### ISSUE THREAD

**Issue by liliang8858** [dianping/cat#1235]
http://127.0.0.1:8080/cat/r
java.lang.NullPointerException
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:60)
        at org.unidal.web.MVC.service(MVC.java:97)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:83)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:336)
        at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:124)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:334)
        at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:141)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:334)
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:270)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:334)
        at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:73)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:334)
        at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:40)

**Comment by youyong205** [comment]
这个理论上还有其他错误，这个还不是rootcause~
