### ISSUE TITLE
使用Tomcat无法上报数据

### ISSUE THREAD

**Issue by letiantian** [dianping/cat#1264]
使用最新的commit `f217b78b7` ，测试代码：
```
import com.dianping.cat.Cat;
import com.dianping.cat.message.Event;
import com.dianping.cat.message.Transaction;

public class CatExample {

    public static void main(String[] args) throws Exception {

        for(int i=0; i<100;i++) {

            System.out.println("report " + i);

            report();

            Thread.sleep(1000);
        }

    }

    public static void report() throws Exception {
        Transaction t = Cat.getProducer().newTransaction("your-transaction-type", "your-transaction-name");
        try {
            businessOperation();
            Cat.getProducer().logEvent("your-event-type", "your-event-name", Event.SUCCESS, "keyValuePairs");
            t.setStatus(Transaction.SUCCESS);
        } catch (Exception e) {
            Cat.getProducer().logError(e);//用log4j记录系统异常，以便在Logview中看到此信息
            t.setStatus(e);
            throw e;
        } finally {
            t.complete();
        }
    }

    public static void businessOperation() {

    }

}

```

配置的app.name 是 `app.name=cat-demo-001`。

使用 `mvn jetty:run` 运行cat，可以在网址`http://127.0.0.1:2281/cat/r/`看到`cat-demo-001`的数据上报。

但是使用tomcat 时，遇到两个问题。

### **问题1：**
能进入`http://127.0.0.1:8080/cat/r/`，但是看不到`cat-demo-001`的上报数据。

配置：
`/data/appdatas/cat/client.xml`中2281改成了8080：
```
<server ip="127.0.0.1" port="2280" http-port="8080" />
```

使用 tomcat 8 部署的 cat.war 。

### **问题2：**
访问`实时`中的`Problem`，会出现500错误。查看日志`/data/applogs/cat/cat_20180620.log`，报错如下：
```
Caused by: java.lang.NullPointerException
	at com.dianping.cat.consumer.problem.model.transform.BaseVisitor.visitProblemReport(BaseVisitor.java:52)
	at com.dianping.cat.report.page.problem.Handler.handleOutbound(Handler.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
```

**Comment by youyong205** [comment]
使用tomcat部署，可以对照安装文档检查下步骤。

应该在server.xml  里面的remote-servers，有个端口2281还需要改为8080

**Comment by letiantian** [comment]
嗯 我试一下。但是文档里好像没说。

**Comment by letiantian** [comment]
方法可行。
