### ISSUE TITLE
Readme能再清晰有条理一点吗

### ISSUE THREAD

**Issue by guchensmile** [dianping/cat#1268]
昨天的Readme感觉比今天的还强一点

**Comment by youyong205** [comment]
你可以提下哪里地方看不懂，哪里可以改进，可以在issue下面留言。
或者根据自己理解提交pull request 更好。

**Comment by guchensmile** [comment]
1. 建议增加单机模式的启动教程
2. 之前的例子说使用mvn install进行安装，当时可以同时进行sql的执行创建数据库同时有引导配置数据库，直接会写到xml中，但当前教程列出安装CAT的数据库【一个CAT集群公用一个数据库】不知道用意何在
3. 本人在windows下编译时cat-maven-plugin编译不通过，按道理应该也不影响home下war的部署吧？
4. 另外使用jetty部署，报错显示没有找到数据库cat，但我确实有数据库而且xml里配置也有，我怀疑war没有读xml吗还是其他原因
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
[06-26 22:33:49.049] [WARN] [cat] CAT client was disabled due to no CAT servers configured!
[06-26 22:33:49.049] [WARN] [cat] Cat is lazy initialized!
java.lang.RuntimeException: No data source(cat) defined!
        at org.unidal.dal.jdbc.datasource.DefaultDataSourceManager.getDataSource(DefaultDataSourceManager.java:32)
        at org.unidal.dal.jdbc.transaction.DefaultTransactionManager.getConnection(DefaultTransactionManager.java:97)
        at org.unidal.dal.jdbc.query.mysql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:39)
        at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:21)
        at org.unidal.dal.jdbc.engine.DefaultQueryEngine.querySingle(DefaultQueryEngine.java:114)
        at com.dianping.cat.core.config.ConfigDao.findByName(ConfigDao.java:51)
        at com.dianping.cat.config.server.ServerFilterConfigManager.initialize(ServerFilterConfigManager.java:72)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.ComponentManager.lookupMap(ComponentManager.java:118)
        at org.unidal.lookup.container.MyPlexusContainer.lookupMap(MyPlexusContainer.java:98)
        at org.unidal.lookup.ContainerHolder.lookupMap(ContainerHolder.java:53)
        at com.dianping.cat.analysis.DefaultMessageAnalyzerManager.initialize(DefaultMessageAnalyzerManager.java:101)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.MyPlexusContainer.lookup(MyPlexusContainer.java:83)
        at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:93)
        at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:87)
        at com.dianping.cat.CatHomeModule.execute(CatHomeModule.java:31)
        at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10)
        at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:63)
        at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42)
        at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:24)
        at com.dianping.cat.servlet.CatServlet.initComponents(CatServlet.java:48)
        at org.unidal.web.AbstractContainerServlet.init(AbstractContainerServlet.java:47)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:505)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:579)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:240)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:419)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:386)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
        at org.eclipse.jetty.start.Main.start(Main.java:486)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
org.unidal.dal.jdbc.DalException: Error when executing query(SELECT c.id,c.`name`,c.content,c.creation_date,c.modify_date FROM config c WHERE c.name = ?) failed, proto: Config[content: null, creation-date: null, id: 0, key-id: 0, modify-date: null, name: serverFilter], message: java.lang.RuntimeException: No data source(cat) defined!.
        at org.unidal.dal.jdbc.query.mysql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:72)
        at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:21)
        at org.unidal.dal.jdbc.engine.DefaultQueryEngine.querySingle(DefaultQueryEngine.java:114)
        at com.dianping.cat.core.config.ConfigDao.findByName(ConfigDao.java:51)
        at com.dianping.cat.config.server.ServerFilterConfigManager.initialize(ServerFilterConfigManager.java:72)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.ComponentManager.lookupMap(ComponentManager.java:118)
        at org.unidal.lookup.container.MyPlexusContainer.lookupMap(MyPlexusContainer.java:98)
        at org.unidal.lookup.ContainerHolder.lookupMap(ContainerHolder.java:53)
        at com.dianping.cat.analysis.DefaultMessageAnalyzerManager.initialize(DefaultMessageAnalyzerManager.java:101)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
        at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
        at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
        at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
        at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
        at org.unidal.lookup.container.MyPlexusContainer.lookup(MyPlexusContainer.java:83)
        at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:93)
        at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:87)
        at com.dianping.cat.CatHomeModule.execute(CatHomeModule.java:31)
        at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10)
        at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:63)
        at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42)
        at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:24)
        at com.dianping.cat.servlet.CatServlet.initComponents(CatServlet.java:48)
        at org.unidal.web.AbstractContainerServlet.init(AbstractContainerServlet.java:47)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:192)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:505)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:579)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:240)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:419)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:386)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1572)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1512)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1511)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:220)
        at org.eclipse.jetty.start.Main.start(Main.java:486)
        at org.eclipse.jetty.start.Main.main(Main.java:77)
Caused by: java.lang.RuntimeException: No data source(cat) defined!
        at org.unidal.dal.jdbc.datasource.DefaultDataSourceManager.getDataSource(DefaultDataSourceManager.java:32)
        at org.unidal.dal.jdbc.transaction.DefaultTransactionManager.getConnection(DefaultTransactionManager.java:97)
        at org.unidal.dal.jdbc.query.mysql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:39)
        ... 98 more

**Comment by guchensmile** [comment]
另附编译错误
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ cat-home ---
[INFO] Installing C:\Users\zwl\git\cat\cat-home\target\cat-alpha-2.0.0.war to C:\Users\zwl\.m2\repository\com\dianping\cat\cat-home\2.0.0\cat-home-2.0.0.war
[INFO] Installing C:\Users\zwl\git\cat\cat-home\pom.xml to C:\Users\zwl\.m2\repository\com\dianping\cat\cat-home\2.0.0\cat-home-2.0.0.pom
[INFO] Installing C:\Users\zwl\git\cat\cat-home\target\cat-home-2.0.0-sources.jar to C:\Users\zwl\.m2\repository\com\dianping\cat\cat-home\2.0.0\cat-home-2.0.0-sources.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building cat-maven-plugin 2.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cat-maven-plugin ---
[INFO] Using 'utf-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ cat-maven-plugin ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-plugin-plugin:3.2:descriptor (default-descriptor) @ cat-maven-plugin ---
[INFO] Using 'utf-8' encoding to read mojo metadata.
[INFO] Applying mojo extractor for language: java
[INFO] Mojo extractor for language: java found 1 mojo descriptors.
[INFO] Applying mojo extractor for language: bsh
[INFO] Mojo extractor for language: bsh found 0 mojo descriptors.
[INFO] Applying mojo extractor for language: java-annotations
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent ............................................. SUCCESS [  6.748 s]
[INFO] cat-client ......................................... SUCCESS [ 38.973 s]
[INFO] cat-core ........................................... SUCCESS [ 25.223 s]
[INFO] cat-hadoop ......................................... SUCCESS [  5.718 s]
[INFO] cat-consumer ....................................... SUCCESS [ 36.780 s]
[INFO] cat-home ........................................... SUCCESS [03:02 min]
[INFO] cat-maven-plugin ................................... FAILURE [ 11.317 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:07 min
[INFO] Finished at: 2018-06-26T22:33:44+08:00
[INFO] Final Memory: 52M/447M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.2:descriptor (default-descriptor) on project cat-maven-plugin: Execution default-descriptor of goal org.apache.maven.plugins:maven-plugin-plugin:3.2:descriptor failed: 35368 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cat-maven-plugin

**Comment by youyong205** [comment]
1.建议增加单机模式的启动教程(已经有集群安装明确教程，单机安装无非就是把三台IP部署变成1台机器，另外可以参考第9点，开发环境cat的部署)
2.之前的例子说使用mvn install进行安装，当时可以同时进行sql的执行创建数据库同时有引导配置数据库，直接会写到xml中，但当前教程列出安装CAT的数据库【一个CAT集群公用一个数据库】不知道用意何在

用意思如下：
注意：一套独立的CAT集群只需要一个数据库（之前碰到过个别同学在每台cat的服务端节点都安装了一个数据库）


===关于下面的第三和第四点，请直接下载最新的master代码，插件等东西源码都已经删除，另外启动方式也不支持jetty:run，直接用标准tomcat的启动===

3.本人在windows下编译时cat-maven-plugin编译不通过，按道理应该也不影响home下war的部署吧？
4.另外使用jetty部署，报错显示没有找到数据库cat，但我确实有数据库而且xml里配置也有，我怀疑war没有读xml吗还是其他原因
