### ISSUE TITLE
按照wiki部署完后，启动首页报500错误，求解答

### ISSUE THREAD

**Issue by 839284824** [dianping/cat#1270]
27-Jun-2018 19:10:05.751 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [mvc-servlet] in web application [/cat] threw load() exception
 com.mchange.v2.resourcepool.TimeoutException: A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@1d092a8a -- timeout at awaitAvailable()
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1467)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at org.unidal.dal.jdbc.datasource.JdbcDataSource.initialize(JdbcDataSource.java:95)
	at org.unidal.dal.jdbc.datasource.DefaultDataSourceManager.getDataSource(DefaultDataSourceManager.java:36)
	at org.unidal.dal.jdbc.transaction.DefaultTransactionManager.getConnection(DefaultTransactionManager.java:97)
	at org.unidal.dal.jdbc.query.mysql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:39)
	at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:21)
	at org.unidal.dal.jdbc.engine.DefaultQueryEngine.queryMultiple(DefaultQueryEngine.java:104)
	at com.dianping.cat.core.dal.ProjectDao.findAll(ProjectDao.java:25)
	at com.dianping.cat.service.ProjectService.refresh(ProjectService.java:166)
	at com.dianping.cat.service.ProjectService.initialize(ProjectService.java:131)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88)
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(Compone

**Comment by 839284824** [comment]
不太清楚什么地方timeout了

**Comment by 839284824** [comment]
定位到问题，数据库白名单的问题
