### ISSUE TITLE
[100%复现]CAT-CLIENT 懒加载失败，导致CatFilter拦截所有HTTP请求NullPointerException

### ISSUE THREAD

**Issue by 315327017** [dianping/cat#1290]
## 1. 场景
1.1 客户端版本
```
<dependency>
         <groupId>com.dianping.cat</groupId>
         <artifactId>cat-client</artifactId>
         <version>1.4.0</version>
</dependency>
```
1.2 WEB容器 tomcat
1.3 JDK 8

## 2. 错误触发原因
client.xml为[路径]而非[文件]
![xxxxxxxxx2](https://user-images.githubusercontent.com/11953877/44262927-67a85000-a24f-11e8-89aa-17e454c266a4.png)

## 3. 错误结果
1. MessageManager初始化失败。
```
java.lang.RuntimeException: Unable to get instance of MessageManager, please make sure the environment was setup correctly!
	at com.dianping.cat.Cat.setContainer(Cat.java:337)
	at com.dianping.cat.CatClientModule.execute(CatClientModule.java:32)
	at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10)
	at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:63)
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42)
	at com.dianping.cat.Cat.initialize(Cat.java:118)
	at com.dianping.cat.Cat.initialize(Cat.java:107)
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:48)
	at com.dianping.cat.Cat.getManager(Cat.java:92)
	at com.dianping.cat.Main$1.run(Main.java:19)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.unidal.lookup.ComponentLookupException: Error when initializing component!
      role: com.dianping.cat.configuration.ClientConfigManager
  roleHint: default
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:92)
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36)
	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94)
	at org.unidal.lookup.container.MyPlexusContainer.lookup(MyPlexusContainer.java:78)
	at com.dianping.cat.Cat.setContainer(Cat.java:334)
	... 14 more
Caused by: org.unidal.lookup.extension.InitializationException: C:\data\appdatas\cat\client.xml (拒绝访问。)
	at com.dianping.cat.configuration.DefaultClientConfigManager.initialize(DefaultClientConfigManager.java:234)
	at com.dianping.cat.configuration.DefaultClientConfigManager.initialize(DefaultClientConfigManager.java:197)
	at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88)
	... 26 more
Caused by: java.io.FileNotFoundException: C:\data\appdatas\cat\client.xml (拒绝访问。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.unidal.helper.Files$IO.readFrom(Files.java:162)
	at com.dianping.cat.configuration.DefaultClientConfigManager.initialize(DefaultClientConfigManager.java:208)
	... 28 more
```
2. 日志显示懒加载成功
![xxxx1](https://user-images.githubusercontent.com/11953877/44262636-5874d280-a24e-11e8-9978-8c022c2550f2.png)

3. 被CatFilter拦截请求全部NPE，影响业务  

```  

java.lang.NullPointerException    at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:61)    at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:330)    at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:40)    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)    at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)    at java.lang.Thread.run(Thread.java:745)

```  

PS：该场景比较特殊，但因种种原因在生产环境出现。影响业务。希望CatFilter能捕获NPE，通过日志提示，不影响Servlet执行。

**Comment by youyong205** [comment]
/data/appdatas/cat/client.xml 拒绝访问。这个处理好了就行了吧。

下一个版本会把cat的相关异常全部包装起来，防止出问题
