### ISSUE TITLE
org.unidal.lookup.ComponentLookupException异常，详细内页

### ISSUE THREAD

**Issue by guoqing228** [dianping/cat#1294]
严重: Servlet.service() for servlet [LoginServlet] in context with path [/catmaidianss] threw exception [Servlet execution threw an exception] with root cause
java.lang.ClassNotFoundException: org.unidal.lookup.ComponentLookupException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1928)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1771)
	at millt.LoginServlet.doPost(LoginServlet.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1136)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by guoqing228** [comment]
补充：jdk版本1.7   cat-client版本2.0.0

**Comment by guoqing228** [comment]
@duguyixiaono1 不知道缺少什么以来，^~^。错误信息就上面那些，网上搜了好几天也没搜出来这个问题，纠结纠结

**Comment by duguyixiaono1** [comment]
我遇到过 应该是plexus-container-default的依赖不对

**Comment by guoqing228** [comment]
@duguyixiaono1  @刚试了plexus-container-default所有版本还是不行，T抱拳抱拳，我再找找其他原因

**Comment by youyong205** [comment]
Q3会发布新版本客户端，彻底解决这类plexus的问题。

你这个估计是maven环境或者版本不对

**Comment by liruizi** [comment]
请问 从官网上当下最新 CAT 进行部署的时候 报错：A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@5eefa415 -- timeout at awaitAvailable()； 这个怎么解决

**Comment by youyong205** [comment]
java客户端最新版本，请使用lib下的java客户端，这个客户端无依赖版本

**Comment by youyong205** [comment]
请问 从官网上当下最新 CAT 进行部署的时候 报错：A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@5eefa415 -- timeout at awaitAvailable()； 这个怎么解决

你这个问题是数据库连不上，这个自己好好查查为什么连不上吧。

**Comment by monkeyAlwaysWin** [comment]
这个问题是使用master分支自行构建了cat_client 3.0jar 这个版本是没有ComponentLookupException.java这些类的,所以引用后启动报错

而官方提供的cat_client 3.0 其实是低于 master分支的版本

**Comment by KevinClair** [comment]
> 这个问题是使用master分支自行构建了cat_client 3.0jar 这个版本是没有ComponentLookupException.java这些类的,所以引用后启动报错
> 
> 而官方提供的cat_client 3.0 其实是低于 master分支的版本

请问一下不是用Master分支进行构建吗？那用什么分支进行构建呢？
