### ISSUE TITLE
cat-client在非web项目中集成的相关问题

### ISSUE THREAD

**Issue by seafowlro** [dianping/cat#1299]
比如一个jar包，直接用java命令来运营jar包，却报找不到这个jar的问题。

java.lang.RuntimeException: Unable to create Plexus container!
	at org.unidal.lookup.ContainerLoader.getDefaultContainer(ContainerLoader.java:34) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.ContainerLoader.getDefaultContainer(ContainerLoader.java:18) ~[foundation-service-4.0.0.jar:?]
	at com.dianping.cat.Cat.initialize(Cat.java:103) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:46) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.getProducer(Cat.java:96) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.logMetricInternal(Cat.java:231) ~[cat-client-2.0.0.jar:?]
	at com.dianping.cat.Cat.logMetricForCount(Cat.java:179) ~[cat-client-2.0.0.jar:?]

Caused by: java.io.FileNotFoundException: /chipAccess-3.0.2.7-SNAPSHOT.one-jar.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_71]
	at java.util.zip.ZipFile.<init>(ZipFile.java:215) ~[?:1.7.0_71]
	at java.util.zip.ZipFile.<init>(ZipFile.java:145) ~[?:1.7.0_71]
	at java.util.jar.JarFile.<init>(JarFile.java:154) ~[?:1.7.0_71]
	at java.util.jar.JarFile.<init>(JarFile.java:91) ~[?:1.7.0_71]
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93) ~[?:1.7.0_71]
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69) ~[?:1.7.0_71]
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84) ~[?:1.7.0_71]
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122) ~[?:1.7.0_71]
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89) ~[?:1.7.0_71]
	at org.unidal.helper.Scanners$ResourceScanner.scan(Scanners.java:396) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.helper.Scanners$ResourceScanner.scan(Scanners.java:354) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.ComponentModelManager.scanComponents(ComponentModelManager.java:151) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.ComponentModelManager.loadComponentsFromClasspath(ComponentModelManager.java:137) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.ComponentManager.<init>(ComponentManager.java:39) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.MyPlexusContainer.<init>(MyPlexusContainer.java:23) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.container.MyPlexusContainer.<init>(MyPlexusContainer.java:19) ~[foundation-service-4.0.0.jar:?]
	at org.unidal.lookup.ContainerLoader.getDefaultContainer(ContainerLoader.java:31) ~[foundation-service-4.0.0.jar:?]

----------------------------------------------------
补充：可运行程序是用maven插件onejar-maven-plugin打包的，打包成A，将A解压之后，里面有个lib目录，这里面是依赖的包; 一个名叫main的目录，这里面才是真正的业务代码，进入之后，将业务jar包再解压缩，配置是这样的：./META-INF/app.properties。

2018-08-31更新：由于异常提示在“/”目录下缺少文件，那就复制了一份过去，但这只是临时的方案。不可能每次发布版本的时候，都将可运行程序在原有的目录和"/"目录下放置一份。
但即使这样之后，我在代码中埋点的“Transaction”，依然在网页中看不见，客户端和cat-home是有TCP链接的，心跳的数据也有，但还是没有业务上埋点的监控数据。

2018-08-31 9:47更新：若将Transaciton放在一个方法里面，就有监控数据，难道是Transaction不能跨方法？就是在一个方法里面创建对象，在另外的方法中complete()。

**Comment by youyong205** [comment]
onejar-maven-plugin 这类打包插件很多比较尴尬的，我们内部推荐的maven-assembly-plugin（2.2-beta-5或以上版本）打包方式进行打包

Q3会发布新版本客户端，彻底解决这类plexus的问题。

**Comment by youyong205** [comment]
transaction可以跨方法，不可以跨线程。。

**Comment by youyong205** [comment]
java客户端最新版本，请使用lib下的java客户端，这个客户端无依赖版本
