### ISSUE TITLE
java.lang.IllegalStateException happens while CAT running in Ubuntu

### ISSUE THREAD

**Issue by shellcompute** [dianping/cat#1308]
I installed tomcat 7 and java 8 in Ubuntu 18.04, and depolyed cat.war(downloaded from the link in README.md). But while running, a lot of errors were printed in catalina.out.
Here is a sample of the errors:
```
九月 19, 2018 11:27:35 上午 org.apache.catalina.loader.WebappClassLoaderBase loadClass
信息: Illegal access: this web application instance has been stopped already.  Could not load com.mchange.v2.c3p0.AbstractComboPooledDataSourceCustomizer.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1813)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1771)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.sun.beans.finder.ClassFinder.findClass(ClassFinder.java:103)
	at java.beans.Introspector.findCustomizerClass(Introspector.java:1301)
	at java.beans.Introspector.getTargetBeanDescriptor(Introspector.java:1295)
	at java.beans.Introspector.getBeanInfo(Introspector.java:425)
	at java.beans.Introspector.getBeanInfo(Introspector.java:262)
	at java.beans.Introspector.<init>(Introspector.java:407)
	at java.beans.Introspector.getBeanInfo(Introspector.java:262)
	at java.beans.Introspector.getBeanInfo(Introspector.java:224)
	at com.mchange.v2.beans.BeansUtils.extractAccessiblePropertiesToMap(BeansUtils.java:413)
	at com.mchange.v2.beans.BeansUtils.appendPropNamesAndValues(BeansUtils.java:388)
	at com.mchange.v2.c3p0.AbstractComboPooledDataSource.toString(AbstractComboPooledDataSource.java:750)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getPoolManager(AbstractPoolBackedDataSource.java:527)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at org.unidal.dal.jdbc.datasource.JdbcDataSource.initialize(JdbcDataSource.java:95)
	at org.unidal.dal.jdbc.datasource.DefaultDataSourceManager.getDataSource(DefaultDataSourceManager.java:36)
	at org.unidal.dal.jdbc.transaction.DefaultTransactionManager.getConnection(DefaultTransactionManager.java:97)
	at org.unidal.dal.jdbc.query.mysql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:39)
	at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:21)
	at org.unidal.dal.jdbc.engine.DefaultQueryEngine.querySingle(DefaultQueryEngine.java:114)
	at com.dianping.cat.core.config.ConfigDao.findByName(ConfigDao.java:51)
	at com.dianping.cat.config.server.ServerFilterConfigManager.refreshConfig(ServerFilterConfigManager.java:136)
	at com.dianping.cat.config.server.ServerFilterConfigManager$ConfigReloadTask.run(ServerFilterConfigManager.java:163)
	at java.lang.Thread.run(Thread.java:748)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:344)

```

I can't stop this by executing " ./tomcat7/bin/shutdown.sh ", and I have to kill 2 java processes to stop all these errors!
```
ps -ef | grep java
xxx    9101  1854 22 9月18 ?       03:25:19 java -Djava.util.logging.config.file=/.../tomcat7/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Dignore.endorsed.dirs= -classpath /.../tomcat7/bin/bootstrap.jar:/.../tomcat7/bin/tomcat-juli.jar -Dcatalina.base=/.../tomcat7 -Dcatalina.home=/.../tomcat7 -Djava.io.tmpdir=/.../tomcat7/temp org.apache.catalina.startup.Bootstrap start
xxx   14016  1854 27 11:25 pts/1    00:01:43 java -Djava.util.logging.config.file=/.../tomcat7/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Dignore.endorsed.dirs= -classpath /.../tomcat7/bin/bootstrap.jar:/.../tomcat7/bin/tomcat-juli.jar -Dcatalina.base=/.../tomcat7 -Dcatalina.home=/.../tomcat7 -Djava.io.tmpdir=/.../tomcat7/temp org.apache.catalina.startup.Bootstrap start
```

Can anybody give me some suggestions?

**Comment by shellcompute** [comment]
Versions in detail: java - 8.0.181(oracle), tomcat - 7.0.90

**Comment by qmwu2000** [comment]
I believe it’s a bug due to some non-daemon threads was not stopped whiling stopping tomcat, and prevent tomcat stopping cleanly.

I will spare some time to look into this issue, please stay in tune. Thanks!


From my iPhone
