### ISSUE TITLE
Python client 报错： undefined symbol: catClientInitWithConfig

### ISSUE THREAD

**Issue by wechasing** [dianping/cat#1340]
Python 代码：

```import cat

import time

cat.init("appkey", sampling=False, encoder=cat.ENCODER_TEXT)

with cat.Transaction("foo", "bar") as t:
    try:
        t.add_data("a=1")
        cat.log_event("hook", "before")
        # do something
    except Exception as e:
        cat.log_exception(e)
    finally:
        cat.metric("api-count").count()
        cat.metric("api-duration").duration(100)
        cat.log_event("hook", "after")

time.sleep(1)
```

运行结果：

```
(cat_monitor2) [root@VM_131_200_centos cat_test]# python test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    cat.init("appkey_alick", sampling=False, encoder=cat.ENCODER_TEXT)
  File "/root/.pyenv/versions/cat_monitor2/lib/python3.5/site-packages/pycat-3.0.0-py3.5.egg/cat/utils.py", line 39, in wraps
    return func(*args, **kwargs)
  File "/root/.pyenv/versions/cat_monitor2/lib/python3.5/site-packages/pycat-3.0.0-py3.5.egg/cat/cat.py", line 51, in init
    sdk = catSdkDefault(appkey, **kwargs)
  File "/root/.pyenv/versions/cat_monitor2/lib/python3.5/site-packages/pycat-3.0.0-py3.5.egg/cat/sdk.py", line 55, in __init__
    self.__init_ccat(**kwargs)
  File "/root/.pyenv/versions/cat_monitor2/lib/python3.5/site-packages/pycat-3.0.0-py3.5.egg/cat/sdk.py", line 65, in __init_ccat
    self.cat.catClientInitWithConfig(_(self.appkey), config)
  File "/root/.pyenv/versions/cat_monitor2/lib/python3.5/site-packages/cffi/api.py", line 882, in __getattr__
    make_accessor(name)
  File "/root/.pyenv/versions/cat_monitor2/lib/python3.5/site-packages/cffi/api.py", line 878, in make_accessor
    accessors[name](name)
  File "/root/.pyenv/versions/cat_monitor2/lib/python3.5/site-packages/cffi/api.py", line 808, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'catClientInitWithConfig' not found in library '/root/.pyenv/versions/cat_monitor2/lib/python3.5/site-packages/pycat-3.0.0-py3.5.egg/cat/lib/linux/libcatclient.so': /root/.pyenv/versions/cat_monitor2/lib/python3.5/site-packages/pycat-3.0.0-py3.5.egg/cat/lib/linux/libcatclient.so: undefined symbol: catClientInitWithConfig

```
objdump 查看了下确实没有这个方法：

```
(cat_monitor2) [root@VM_131_200_centos tmp]# objdump -tT libcatclient.so  | grep catClient
000000000001d0c1 g     F .text	0000000000000072              catClientDestroy
000000000001d07d g     F .text	0000000000000044              catClientInitWithSingleProcessModel
000000000001cecf g     F .text	00000000000001ae              catClientInit
000000000001cecf g    DF .text	00000000000001ae  Base        catClientInit
000000000001d0c1 g    DF .text	0000000000000072  Base        catClientDestroy
000000000001d07d g    DF .text	0000000000000044  Base        catClientInitWithSingleProcessModel
```
请问这个问题咋解决呀？

**Comment by chixuan777** [comment]
默认的so文件应该有问题，你要自己打个c的包
但是我自己打的c包，之后发送成功，但是cat上面没有展示
你那边试试能正常展示么

**Comment by stdrickforce** [comment]
@chixuan777 
如果使用的是旧版的 cat 服务端的话，需要在启动时增加这个参数。
```
cat.init("appkey", encoder=cat.ENCODER_TEXT)
```
Linux 的 .so 文件可能存在问题，我更新一下。

**Comment by stdrickforce** [comment]
Refer #1345
