### ISSUE TITLE
出现了NegativeArraySizeException异常

### ISSUE THREAD

**Issue by simusco** [dianping/cat#1379]
java.lang.NegativeArraySizeException at com.dianping.cat.message.storage.MessageBlockReader.readMessage(MessageBlockReader.java:39) at com.dianping.cat.message.storage.LocalMessageBucket.findByIndex(LocalMessageBucket.java:76) at com.dianping.cat.message.storage.LocalMessageBucket.findById(LocalMessageBucket.java:69) at com.dianping.cat.consumer.dump.LocalMessageBucketManager.loadMessage(LocalMessageBucketManager.java:175) at com.dianping.cat.report.page.logview.service.LocalMessageService.buildReport(LocalMessageService.java:50) at com.dianping.cat.report.service.LocalModelService.getReport(LocalModelService.java:74) at com.dianping.cat.report.page.model.Handler.handleOutbound(Handler.java:72) at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49) at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:25) at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:122) at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:194) at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:66) at org.unidal.web.MVC.service(MVC.java:97)
--

**Comment by youyong205** [comment]
可以尝试update到master最新代码
