### ISSUE TITLE
No data source(cat) defined!

### ISSUE THREAD

**Issue by adventurer2008** [dianping/cat#1391]
按照3.0.0的教程安装了多次，client.xml  datasources.xml都已配置好，mysql也已创建好，但是tomcat启动后就报个错，从提示看数据库是连接成功，那为什么还会提示No data source(cat) ？

2018-11-03 16:47:10.010 INFO  [MLog] MLog clients using slf4j logging.
2018-11-03 16:47:10.775 INFO  [[/cat]] Logger file /data/applogs/cat/cat_20181103.log
[11-03 16:47:09.009] [INFO] [cat] Cat is lazy initialized!
2018-11-03 16:47:10.114 INFO  [C3P0Registry] Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
2018-11-03 16:47:10.249 INFO  [AbstractPoolBackedDataSource] Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 1, acquireRetryDelay -> 30, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 2vsmnv9y1o53ms21ofobi0|30091b1a, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 2vsmnv9y1o53ms21ofobi0|30091b1a, idleConnectionTestPeriod -> 60, initialPoolSize -> 1, jdbcUrl -> jdbc:mysql://10.XXXX.XXX.XX:3306/cat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000, maxAdministrativeTaskTime -> 5, maxConnectionAge -> 0, maxIdleTime -> 600, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 3, maxStatements -> 0, maxStatementsPerConnection -> 1000, minPoolSize -> 1, numHelperThreads -> 6, preferredTestQuery -> SELECT 1, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]

2018-11-03 16:47:12.109 INFO  [HostConfig] Deployment of web application directory /opt/tpapp/catTomcat/webapps/cat has finished in 15,317 ms
2018-11-03 16:47:12.125 INFO  [Http11NioProtocol] Starting ProtocolHandler ["http-nio-51080"]
2018-11-03 16:47:12.129 INFO  [AjpNioProtocol] Starting ProtocolHandler ["ajp-nio-51009"]
2018-11-03 16:47:12.132 INFO  [Catalina] Server startup in 15390 ms
2018-11-03 16:47:12.632 INFO  [[/cat]] [INFO] Working directory is /opt/tpapp/catTomcat/bin
[INFO] War root is /opt/tpapp/catTomcat/webapps/cat

java.lang.RuntimeException: No data source(cat) defined!
        at org.unidal.dal.jdbc.datasource.DefaultDataSourceManager.getDataSource(DefaultDataSourceManager.java:32)
        at org.unidal.dal.jdbc.transaction.DefaultTransactionManager.getConnection(DefaultTransactionManager.java:97)
        at org.unidal.dal.jdbc.query.msyql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:40)
        at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:21)
        at org.unidal.dal.jdbc.engine.DefaultQueryEngine.queryMultiple(DefaultQueryEngine.java:104)
        at com.dianping.cat.core.dal.HostinfoDao.findAllIp(HostinfoDao.java:25)
        at com.dianping.cat.service.HostinfoService.refresh(HostinfoService.java:190)
        at com.dianping.cat.service.HostinfoService$RefreshHost.run(HostinfoService.java:240)
        at java.lang.Thread.run(Thread.java:748)
        at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
org.unidal.dal.jdbc.DalException: Error when executing query(SELECT h.id,h.ip,h.domain,h.hostname,h.creation_date,h.last_modified_date FROM hostinfo h) failed, proto: Hostinfo[creation-date: null, domain: null, hostname: null, id: 0, ip: null, key-id: 0, last-modified-date: null], message: java.lang.RuntimeException: No data source(cat) defined!.
        at org.unidal.dal.jdbc.query.msyql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:73)
        at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:21)
        at org.unidal.dal.jdbc.engine.DefaultQueryEngine.queryMultiple(DefaultQueryEngine.java:104)
        at com.dianping.cat.core.dal.HostinfoDao.findAllIp(HostinfoDao.java:25)
        at com.dianping.cat.service.HostinfoService.refresh(HostinfoService.java:190)
        at com.dianping.cat.service.HostinfoService$RefreshHost.run(HostinfoService.java:240)
        at java.lang.Thread.run(Thread.java:748)
        at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
Caused by: java.lang.RuntimeException: No data source(cat) defined!
        at org.unidal.dal.jdbc.datasource.DefaultDataSourceManager.getDataSource(DefaultDataSourceManager.java:32)
        at org.unidal.dal.jdbc.transaction.DefaultTransactionManager.getConnection(DefaultTransactionManager.java:97)
        at org.unidal.dal.jdbc.query.msyql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:40)

datasources.xml 配置如下：
<?xml version="1.0" encoding="utf-8"?>

<data-sources>
        <data-source id="cat">
                <maximum-pool-size>3</maximum-pool-size>
                <connection-timeout>1s</connection-timeout>
                <idle-timeout>10m</idle-timeout>
                <statement-cache-size>1000</statement-cache-size>
                <properties>
                        <driver>com.mysql.jdbc.Driver</driver>
                        <url><![CDATA[jdbc:mysql://10.xxx.xx.xx:3306/cat]]></url> 
                        <user>XXX</user>  
                        <password>XXX</password>  
                        <connectionProperties><![CDATA[useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000]]></connectionProperties>
                </properties>
        </data-source>

        <data-source id="app">
                <maximum-pool-size>3</maximum-pool-size>
                <connection-timeout>1s</connection-timeout>
                <idle-timeout>10m</idle-timeout>
                <statement-cache-size>1000</statement-cache-size>
                <properties>
                        <driver>com.mysql.jdbc.Driver</driver>
                        <url><![CDATA[jdbc:mysql://10.xxx.xx.xx:3306/cat]]></url>
                        <user>XXX</user>
                        <password>XXX</password>
                        <connectionProperties><![CDATA[useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000]]></connectionProperties>
                </properties>
        </data-source>
</data-sources>

**Comment by wangyapu0714** [comment]
datasources.xml中配置改成 id="cat"试下。

**Comment by adventurer2008** [comment]
配了：
<?xml version="1.0" encoding="utf-8"?>

<data-sources>
        <data-source id="cat">
                <maximum-pool-size>3</maximum-pool-size>
                <connection-timeout>1s</connection-timeout>
                <idle-timeout>10m</idle-timeout>
                <statement-cache-size>1000</statement-cache-size>
                <properties>
                        <driver>com.mysql.jdbc.Driver</driver>
                        <url><![CDATA[jdbc:mysql://10.xxx.xx.xx:3306/cat]]></url> 
                        <user>XXX</user>  
                        <password>XXX</password>  
                        <connectionProperties><![CDATA[useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000]]></connectionProperties>
                </properties>
        </data-source>

        <data-source id="app">
                <maximum-pool-size>3</maximum-pool-size>
                <connection-timeout>1s</connection-timeout>
                <idle-timeout>10m</idle-timeout>
                <statement-cache-size>1000</statement-cache-size>
                <properties>
                        <driver>com.mysql.jdbc.Driver</driver>
                        <url><![CDATA[jdbc:mysql://10.xxx.xx.xx:3306/cat]]></url>
                        <user>XXX</user>
                        <password>XXX</password>
                        <connectionProperties><![CDATA[useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000]]></connectionProperties>
                </properties>
        </data-source>
</data-sources>

**Comment by youyong205** [comment]
检查下xml是否有乱码，以及格式问题。

**Comment by adventurer2008** [comment]
xml无乱码，格式也都是正确的，从日志看，jdbc的启动日志也是正常的。

**Comment by adventurer2008** [comment]
重启tomcat后现在不报这个错误了。
Config的相关菜单都可以打开和设置，但是Application的菜单都报错：
HTTP Status 500 - Error occured when handling uri: /cat/r/t

type Status report

message Error occured when handling uri: /cat/r/t

description The server encountered an internal error that prevented it from fulfilling this request.

Cat日志显示如下：

[11-07 10:44:40.351] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-7) ...
[11-07 10:44:40.353] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/t
java.lang.RuntimeException: Error occured during handling outbound action(t)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
        at org.unidal.web.MVC.service(MVC.java:90)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:105)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
        at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(t)
        at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
        ... 42 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.transaction.Handler.handleOutbound(com.dianping.cat.report.page.transaction.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.transaction.Context@3e788682])
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:52)
        at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
        ... 44 more
Caused by: java.lang.NullPointerException
        at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:92)
        at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:34)
        at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:234)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
        ... 45 more

**Comment by wangyapu0714** [comment]
麻烦检查几个点：
1. 项目启动的contextPath是/cat吗？
2. 服务端是否在正常接收数据？
3. LocalTransactionService里buildReport可以断点看看，如果没有执行说明并没有访问到远程接口。

**Comment by adventurer2008** [comment]
找到原因了，配置链接：http://{ip:port}/cat/s/config?op=serverConfigUpdate，将remote-servers从127.0.0.1更新为实际ip+port后正常了。

**Comment by DennisJin** [comment]
> http://{ip:port}/cat/s/config?op=serverConfigUpdate

请问怎么解决的，遇到了一样的问题，配置链接 ：http://{ip:port}/cat/s/config?op=serverConfigUpdate，出错后这个地址在浏览器里也打不开啊
