### ISSUE TITLE
module 'cffi' has no attribute 'new'

### ISSUE THREAD

**Issue by flycash** [dianping/cat#1422]
在使用python3的时候，Cat在启动的时候会有异常出现：
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/zavier/git/archon/archon-client-python/tests/test_log.py", line 12, in test_log_error
    cat.init("archon-client")
  File "/Users/zavier/.virtualenvs/archon-client-python-7ZSGLXJI/lib/python3.7/site-packages/cat/utils.py", line 39, in wraps
    return func(*args, **kwargs)
  File "/Users/zavier/.virtualenvs/archon-client-python-7ZSGLXJI/lib/python3.7/site-packages/cat/cat.py", line 49, in init
    sdk = catSdkDefault(appkey, **kwargs)
  File "/Users/zavier/.virtualenvs/archon-client-python-7ZSGLXJI/lib/python3.7/site-packages/cat/sdk.py", line 63, in __init__
    self.__init_ccat(**kwargs)
  File "/Users/zavier/.virtualenvs/archon-client-python-7ZSGLXJI/lib/python3.7/site-packages/cat/sdk.py", line 73, in __init_ccat
    self.cat.catClientInitWithConfig(_(self.appkey), config)
  File "/Users/zavier/.virtualenvs/archon-client-python-7ZSGLXJI/lib/python3.7/site-packages/cat/version.py", line 34, in _
    return cffi.new("char[]", x.encode("utf-8"))
AttributeError: module 'cffi' has no attribute 'new'

cffi使用的是1.11.5. macOS, python3.7.0
异常出现的就是在version.py中，cffi本身也的确没有声明new的方法
我看到cffi里面文档都是使用cffi.FFI，如
from cffi import FFI
FFI().new(...)
不过我在python方面是一个菜鸡，所以我想确认一下，这个问题的确是应该这样被解决吧？

**Comment by stdrickforce** [comment]
能提供一下你用的 cffi 版本和 python 的版本吗？

**Comment by flycash** [comment]
cffi 使用的是版本1.11.5，python3.7.0, macOS10.14

**Comment by flycash** [comment]
我试过cffi从1.11.0-1.11.5的全部版本，都跪了
