### ISSUE TITLE
for plain text message codec  服务端报错，导致报表无法显示

### ISSUE THREAD

**Issue by majintao** [dianping/cat#1441]
cat80cat-StatusUpdateTask%springboot-template-c0a804b3-428410-6t��ڶ�,SystemStatusH��ڶ�,) for plain text message codec!
	at com.dianping.cat.message.spi.codec.PlainTextMessageCodec.decodeHeader(PlainTextMessageCodec.java:105)
	at com.dianping.cat.message.spi.codec.PlainTextMessageCodec.decode(PlainTextMessageCodec.java:72)
	at com.dianping.cat.message.spi.codec.PlainTextMessageCodec.decode(PlainTextMessageCodec.java:64)
	at com.dianping.cat.analysis.TcpSocketReceiver$MessageDecoder.decode(TcpSocketReceiver.java:143)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:268)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)

**Comment by majintao** [comment]
windows 上报到 阿里云服务器

**Comment by wangyapu0714** [comment]
你的客户端、服务端的版本是多少？

**Comment by wangyapu0714** [comment]
@majintao 应该是序列化方式不兼容导致。Java客户端近期会暴露一些兼容性的配置接口。目前可以升级3.0.0的server或者降级client版本先解决。
