### ISSUE TITLE
麻烦帮看下一下，是什么原因java.lang.ClassNotFoundException: sun.nio.ch.EPollSelectorProvider

### ISSUE THREAD

**Issue by sharemu001** [dianping/cat#1471]
麻烦帮看下一下，是什么原因：
开发环境：MAC ， java version "1.8.0_181"
启动参数：
`CATALINA_OPTS="$CATALINA_OPTS -server -Djava.awt.headless=true -Xms4G -Xmx4G -XX:PermSize=1024m -XX:MaxPermSize=2048m -XX:NewSize=1024m -XX:MaxNewSize=2048m -XX:SurvivorRatio=10 -XX:+UseParNewGC -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=13 -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:+UseCMSInitiatingOccupancyOnly -XX:+ScavengeBeforeFullGC -XX:+UseCMSCompactAtFullCollection -XX:+CMSParallelRemarkEnabled -XX:CMSFullGCsBeforeCompaction=9 -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSClassUnloadingEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:-ReduceInitialCardMarks -XX:+CMSPermGenSweepingEnabled -XX:CMSInitiatingPermOccupancyFraction=70 -XX:+ExplicitGCInvokesConcurrent -Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.EPollSelectorProvider -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config.file=/Users/sharemu/software/apache-tomcat-cat/conf/logging.properties -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationConcurrentTime -XX:+PrintHeapAtGC -Xloggc:/data/applogs/heap_trace.txt -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/applogs/HeapDumpOnOutOfMemoryError -Djava.util.Arrays.useLegacyMergeSort=true"`
启动异常：
02-Dec-2018 10:19:24.443 严重 [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector[HTTP/1.1-8080]]
 org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-8080]]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:552)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:875)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:632)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:655)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:309)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
Caused by: java.util.ServiceConfigurationError
	at java.nio.channels.spi.SelectorProvider.loadProviderFromProperty(SelectorProvider.java:97)
	at java.nio.channels.spi.SelectorProvider.access$000(SelectorProvider.java:69)
	at java.nio.channels.spi.SelectorProvider$1.run(SelectorProvider.java:171)
	at java.nio.channels.spi.SelectorProvider$1.run(SelectorProvider.java:169)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.channels.spi.SelectorProvider.provider(SelectorProvider.java:168)
	at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:108)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:216)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1087)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:265)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581)
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:68)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:993)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
	... 12 more
Caused by: java.lang.ClassNotFoundException: sun.nio.ch.EPollSelectorProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.nio.channels.spi.SelectorProvider.loadProviderFromProperty(SelectorProvider.java:92)
	... 25 more

**Comment by sharemu001** [comment]
自己解决了，谢谢。
将启动参数里的`-Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.EPollSelectorProvider` ，修改为：
`-Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.PollSelectorProvider`
MAC ， java version "1.8.0_181" 中没有，EPollSelectorProvider只有PollSelectorProvider

**Comment by wangyapu0714** [comment]
> 自己解决了，谢谢。
> 将启动参数里的`-Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.EPollSelectorProvider` ，修改为：
> `-Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.PollSelectorProvider`
> MAC ， java version "1.8.0_181" 中没有，EPollSelectorProvider只有PollSelectorProvider

👍，Linux才支持EPollSelectorProvider

**Comment by Aizen002** [comment]
如果你在 Windows 上运行 Tomcat 时遇到了类似于 java.lang.ClassNotFoundException: sun.nio.ch.EPollSelectorProvider 的错误，那么可能是因为配置文件中不小心指定了 EPollSelectorProvider，Windows 平台上并不需要像 EPollSelectorProvider 这样的 Linux 特定的 I/O 选择器提供者，所以可以直接删掉该选项
