### ISSUE TITLE
cat-client使用问题

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1520]
根据设计“最开始的Transaction 如果一直没有compelte是不会上报”，

![image](https://user-images.githubusercontent.com/19452291/50671319-15a07500-100c-11e9-9b94-bc8c41e3044d.png)

目前出现如图所示的情况，

**Comment by 578394545** [comment]
> 根据设计“最开始的Transaction 如果一直没有compelte是不会上报”，
> 
> ![image](https://user-images.githubusercontent.com/19452291/50671319-15a07500-100c-11e9-9b94-bc8c41e3044d.png)
> 
> 目前出现如图所示的情况，T1 在12月28日20:31:06 开启后未关闭，一直存在Threadlocal中，待到该线程再次被使用后，创建了T2，根据设计来说，此线程由于T1的存在且未关闭，此线程中的messageTree应该永远不会发送的，目前出现了发送的情况，而且T1先被关闭了（T1应该无法再关闭了吧？）请帮忙看一下如图出现的情况，必现，且T1永远先于T2关闭（这种情况，应该和设计是相违背的吧？）。谢谢

**Comment by xiaolei-fu** [comment]
这种我觉的没办法处理，只能在线程执行开始的Transaction必须调用complete方法，当然也可以自己封装一个线程池，在包一层 Transaction保证complete方法的调用。

**Comment by Aresyi** [comment]
一直抛这个异常
[01-07 11:04:00.700] [ERROR] [CatClientModule$CatThreadListener] Uncaught exception thrown out of thread(cat-5135)
java.lang.NoClassDefFoundError: com/dianping/cat/consumer/util/InvidStringBuilder
        at com.dianping.cat.consumer.event.EventReportCountFilter.visitType(EventReportCountFilter.java:142)
        at com.dianping.cat.consumer.event.model.transform.BaseVisitor.visitMachine(BaseVisitor.java:27)
        at com.dianping.cat.consumer.event.EventReportCountFilter.visitMachine(EventReportCountFilter.java:113)
        at com.dianping.cat.consumer.event.model.transform.BaseVisitor.visitEventReport(BaseVisitor.java:16)
        at com.dianping.cat.consumer.event.EventReportCountFilter.visitEventReport(EventReportCountFilter.java:87)
        at com.dianping.cat.consumer.event.EventAnalyzer.cleanUpReports(EventAnalyzer.java:159)
        at com.dianping.cat.consumer.event.EventAnalyzer.access$000(EventAnalyzer.java:43)
        at com.dianping.cat.consumer.event.EventAnalyzer$1.run(EventAnalyzer.java:264)
        at java.lang.Thread.run(Thread.java:748)
        at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
