### ISSUE TITLE
cat-client报错-急!-Could not initialize class io.netty.buffer.PooledUnsafeDirectByteBuf

### ISSUE THREAD

**Issue by zcc1234567** [dianping/cat#1553]
项目启动后找到了client.xml文件，并根据配置成功建链，但发送数据直接以下错误:
[01-18 15:00:43.512] [INFO] [DefaultModuleContext] Thread group(cat) created.
[01-18 15:00:43.519] [INFO] [DefaultModuleContext] Starting thread(cat-TcpSocketSender) ...
[01-18 15:00:43.523] [INFO] [DefaultModuleContext] Starting thread(cat-TcpSocketSender-ChannelManager) ...
[01-18 15:00:43.540] [INFO] [DefaultModuleContext] Starting thread(cat-StatusUpdateTask) ...
[01-18 15:00:43.540] [INFO] [DefaultModuleContext] Starting thread(cat-3) ...
[01-18 15:00:43.823] [ERROR] [TcpSocketSender] Error when sending message over TCP socket!
java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;
	at io.netty.buffer.AbstractReferenceCountedByteBuf.<clinit>(AbstractReferenceCountedByteBuf.java:32)
	at io.netty.buffer.PoolArena$DirectArena.newByteBuf(PoolArena.java:454)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:97)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:250)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:83)
	at com.dianping.cat.message.spi.codec.NativeMessageCodec.encode(NativeMessageCodec.java:109)
	at com.dianping.cat.message.io.TcpSocketSender.sendInternal(TcpSocketSender.java:285)
	at com.dianping.cat.message.io.TcpSocketSender.processNormalMessage(TcpSocketSender.java:212)
	at com.dianping.cat.message.io.TcpSocketSender.run(TcpSocketSender.java:241)
	at java.lang.Thread.run(Thread.java:748)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
[01-18 15:00:43.823] [ERROR] [TcpSocketSender] Error when sending message over TCP socket!
java.lang.NoClassDefFoundError: Could not initialize class io.netty.buffer.PooledUnsafeDirectByteBuf
	at io.netty.buffer.PoolArena$DirectArena.newByteBuf(PoolArena.java:454)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:97)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:250)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:83)
	at com.dianping.cat.message.spi.codec.NativeMessageCodec.encode(NativeMessageCodec.java:109)
	at com.dianping.cat.message.io.TcpSocketSender.sendInternal(TcpSocketSender.java:285)
	at com.dianping.cat.message.io.TcpSocketSender.processNormalMessage(TcpSocketSender.java:212)
	at com.dianping.cat.message.io.TcpSocketSender.run(TcpSocketSender.java:241)
	at java.lang.Thread.run(Thread.java:748)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)

**Comment by stenio2011** [comment]
项目中依赖的netty与cat-client需要的netty4不一致吧？

**Comment by zcc1234567** [comment]
> 项目中依赖的netty与cat-client需要的netty4不一致吧？

确实存在不一致，但本地运行可以，到服务器上就不行了。。。本地打的包和服务器上的netty相关jar包一致
