### ISSUE TITLE
node 启动文件报错

### ISSUE THREAD

**Issue by jjeejj** [dianping/cat#1555]
已经安装成功 libcatclient.so
在对应的 /usr/local/lib/ 也有 libcatclient.so 文件了，但是node 启动程序的是报错
```
module.js:682
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libcatclient.so: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/Cat-Api-GateWay/node_modules/@dp-cat/client/lib/implements/ccat.js:2:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

```

这是什么原因呢？

**Comment by youyong205** [comment]
这个好像是简单的环境编译问题吧。

**Comment by sunaiwen** [comment]
@jjeejj 你好，我遇到同样的报错，检查了一下 `libcatclient.so` 也是存在的，请问你后来找到解决办法了吗？
