### ISSUE TITLE
心跳时有异常，心跳报表看不见

### ISSUE THREAD

**Issue by Aresyi** [dianping/cat#1558]
22-Jan-2019 20:18:20.957 INFO [cat-heartbeat-task] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [META-INF/services/javax.xml.parsers.SAXParserFactory]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [META-INF/services/javax.xml.parsers.SAXParserFactory]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
  at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1305)
  at org.apache.catalina.loader.WebappClassLoaderBase.findResources(WebappClassLoaderBase.java:933)
  at java.lang.ClassLoader.getResources(ClassLoader.java:1139)
  at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
  at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
  at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
  at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)
  at java.security.AccessController.doPrivileged(Native Method)
  at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
  at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
  at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
  at com.dianping.cat.configuration.property.transform.DefaultSaxParser.parseEntity(DefaultSaxParser.java:52)
  at com.dianping.cat.configuration.property.transform.DefaultSaxParser.parse(DefaultSaxParser.java:29)
  at com.dianping.cat.configuration.property.transform.DefaultSaxParser.parse(DefaultSaxParser.java:41)
  at com.dianping.cat.configuration.DefaultClientConfigService.refreshConfig(DefaultClientConfigService.java:219)
  at com.dianping.cat.configuration.DefaultClientConfigService.refreshConfig(DefaultClientConfigService.java:186)
  at com.dianping.cat.status.StatusUpdateTask.refreshClientConfig(StatusUpdateTask.java:235)
  at com.dianping.cat.status.StatusUpdateTask.run(StatusUpdateTask.java:254)
  at java.lang.Thread.run(Thread.java:745)
  at com.dianping.cat.util.Threads$RunnableThread.run(Threads.java:300)

**Comment by wangyapu0714** [comment]
是否是client3.0的版本？更新到lib/java最新代码再试下。

**Comment by Aresyi** [comment]
> 是否是client3.0的版本？更新到lib/java最新代码再试下。

嗯 是client3.0   springboot运行

**Comment by wangyapu0714** [comment]
这个问题是之前修复过的一个问题，服务端部署的war包也是最新的吗？可以自己build最新代码部署一下看看。

**Comment by zhaojinfeng5** [comment]
最新的包，http://unidal.org/nexus/service/local/repositories/releases/content/com/dianping/cat/cat-home/3.0.0/cat-home-3.0.0.war 上下载的，报同样的错，有什么解决方案吗？

**Comment by zhaoyuguang** [comment]
我也遇到了同样的问题![image](https://user-images.githubusercontent.com/10150229/60950032-f5d66a80-a328-11e9-9921-76f5de991616.png)
