### ISSUE TITLE
3.0版本 点击application报错

### ISSUE THREAD

**Issue by wuji1mol** [dianping/cat#1562]
[01-24 18:01:59.927] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/t
java.lang.RuntimeException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1437)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
	... 43 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.transaction.Handler.handleOutbound(com.dianping.cat.report.page.transaction.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.transaction.Context@2a3a0573])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:52)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 45 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:92)
	at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:34)
	at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:234)
	at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 46 more

**Comment by 1042066103** [comment]
楼主有找到解决这个问题的方法吗
