### ISSUE TITLE
Unable to get instance of MessageManager, please make sure the environment was setup correctly报错

### ISSUE THREAD

**Issue by zcc1234567** [dianping/cat#1615]
cat-3.0.0

java.lang.RuntimeException: Error when initializing **modules!** Exception: java.lang.RuntimeException: Unable to get instance of MessageManager, please make sure the environment was setup correctly!
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:46)
	at com.dianping.cat.Cat.initialize(Cat.java:185)
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:76)
	at com.dianping.cat.Cat.getProducer(Cat.java:156)
	at com.dianping.cat.Cat.newTransaction(Cat.java:519)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.ctrip.framework.apollo.tracer.internals.cat.CatMessageProducer.newTransaction(CatMessageProducer.java:79)
	at com.ctrip.framework.apollo.tracer.Tracer.newTransaction(Tracer.java:78)
	at com.ctrip.framework.apollo.internals.ConfigServiceLocator.updateConfigServices(ConfigServiceLocator.java:151)
	at com.ctrip.framework.apollo.internals.ConfigServiceLocator.tryUpdateConfigServices(ConfigServiceLocator.java:122)
	at com.ctrip.framework.apollo.internals.ConfigServiceLocator.initConfigServices(ConfigServiceLocator.java:69)
	at com.ctrip.framework.apollo.internals.ConfigServiceLocator.<init>(ConfigServiceLocator.java:56)
	at com.ctrip.framework.apollo.internals.ConfigServiceLocator$$FastClassByGuice$$2581eb37.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at com.ctrip.framework.apollo.internals.DefaultInjector.getInstance(DefaultInjector.java:38)
	at com.ctrip.framework.apollo.build.ApolloInjector.getInstance(ApolloInjector.java:35)
	at com.ctrip.framework.apollo.internals.RemoteConfigRepository.<init>(RemoteConfigRepository.java:83)
	at com.ctrip.framework.apollo.spi.DefaultConfigFactory.createRemoteConfigRepository(DefaultConfigFactory.java:69)
	at com.ctrip.framework.apollo.spi.DefaultConfigFactory.createLocalConfigRepository(DefaultConfigFactory.java:65)
	at com.ctrip.framework.apollo.spi.DefaultConfigFactory.create(DefaultConfigFactory.java:35)
	at com.ctrip.framework.apollo.internals.DefaultConfigManager.getConfig(DefaultConfigManager.java:37)
	at com.ctrip.framework.apollo.ConfigService.getConfig(ConfigService.java:61)
	at com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer.initialize(ApolloApplicationContextInitializer.java:129)
	at com.ctrip.framework.apollo.spring.boot.ApolloApplicationContextInitializer.initialize(ApolloApplicationContextInitializer.java:85)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:611)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:348)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:143)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:89)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:62)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:73)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:336)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5352)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1410)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1400)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to get instance of MessageManager, please make sure the environment was setup correctly!
	at com.dianping.cat.Cat.setContainer(Cat.java:554)
	at com.dianping.cat.CatClientModule.execute(CatClientModule.java:55)
	at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10)
	at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:59)
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42)
	... 64 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'com.dianping.cat.message.spi.MessageManager', it could not be started.
      role: com.dianping.cat.message.spi.MessageManager
  roleHint: default
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:373)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:383)
	at com.dianping.cat.Cat.setContainer(Cat.java:551)
	... 68 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error constructing component role: 'com.dianping.cat.message.spi.MessageManager', implementation: 'com.dianping.cat.message.internal.DefaultMessageManager', role hint: 'default'
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:178)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:123)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	... 71 more
Caused by: java.lang.AbstractMethodError: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/ThreadFactory;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor;
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at com.dianping.cat.message.io.ChannelManager.<init>(ChannelManager.java:72)
	at com.dianping.cat.message.io.TcpSocketSender.initialize(TcpSocketSender.java:99)
	at com.dianping.cat.message.io.DefaultTransportManager.initialize(DefaultTransportManager.java:76)
	at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
	at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:96)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:283)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:129)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:517)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:385)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:300)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
	... 75 more
[03-08 15:13:40.040] [INFO] [cat] Cat is lazy initialized!

**Comment by youyong205** [comment]
![image](https://user-images.githubusercontent.com/1281552/54014567-23af7500-41b8-11e9-9c18-6c795bee30f2.png)

**Comment by zcc1234567** [comment]
我们在使用过程中类似问题其实挺多的，部分项目都是dubbo的里面用是netty-3.7.0，或者用了elasticsearch的包，里面的netty用的又是另一个版本，而cat本身用的是netty-4.0.24。经常遇到依赖冲突问题，这块有比较好的解决方案吗，而且经常是本地编译运行正常，通过发布打包编译后就报class not found或者no such method错误。本地和发布提供用的maven版本不同也经常导致出现问题。

**Comment by youyong205** [comment]
你看下lib下最新的java客户端，把这个问题应该是解决了。

**Comment by youyong205** [comment]
但是dubbo es版本冲突问题，最好是统一版本，公司规定都统一一个版本

**Comment by wayTofeatures** [comment]
感谢提示,解决完jar冲突,问题得到了解决
