### ISSUE TITLE
cat-home报错

### ISSUE THREAD

**Issue by panjunDev** [dianping/cat#1619]
部署cat3报错，错误信息如下：
Caused by: file:/data/application/webserver/resin/webapps/cat/WEB-INF/app.tld:81: com.caucho.jsp.cfg.TldFunction.setFunctionClass(): com.caucho.config.ConfigRuntimeException: java.lang.ClassNotFoundException: com.dianping.cat.report.page.ip.location.IPSeekerManager (in EnvironmentClassLoader[web-app:production/webapp/default/cat])

79:       <description>ip location</description>
80:       <name>getLocation</name>
81:       <function-class>com.dianping.cat.report.page.ip.location.IPSeekerManager</function-class>
82:       <function-signature>String getLocation(java.lang.String)</function-signature>
83:       <example>${a:getLocation(ip)}</example>

	at com.caucho.config.xml.XmlConfigContext.error(XmlConfigContext.java:1244)
	at com.caucho.config.xml.XmlConfigContext.configureChildNode(XmlConfigContext.java:471)
	at com.caucho.config.xml.XmlConfigContext.configureNode(XmlConfigContext.java:371)
	at com.caucho.config.xml.XmlConfigContext.configureChildBean(XmlConfigContext.java:700)
	at com.caucho.config.xml.XmlConfigContext.configureBeanProperties(XmlConfigContext.java:686)
	at com.caucho.config.xml.XmlConfigContext.configureChildNode(XmlConfigContext.java:464)
	at com.caucho.config.xml.XmlConfigContext.configureNode(XmlConfigContext.java:371)
	at com.caucho.config.xml.XmlConfigContext.configureBean(XmlConfigContext.java:285)
	at com.caucho.config.xml.XmlConfigContext.configure(XmlConfigContext.java:243)
	at com.caucho.config.Config.configure(Config.java:324)
	at com.caucho.config.Config.configure(Config.java:291)
	at com.caucho.jsp.TldManager.parseTld(TldManager.java:669)
	at com.caucho.jsp.TldManager.parseTld(TldManager.java:630)
	at com.caucho.jsp.TldManager.findTld(TldManager.java:600)
	at com.caucho.jsp.TldManager.parseTld(TldManager.java:532)
	at com.caucho.jsp.TldManager.parseTld(TldManager.java:521)
	at com.caucho.jsp.TaglibManager.readTaglib(TaglibManager.java:253)
	... 82 more
Caused by: com.caucho.config.ConfigException: com.caucho.jsp.cfg.TldFunction.setFunctionClass(): com.caucho.config.ConfigRuntimeException: java.lang.ClassNotFoundException: com.dianping.cat.report.page.ip.location.IPSeekerManager (in EnvironmentClassLoader[web-app:production/webapp/default/cat])
	at com.caucho.config.ConfigException.create(ConfigException.java:102)
	at com.caucho.config.ConfigException.create(ConfigException.java:130)
	at com.caucho.config.attribute.SetterAttribute.setText(SetterAttribute.java:135)
	at com.caucho.config.xml.XmlConfigContext.setText(XmlConfigContext.java:545)
	at com.caucho.config.xml.XmlConfigContext.configureInlineText(XmlConfigContext.java:58

**Comment by youyong205** [comment]
请在检查下部署环境下，我们发出去的war包都是没问题的，也经过测试过。

**Comment by youyong205** [comment]
建议按照流程在试一遍，也用下环境里面推荐的jdk，tomcat等各个版本
