### ISSUE TITLE
java.lang.OutOfMemoryError: Requested array size exceeds VM limit 

### ISSUE THREAD

**Issue by ishouwen** [dianping/cat#1620]
java.lang.OutOfMemoryError: Requested array size exceeds VM limit 
at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300) 
at java.lang.StringCoding.encode(StringCoding.java:344) 
at java.lang.String.getBytes(String.java:918) 
at com.dianping.cat.report.LocalReportBucket.storeById(LocalReportBucket.java:215) 
at com.dianping.cat.report.DefaultReportManager.storeFile(DefaultReportManager.java:295) 
at com.dianping.cat.report.DefaultReportManager.storeHourlyReports(DefaultReportManager.java:332) 
at com.dianping.cat.consumer.cross.CrossAnalyzer.doCheckpoint(CrossAnalyzer.java:85) 
at com.dianping.cat.analysis.PeriodTask.finish(PeriodTask.java:86) 
at com.dianping.cat.analysis.Period.finish(Period.java:137) 
at com.dianping.cat.analysis.PeriodManager.endPeriod(PeriodManager.java:66) 
at com.dianping.cat.analysis.PeriodManager.access$000(PeriodManager.java:32) 
at com.dianping.cat.analysis.PeriodManager$EndTaskThread.run(PeriodManager.java:147) 
at java.lang.Thread.run(Thread.java:745) 
at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)

**Comment by youyong205** [comment]
你这个是jvm内存太小？
