### ISSUE TITLE
docker compose 启动mysql 报错

### ISSUE THREAD

**Issue by withlin** [dianping/cat#1626]
系统:Centos7
docker版本:18.06.1-ce
docker-compose版本:1.20.1, build 5d8c71b
错误:
```
cat-mysql | Initializing database
cat-mysql | mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)
cat-mysql | 2019-03-15T01:13:23.527287Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
cat-mysql | 2019-03-15T01:13:23.530942Z 0 [ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
cat-mysql | 2019-03-15T01:13:23.530970Z 0 [ERROR] Aborting

```

**Comment by wangyapu0714** [comment]
这个上次也有童鞋反馈 mysqld: Can’t create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)，之后加的 user: "1000:50" 解决。

**Comment by withlin** [comment]
我这边确实报错了，您还是复现一下吧。上次的同学是 win或者mac平台？

**Comment by lang-CN** [comment]
系统:Centos7
docker版本:18.06.1-ce
docker-compose版本:1.20.1, build 5d8c71b
错误:
[root@localhost docker]# docker-compose up
Building cat
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1085, in up
  File "compose/cli/main.py", line 1081, in up
  File "compose/project.py", line 527, in up
  File "compose/service.py", line 360, in ensure_image_exists
  File "compose/service.py", line 1084, in build
  File "site-packages/docker/api/build.py", line 159, in build
  File "site-packages/docker/utils/build.py", line 31, in tar
  File "site-packages/docker/utils/build.py", line 79, in create_archive
  File "tarfile.py", line 1833, in gettarinfo
FileNotFoundError: [Errno 2] No such file or directory: '/proc/10/exe'
[37612] Failed to execute script docker-compose
