### ISSUE TITLE
cat error

### ISSUE THREAD

**Issue by jayslife0** [dianping/cat#1628]
[03-16 17:09:48.583] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r
java.lang.RuntimeException: Error occured during handling outbound action(top)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(top)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)

**Comment by jayslife0** [comment]
this is client.xml:

<?xml version="1.0" encoding="utf-8"?>

<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
        <servers>
                
                <server ip="127.0.0.1" port="2280" http-port="8585" />
                
                
        </servers>
</config>

**Comment by jayslife0** [comment]
<?xml version="1.0" encoding="utf-8"?>

<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
        <servers>
                
                <server ip="127.0.0.1" port="2280" http-port="8585" />
                
                
        </servers>
</config>

**Comment by jayslife0** [comment]
<?xml version="1.0" encoding="utf-8"?>

<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
        <servers>
                
                <server ip="127.0.0.1" port="2280" http-port="8585" />
                
                
        </servers>
</config>

**Comment by jayslife0** [comment]
<?xml version="1.0" encoding="utf-8"?>

<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
	<servers>
		
		<server ip="127.0.0.1" port="2280" http-port="8585" />
		
		
	</servers>
</config>

**Comment by wangyapu** [comment]
建议参考wiki文档操作一遍，应该还是环境问题。

**Comment by slankka** [comment]
IP 发生变化会遇到这个问题。

**Comment by zmy366** [comment]
用docker部署之后，访问http://localhost:8080/cat/r 也遇到了这个错误

**Comment by youyong205** [comment]
@zmy366  那现在结果呢？cat部署应该是没问题的，群里很多同学都部署没问题。
部署文档内部都迭代了很多遍。

**Comment by guxsun** [comment]
把客户端的路由改成你的内网IIP就可以了

**Comment by xiehongji** [comment]
安装有问题=。=，

**Comment by zmy366** [comment]
> @zmy366 那现在结果呢？cat部署应该是没问题的，群里很多同学都部署没问题。
> 部署文档内部都迭代了很多遍。

估计依赖下载有问题吧，开代理重新拉就好了

**Comment by Gangchao** [comment]
修改了client.xml ,server.xml 端口后出过此类问题，后面改回到8080就正常了，可能是我缓存的问题，待验证..
