### ISSUE TITLE
cat部分页面不显示数据

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1629]
发现一个情况，在查看一些数据量比较大的应用的历史模式数据时，会出现无法显示数据的情况，页面效果类似于链接所示,
[cat](http://www.unidal.org/cat/r/t?domain=cat&ip=All&date=2019031623&reportType=day&op=view)

查看日志，发现tomcat有报以下错误：
org.apache.coyote.http11.AbstractHttp11Processor process
信息: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
    at org.apache.coyote.http11.InternalAprInputBuffer.parseRequestLine(InternalAprInputBuffer.java:185)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1028)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2555)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2544)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
，请问这个使用的tomcat版本的问题吗？我用的tomcat版本是8.5.16

**Comment by wangyapu0714** [comment]
这个不太清楚，可以先降级试下。欢迎再向我们反馈。
