### ISSUE TITLE
HDFS上传模块，用几天就会报错

### ISSUE THREAD

**Issue by slankka** [dianping/cat#1644]
已经添加JVM参数：
```
-Djavax.security.auth.useSubjectCredsOnly=false
```
已知Kerberos每天定时 12个小时执行一次kinit。
但是报错
```
at org.unidal.cat.message.storage.clean.HdfsUploader.makeHdfsOutputStream(HdfsUploader.java:96) 
at org.unidal.cat.message.storage.clean.HdfsUploader.upload(HdfsUploader.java:117) 
at org.unidal.cat.message.storage.clean.HdfsUploader$Uploader.run(HdfsUploader.java:191) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: java.io.IOException: Couldn't setup connection for appuser/xx.xx.xx.xx@yyyy.xxxx.COM to xxxxx.com/xx.xx.xx.xx:8020 
at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:669) 
at java.security.AccessController.doPrivileged(Native Method) 
at javax.security.auth.Subject.doAs(Subject.java:422) 
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556) 
at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:640) 
at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:724) 
at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:367) 
at org.apache.hadoop.ipc.Client.getConnection(Client.java:1462) 
at org.apache.hadoop.ipc.Client.call(Client.java:1381) 
... 29 more 
Caused by: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))] 
at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211) 
at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:411) 
at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:550) 
at org.apache.hadoop.ipc.Client$Connection.access$1800(Client.java:367) 
at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:716) 
at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:712) 
at java.security.AccessController.doPrivileged(Native Method) 
at javax.security.auth.Subject.doAs(Subject.java:422) 
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556) 
at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:711) 
... 32 more 
Caused by: GSSException: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null)) 
at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:343) 
at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:145) 
at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122) 
at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187) 
at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224) 
at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212) 
at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179) 
at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192) 
... 41 more 
Caused by: javax.security.auth.login.LoginException: Cannot read from System.in 
at com.sun.security.auth.module.Krb5LoginModule.promptForName(Krb5LoginModule.java:865) 
at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:704) 
at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617) 
at sun.reflect.GeneratedMethodAccessor624.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498) 
at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755) 
at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195) 
at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682) 
at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680) 
at java.security.AccessController.doPrivileged(Native Method) 
at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680) 
at javax.security.auth.login.LoginContext.login(LoginContext.java:587) 
at sun.security.jgss.GSSUtil.login(GSSUtil.java:258) 
at sun.security.jgss.krb5.Krb5Util.getTicket(Krb5Util.java:158) 
at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:335) 
at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:331) 
at java.security.AccessController.doPrivileged(Native Method) 
at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:330) 
```

klist 的输出结果如下：
```

Valid starting       Expires              Service principal
03/24/2019 12:01:01  03/25/2019 12:01:01  krbtgt/yyyy.xxx.COM@xxxx.com
	renew until 03/31/2019 12:01:01
```
运行一下命令正常输出
```
 hadoop fs -ls /
```

感觉像是没有处理relogin逻辑。请问有没有解决方案

**Comment by slankka** [comment]
目前看来已解决。替换JRE的Java Unlimited Strength Crypto Policy即可。

**Comment by changjiasheng** [comment]
我也遇到了同样的问题，我配置如下：
1、JVM参数添加了-Djavax.security.auth.useSubjectCredsOnly=false
2、JDK是jdk1.8.0_131
     替换了了jdk1.8.0_131/jre/lib/security下的local_policy.jar和US_export_policy.jar
但是仍然报错，重启下JAVA应用后解决，我没有在服务器上装Kerberos的客户端

``
[06-29 09:10:55.073] [ERROR] [HdfsUploader$Uploader] Uploading file(/data/appdatas/cat/bucket/dump/20200629/07/cat-10.2.210.4.dat) to HDFS(20200629/07/cat-10.2.210.4.dat) failed!
java.io.IOException: Failed on local exception: java.io.IOException: Couldn't setup connection for hdfs-riskcontrol@CARS.COM to /10.2.211.74:8020; Host Details : local host is: "tk226-nw-e09-dx1-7/10.2.210.4"; destination host is: "risklog-nn-01.cars.com":8020;
 at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:764)
 at org.apache.hadoop.ipc.Client.call(Client.java:1414)
 at org.apache.hadoop.ipc.Client.call(Client.java:1363)
 at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
 at com.sun.proxy.$Proxy25.create(Unknown Source)
 at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:190)
 at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:103)
 at com.sun.proxy.$Proxy25.create(Unknown Source)
 at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.create(ClientNamenodeProtocolTranslatorPB.java:258)
 at org.apache.hadoop.hdfs.DFSOutputStream.newStreamForCreate(DFSOutputStream.java:1600)
 at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1465)
 at org.apache.hadoop.hdfs.DFSClient.create(DFSClient.java:1390)
 at org.apache.hadoop.hdfs.DistributedFileSystem$6.doCall(DistributedFileSystem.java:394)
 at org.apache.hadoop.hdfs.DistributedFileSystem$6.doCall(DistributedFileSystem.java:390)
 at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
 at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:390)
 at org.apache.hadoop.hdfs.DistributedFileSystem.create(DistributedFileSystem.java:334)
 at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:906)
 at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:887)
 at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:784)

at org.unidal.cat.message.storage.clean.HdfsUploader.makeHdfsOutputStream(HdfsUploader.java:96)
 at org.unidal.cat.message.storage.clean.HdfsUploader.upload(HdfsUploader.java:117)
 at org.unidal.cat.message.storage.clean.HdfsUploader$Uploader.run(HdfsUploader.java:191)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Couldn't setup connection for hdfs-riskcontrol@CARS.COM to /10.2.211.74:8020
 at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:669)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAs(Subject.java:422)
 at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
 at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:640)
 at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:724)
 at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:367)
 at org.apache.hadoop.ipc.Client.getConnection(Client.java:1462)
 at org.apache.hadoop.ipc.Client.call(Client.java:1381)
 ... 29 more
Caused by: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))]
 at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
 at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:411)
 at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:550)
 at org.apache.hadoop.ipc.Client$Connection.access$1800(Client.java:367)
 at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:716)
 at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:712)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.Subject.doAs(Subject.java:422)
 at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
 at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:711)
 ... 32 more
Caused by: GSSException: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))
 at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:343)
 at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:145)
 at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)

at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
 at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
 at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
 at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
 at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)
 ... 41 more
Caused by: javax.security.auth.login.LoginException: Cannot read from System.in
 at com.sun.security.auth.module.Krb5LoginModule.promptForName(Krb5LoginModule.java:865)
 at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:704)
 at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
 at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
 at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
 at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
 at java.security.AccessController.doPrivileged(Native Method)
 at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
 at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
 at sun.security.jgss.GSSUtil.login(GSSUtil.java:258)
 at sun.security.jgss.krb5.Krb5Util.getTicket(Krb5Util.java:158)
 at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:335)
 at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:331)
 at java.security.AccessController.doPrivileged(Native Method)
 at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:330)
 ... 48 more
``

**Comment by MikuSugar** [comment]
@slankka 你好，遇到类似的问题，能稍微详细说一下怎么替换JRE的Java Unlimited Strength Crypto Policy吗

**Comment by slankka** [comment]
@MikuSugar [WIKI-服务端部署](https://github.com/dianping/cat/wiki/readme_server#%E9%99%84%E5%BD%951-cat%E4%BD%BF%E7%94%A8hdfs%E5%AD%98%E5%82%A8logview)

**Comment by MikuSugar** [comment]
@slankka 谢谢～（因为是其它项目遇到了类似的错误，所以没想到去看这个项目的WIKI，麻烦你了。
