### ISSUE TITLE
安装node客户端node-gyp编译报错

### ISSUE THREAD

**Issue by Fnxxxxo** [dianping/cat#1687]
win: 10
msbuild: 15
node: 10.15.3
node-gyp: 3.8.0
msvs_version: 2015
错误日志如下
```
[5/5] Building fresh packages...
[-/4] ⠄ waiting...
[-/4] ⠄ waiting...
[-/4] ⠄ waiting...
error E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client
Output:
E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | win32 | x64
gyp info spawn D:\Python27\python.EXE
gyp info spawn args [ 'D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\projects\\Git\\lc\\xcrm-components\\node_modules\\@dp-cat\\client\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\palki\\.node-gyp\\10.15.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\palki\\.node-gyp\\10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\palki\\.node-gyp\\10.15.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\projects\\Git\\lc\\xcrm-components\\node_modules\\@dp-cat\\client',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\projects\\Git\\lc\\xcrm-components\\node_modules\\@dp-cat\\client\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  nodecat.cc
  win_delay_load_hook.cc
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(21): warning C4996: 'v8::String::Utf8Value::Utf8Value': 被声明为已否决 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2891): note: 参见“v8::String::Utf8Value::Utf8Value”的声明
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(60): error C2065: “u_int32_t”: 未声明的标识符 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(60): error C2146: 语法错误: 缺少“;”(在标识符“i”的前面) [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(60): error C2143: 语法错误: 缺少“;”(在“=”的前面) [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(60): error C2143: 语法错误: 缺少“)”(在“=”的前面) [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(60): error C2059: 语法错误:“=” [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(60): error C2065: “i”: 未声明的标识符 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(60): error C2059: 语法错误:“)” [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(61): error C2065: “i”: 未声明的标识符 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(61): error C2672: “v8::Local<v8::Object>::Cast”: 未找到匹配的重载函数 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(61): error C2660: “catapi::InnerSendNode”: 函数不接受 1 个参数 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(37): note: 参见“catapi::InnerSendNode”的声明
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(61): error C2059: 语法错误:“;” [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(64): error C2065: “t”: 未声明的标识符 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(42): warning C4996: 'v8::String::Utf8Value::Utf8Value': 被声明为已否决 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2891): note: 参见“v8::String::Utf8Value::Utf8Value”的声明
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(44): warning C4996: 'v8::String::Utf8Value::Utf8Value': 被声明为已否决 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2891): note: 参见“v8::String::Utf8Value::Utf8Value”的声明
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(45): warning C4996: 'v8::String::Utf8Value::Utf8Value': 被声明为已否决 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2891): note: 参见“v8::String::Utf8Value::Utf8Value”的声明
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(46): warning C4996: 'v8::String::Utf8Value::Utf8Value': 被声明为已否决 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2891): note: 参见“v8::String::Utf8Value::Utf8Value”的声明
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(47): warning C4996: 'v8::String::Utf8Value::Utf8Value': 被声明为已否决 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2891): note: 参见“v8::String::Utf8Value::Utf8Value”的声明
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(48): warning C4996: 'v8::Value::NumberValue': 被声 明为已否决 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2475): note: 参见“v8::Value::NumberValue”的声明
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(49): warning C4996: 'v8::Value::NumberValue': 被声 明为已否决 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
  c:\users\palki\.node-gyp\10.15.3\include\node\v8.h(2475): note: 参见“v8::Value::NumberValue”的声明
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(65): error C2059: 语法错误:“else” [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(65): error C2143: 语法错误: 缺少“;”(在“{”的前面) [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(65): error C2447: “{”: 缺少函数标题(是否是老式的 形式表?) [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(77): error C2059: 语法错误:“else” [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(77): error C2143: 语法错误: 缺少“;”(在“{”的前面) [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(77): error C2447: “{”: 缺少函数标题(是否是老式的 形式表?) [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(98): error C3861: “InnerSendNode”: 找不到标识符 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(102): error C2065: “Init”: 未声明的标识符 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(103): error C2065: “Destroy”: 未声明的标识符 [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(109): error C2059: 语法错误:“}” [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
e:\projects\git\lc\xcrm-components\node_modules\@dp-cat\client\src\nodecat.cc(109): error C2143: 语法错误: 缺少“;”(在“}”的前 面) [E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client\build\nodecat.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` faied with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\nod-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\projects\Git\lc\xcrm-components\node_modules\@dp-cat\client
gyp ERR! node -v v10.15.3
```

**Comment by Fnxxxxo** [comment]
尝试过vs2017，vs2015，vs2013环境，还是一样的错

**Comment by chenrulongmaster** [comment]
> 尝试过vs2017，vs2015，vs2013环境，还是一样的错

@Fnxxxxo  是不是还没解决？

**Comment by WHYSOS** [comment]
同样情况，请问最后有解决吗

**Comment by 1978625177** [comment]
问题还存在吗？

**Comment by kaiqiangh** [comment]
有类似的问题，无法安装 @dp-cat/client
