### ISSUE TITLE
源码部署报NullPointerException

### ISSUE THREAD

**Issue by nisaijie** [dianping/cat#1697]
求教：
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:92)
	at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:34)
	at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)

**Comment by koiding** [comment]
我也遇到过这个问题，我是数据库连接没配对。

**Comment by nisaijie** [comment]
重启几次，自动好了，奇葩

**Comment by xuxuanjie** [comment]
我也遇到了，难道就只能重启几次?

**Comment by wuwu955** [comment]
天呐 不会吧....那我要重启到明天吗？
