### ISSUE TITLE
cat error when startup

### ISSUE THREAD

**Issue by MaskerZheng** [dianping/cat#1706]
[05-15 10:34:09.441] [WARN] [DefaultClientConfigManager] error when connect cat server config url http://cobp-dev1:8080/cat/s/router?domain=cat&ip=10.0.1.213&op=json
[05-15 10:34:19.444] [ERROR] [HttpServlet] Error occured when handling uri: /cat/s/router
java.lang.RuntimeException: Error occured during handling outbound action(router)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
        at org.unidal.web.MVC.service(MVC.java:90)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
        at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(router)
        at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
        ... 40 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.system.page.router.Handler.handleOutbound(com.dianping.cat.system.page.router.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.system.page.router.Context@3984b7ba])
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
        at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
        ... 42 more
Caused by: java.lang.ArithmeticException: / by zero
        at com.dianping.cat.system.page.router.config.RouterConfigManager.queryServersByDomain(RouterConfigManager.java:286)
        at com.dianping.cat.system.page.router.Handler.buildRouterInfo(Handler.java:88)
        at com.dianping.cat.system.page.router.Handler.buildKvs(Handler.java:180)
        at com.dianping.cat.system.page.router.Handler.handleOutbound(Handler.java:143)
        at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
        ... 43 more

**Comment by youyong205** [comment]
这个应该是路由配置没有设置对。根据https://github.com/dianping/cat/wiki/readme_server 这个文档检查下路由配置
