### ISSUE TITLE
cat3.0 本地布署后，点application tab页报空指针异常

### ISSUE THREAD

**Issue by yingjiewish** [dianping/cat#1741]
java.lang.RuntimeException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
	... 43 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.transaction.Handler.handleOutbound(com.dianping.cat.report.page.transaction.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.transaction.Context@37711324])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:52)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 45 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:92)
	at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:34)
	at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 46 more

**Comment by youyong205** [comment]
估计服务端路由没有配置好，请对照文档在核实一遍。

**Comment by yingjiewish** [comment]
在现在布署好后，status为正常，但是查了一下2280端口，没有监听，环境是阿里云ubuntu ，jdk1.8，

**Comment by nangergong** [comment]
> 在现在布署好后，status为正常，但是查了一下2280端口，没有监听，环境是阿里云ubuntu ，jdk1.8，

怎么解决的？
