### ISSUE TITLE
MessageDecoder.decode 报错

### ISSUE THREAD

**Issue by zhengxuca** [dianping/cat#1743]
[06-20 13:22:49.365] [ERROR] [ByteToMessageDecoder] minimumReadableBytes: -2147483608 (expected: >= 0)
java.lang.IllegalArgumentException: minimumReadableBytes: -2147483608 (expected: >= 0)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1172)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:655)
	at com.dianping.cat.analysis.TcpSocketReceiver$MessageDecoder.decode(TcpSocketReceiver.java:170)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeLast(ByteToMessageDecoder.java:302)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:204)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:570)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)
[06-20 13:23:17.071] [ERROR] [ByteToMessageDecoder] Error message type : j�n
java.lang.RuntimeException: Error message type : j�n
	at com.dianping.cat.message.CodecHandler.decode(CodecHandler.java:48)
	at com.dianping.cat.analysis.TcpSocketReceiver$MessageDecoder.decode(TcpSocketReceiver.java:155)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wangyapu** [comment]
客户端使用的是哪个语言和什么版本？看上去协议都不太对。

**Comment by zhengxuca** [comment]
> 客户端使用的是哪个语言和什么版本？看上去协议都不太对。

这个服务器上/data/appdatas/cat/　cat_20190620.log　的错误。

**Comment by youyong205** [comment]
这个可能是2280端口被写入了一点其他的脏数据，理论上就是报个错，影响较小。
