### ISSUE TITLE
启动时心跳报错

### ISSUE THREAD

**Issue by zhaojinfeng5** [dianping/cat#1754]
最新的包，http://unidal.org/nexus/service/local/repositories/releases/content/com/dianping/cat/cat-home/3.0.0/cat-home-3.0.0.war 上下载的，报同样的错，有什么解决方案吗？

_Originally posted by @zhaojinfeng5 in https://github.com/dianping/cat/issues/1558#issuecomment-507560200_

**Comment by zhaojinfeng5** [comment]
02-Jul-2019 14:03:20.573 INFO [cat-heartbeat-task] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [META-INF/services/javax.xml.parsers.SAXParserFactory]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [META-INF/services/javax.xml.parsers.SAXParserFactory]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1364)
        at org.apache.catalina.loader.WebappClassLoaderBase.findResources(WebappClassLoaderBase.java:968)
        at org.apache.catalina.loader.WebappClassLoaderBase.getResources(WebappClassLoaderBase.java:1069)
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:348)
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
        at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
        at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
        at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
        at com.dianping.cat.configuration.property.transform.DefaultSaxParser.parseEntity(DefaultSaxParser.java:52)
        at com.dianping.cat.configuration.property.transform.DefaultSaxParser.parse(DefaultSaxParser.java:29)
        at com.dianping.cat.configuration.property.transform.DefaultSaxParser.parse(DefaultSaxParser.java:41)
        at com.dianping.cat.configuration.DefaultClientConfigService.refreshConfig(DefaultClientConfigService.java:219)
        at com.dianping.cat.configuration.DefaultClientConfigService.refreshConfig(DefaultClientConfigService.java:186)
        at com.dianping.cat.status.StatusUpdateTask.refreshClientConfig(StatusUpdateTask.java:235)
        at com.dianping.cat.status.StatusUpdateTask.run(StatusUpdateTask.java:254)
        at java.lang.Thread.run(Thread.java:748)
        at com.dianping.cat.util.Threads$RunnableThread.run(Threads.java:300)

**Comment by wangyapu** [comment]
@zhaojinfeng5 这个日志没什么参考意义吧？tomcat停掉之后的错误，项目可以正常启动吗？如果可以运行会报这个错吗？

**Comment by youyong205** [comment]
this web application instance has been stopped already 这个错误是tomcat stop的错误，可以google下。

**Comment by zhaojinfeng5** [comment]
> @zhaojinfeng5 这个日志没什么参考意义吧？tomcat停掉之后的错误，项目可以正常启动吗？如果可以运行会报这个错吗？

okay，可以，thanks

**Comment by zhaojinfeng5** [comment]
> this web application instance has been stopped already 这个错误是tomcat stop的错误，可以google下。

okay，thanks
