### ISSUE TITLE
Tomcat部署v3.0.0版本报错

### ISSUE THREAD

**Issue by uzdz** [dianping/cat#1760]
sh start.sh，日志抛出以下错我，访问http://127.0.0.1:8090/cat/s/config?op=routerConfigUpdate，404，请问是那个地方可能存在问题？

```error
java.util.ServiceConfigurationError
	at java.nio.channels.spi.SelectorProvider.loadProviderFromProperty(SelectorProvider.java:97)
	at java.nio.channels.spi.SelectorProvider.access$000(SelectorProvider.java:69)
	at java.nio.channels.spi.SelectorProvider$1.run(SelectorProvider.java:171)
	at java.nio.channels.spi.SelectorProvider$1.run(SelectorProvider.java:169)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.channels.spi.SelectorProvider.provider(SelectorProvider.java:168)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at com.dianping.cat.message.io.ChannelManager.<init>(ChannelManager.java:72)
	at com.dianping.cat.message.io.TcpSocketSender.initialize(TcpSocketSender.java:98)
	at com.dianping.cat.message.io.DefaultTransportManager.initialize(DefaultTransportManager.java:76)
	at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
	at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:96)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:285)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:131)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:404)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:517)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:385)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:300)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:161)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:125)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:383)
	at com.dianping.cat.Cat.setContainer(Cat.java:550)
	at com.dianping.cat.CatClientModule.execute(CatClientModule.java:55)
	at org.unidal.initialization.AbstractModule.initialize(AbstractModule.java:10)
	at org.unidal.initialization.DefaultModuleInitializer.executeModule(DefaultModuleInitializer.java:59)
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:42)
	at com.dianping.cat.Cat.initialize(Cat.java:184)
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:75)
	at com.dianping.cat.Cat.getProducer(Cat.java:155)
	at com.dianping.cat.Cat.newTransaction(Cat.java:518)
	at org.unidal.dal.jdbc.query.msyql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:33)
	at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:21)
	at org.unidal.dal.jdbc.engine.DefaultQueryEngine.querySingle(DefaultQueryEngine.java:114)
	at com.dianping.cat.core.config.ConfigDao.findByName(ConfigDao.java:51)
	at com.dianping.cat.system.page.permission.UserConfigManager.initialize(UserConfigManager.java:74)
	at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
	at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:96)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:285)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:131)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:388)
	at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:96)
	at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:90)
	at com.dianping.cat.system.page.permission.PermissionFilter.init(PermissionFilter.java:64)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4809)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5485)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: sun.nio.ch.EPollSelectorProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.nio.channels.spi.SelectorProvider.loadProviderFromProperty(SelectorProvider.java:92)
	... 74 more
```

**Comment by thanq** [comment]
找不到 EPollSelectorProvider, 很可能是你的 jdk 版本没有带EPollSelectorProvider这个类, 可以把 -Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.EPollSelectorProvider 这个启动参数去掉试试
