### ISSUE TITLE
spring boot集成cat请求NPE

### ISSUE THREAD

**Issue by haoyong** [dianping/cat#1815]
java.lang.NullPointerException: null
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:61)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:334)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:40)
debug是下面出现的，
boolean top = !Cat.getManager().hasContext();  这里Cat.getManager()是null.

怎么解决？

**Comment by haoyong** [comment]
Cat 是2.0.0版本

**Comment by jialinsun** [comment]
springboot 的filter需要自己写下intercept
