### ISSUE TITLE
当mysql版本为8.0时, 部署服务端时, 服务端启动失败

### ISSUE THREAD

**Issue by gecan123** [dianping/cat#1816]
我的mysql版本为8.0.16 MySQL Community Server - GPL
我看lib里的mysql-connector-java-5.1.20
我替换为mysql-connector-java-8.0.12重命名后, 还是不可以

错误信息如下
org.unidal.dal.jdbc.datasource.DataSourceException: Error when connecting to JDBC data source(cat) with properties xxx
...
...
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:692)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
	at org.unidal.dal.jdbc.datasource.JdbcDataSource.initialize(JdbcDataSource.java:94)
	... 182 more
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1469)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
	... 184 more

**Comment by gecan123** [comment]
Cat版本为3.0.0
tomcat版本为tomcat9

**Comment by jialinsun** [comment]
账号密码配置是不是有问题，这个看起来就是初始化链接拿不到。

**Comment by youyong205** [comment]
建议你先按照官方推荐的mysql版本来，等这个版本成功了，你在看高版本是否ok。高版本我们内部也没用。
