### ISSUE TITLE
项目打成可执行jar包含cat依赖时，启动时报Unable to get component: interface org.unidal.initialization.ModuleInitializer，不打包进jar，在同级lib目录下引用时  没问题

### ISSUE THREAD

**Issue by chenquanzhen** [dianping/cat#1837]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chenquanzhen** [comment]
java.lang.RuntimeException: Unable to get component: interface org.unidal.initialization.ModuleInitializer.
	at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:98)
	at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:90)
	at com.dianping.cat.Cat.initialize(Cat.java:183)
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:75)
	at com.dianping.cat.Cat.getProducer(Cat.java:157)
	at com.dianping.cat.Cat.newTransaction(Cat.java:520)

**Comment by qmwu2000** [comment]
各个jar中的/META-INF/plexus/components.xml文件需要合并一下。

**Comment by youyong205** [comment]
建议使用lib下java客户端，这个客户端不依赖plexus，我们做了简化处理。 官方文档也有说明。
