### ISSUE TITLE
python client 初始化运行时报错

### ISSUE THREAD

**Issue by FebruaryBird1** [dianping/cat#1865]
根据官方文档的例子我运行后报错,是我使用方法有问题吗？

t = cat.Transaction("Trans", "t3")
t.complete()

[Running] python3.7 -u "/Users/neil/Desktop/python/2.py"
cat sdk has not been initialized!
cat sdk has not been initialized!
Traceback (most recent call last):
File "/Users/neil/Desktop/python/2.py", line 22, in 
test()
File "/usr/local/lib/python3.7/site-packages/cat/transaction.py", line 107, in wraps
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/cat/transaction.py", line 99, in exit
self.complete()
File "/usr/local/lib/python3.7/site-packages/cat/transaction.py", line 46, in complete
self._trans.complete(self._trans)
AttributeError: 'NoneType' object has no attribute 'complete'

**Comment by youyong205** [comment]
python基本的环境以及语法可以在review下。

**Comment by ZyzYyy** [comment]
兄弟你解决了吗

**Comment by ZyzYyy** [comment]
pycat不支持windows 用mac或者linux核心的乌班图这种就好了
