### ISSUE TITLE
CAT导致 疯狂fugc,导致CPU使用100%

### ISSUE THREAD

**Issue by sunOnly** [dianping/cat#1882]
**Describe the bug**
CAT疯狂FUGC,导致CPU使用100%

**栈信息**
2019-11-20 20:16:36
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode):

"cat-243" #583 daemon prio=5 os_prio=0 tid=0x00007f84480b2000 nid=0x523c runnable [0x00007f8403cd0000]
   java.lang.Thread.State: RUNNABLE
	at java.util.Formatter.parse(Formatter.java:2546)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.dianping.cat.CatClientModule$CatThreadListener.onThreadStarting(CatClientModule.java:97)
	at org.unidal.helper.Threads$Manager.onThreadStarting(Threads.java:230)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:293)

   Locked ownable synchronizers:
	- None

"cat-End-Consumer-Task" #582 daemon prio=5 os_prio=0 tid=0x00007f8490068800 nid=0x5216 runnable [0x00007f8403dd1000]
   java.lang.Thread.State: RUNNABLE
	at java.util.ArrayList.iterator(ArrayList.java:840)
	at org.unidal.helper.Threads$Manager.onThreadStarting(Threads.java:228)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:293)

   Locked ownable synchronizers:
	- None

"cat-247" #581 daemon prio=5 os_prio=0 tid=0x00007f8439088800 nid=0x51fc runnable [0x00007f8403ed2000]
   java.lang.Thread.State: RUNNABLE
	at java.util.ArrayList.iterator(ArrayList.java:840)
	at org.unidal.helper.Threads$Manager.onThreadStarting(Threads.java:228)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:293)

   Locked ownable synchronizers:
	- None

"cat-246" #580 daemon prio=5 os_prio=0 tid=0x00007f8439086800 nid=0x51c3 waiting on condition [0x00007f8403fd3000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000704fb7630> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at org.unidal.lookup.logger.TimedConsoleLogger.out(TimedConsoleLogger.java:183)
	at org.unidal.lookup.logger.TimedConsoleLogger.info(TimedConsoleLogger.java:178)
	at org.codehaus.plexus.logging.AbstractLogger.info(AbstractLogger.java:72)
	at org.unidal.initialization.DefaultModuleContext.info(DefaultModuleContext.java:85)
	at com.dianping.cat.CatClientModule$CatThreadListener.onThreadStarting(CatClientModule.java:97)
	at org.unidal.helper.Threads$Manager.onThreadStarting(Threads.java:230)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:293)

   Locked ownable synchronizers:
	- None

"RMI Reaper" #16 prio=5 os_prio=0 tid=0x00007f84c855d000 nid=0x3a71 in Object.wait() [0x00007f84accf6000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000704813378> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x0000000704813378> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at sun.rmi.transport.ObjectTable$Reaper.run(ObjectTable.java:351)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"RMI TCP Accept-9280" #15 daemon prio=5 os_prio=0 tid=0x00007f84c855b000 nid=0x3a70 runnable [0x00007f84acdf7000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"RMI TCP Accept-9180" #14 daemon prio=5 os_prio=0 tid=0x00007f84c8557800 nid=0x3a6f runnable [0x00007f84acef8000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"GC Daemon" #13 daemon prio=2 os_prio=0 tid=0x00007f84c84c8800 nid=0x3a6e in Object.wait() [0x00007f84ad656000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at sun.misc.GC$Daemon.run(GC.java:117)
	- locked <0x000000070481a510> (a sun.misc.GC$LatencyLock)

   Locked ownable synchronizers:
	- None

"RMI TCP Accept-0" #12 daemon prio=5 os_prio=0 tid=0x00007f84c820e000 nid=0x3a6b runnable [0x00007f84b4304000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:52)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:405)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:377)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"AsyncFileHandlerWriter-491044090" #11 daemon prio=5 os_prio=0 tid=0x00007f84c8142800 nid=0x3a6a runnable [0x00007f84b4eca000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.juli.FileHandler.publish(FileHandler.java:262)
	at org.apache.juli.AsyncFileHandler.publishInternal(AsyncFileHandler.java:146)
	at org.apache.juli.AsyncFileHandler$LogEntry.flush(AsyncFileHandler.java:186)
	at org.apache.juli.AsyncFileHandler$LoggerThread.run(AsyncFileHandler.java:162)

   Locked ownable synchronizers:
	- None

"Service Thread" #8 daemon prio=9 os_prio=0 tid=0x00007f84c80c9800 nid=0x3a69 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f84c80be800 nid=0x3a68 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f84c80bc800 nid=0x3a67 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f84c80b9800 nid=0x3a66 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f84c80b8000 nid=0x3a65 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f84c8085000 nid=0x3a64 in Object.wait() [0x00007f84b54d0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x000000070485a6b8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:212)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f84c8080800 nid=0x3a63 in Object.wait() [0x00007f84b55d1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x000000070485bd78> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
	- None

"main" #1 prio=5 os_prio=0 tid=0x00007f84c800a800 nid=0x3a57 runnable [0x00007f84ce1c4000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at org.apache.catalina.core.StandardServer.await(StandardServer.java:466)
	at org.apache.catalina.startup.Catalina.await(Catalina.java:769)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:715)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:353)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:493)

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=0 tid=0x00007f84c8078800 nid=0x3a62 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f84c801f800 nid=0x3a5c runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f84c8021800 nid=0x3a5d runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f84c8023800 nid=0x3a5e runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f84c8025000 nid=0x3a5f runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f84c821c800 nid=0x3a6c waiting on condition 

JNI global references: 241

**GC信息**
 S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT
  0.00   0.00 100.00 100.00  97.79  94.26    506   50.459  3501 8220.752 8271.211
  0.00   0.00 100.00  99.99  97.79  94.26    506   50.459  3503 8225.395 8275.854
  0.00   0.00 100.00  99.99  97.79  94.26    506   50.459  3505 8230.022 8280.481
  0.00   0.00 100.00  99.99  97.79  94.26    506   50.459  3507 8234.546 8285.005
  0.00   0.00 100.00 100.00  97.79  94.26    506   50.459  3509 8239.095 8289.554

**堆对象直方图**
   1:      18847286     1161839232  [C
   2:      24947321      598735704  java.lang.String
   3:       4198315      201519120  com.dianping.cat.message.internal.DefaultEvent
   4:       1983800      151281288  [Ljava.lang.Object;
   5:       1903059      137020248  com.dianping.cat.message.internal.DefaultTransaction
   6:       2051738       49241712  java.util.ArrayList
   7:          2464       23405912  [B
   8:        883200       21196800  io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry
   9:          2000        3564800  [Lio.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry;
  10:         35608        3133504  com.dianping.cat.message.spi.internal.DefaultMessageTree

**Comment by sunOnly** [comment]
线上栈信息分析结果
https://gceasy.io/ft-thread-report.jsp?dumpId=1&oTxnId_value=10636682-67b0-4a6b-81f1-26ac1f2c4532#lengthyThreadsMenu

**Comment by Lovnx** [comment]
服务端的话，适当使用采样率降低压力

**Comment by youyong205** [comment]
服务端fullgc，这个一般是后端内存或者压力过大

**Comment by sunOnly** [comment]
压力确实是过大，不过后面消息停止之后FULLGC一直没停，还是不正常的。后面分析原因是内存打满，所有线程用于FULLGC了，又没线程做正常业务导致正常业务对象无法释放。形成死循环了，后面通过限制最大用于GC的线程数量可以解决这个问题
