### ISSUE TITLE
StackOverflowError-Cat 记录日志时候报堆栈溢出错误

### ISSUE THREAD

**Issue by buhuibuhuidong** [dianping/cat#1905]
这是报的错误：
```
java.lang.StackOverflowError
	at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:510)
	at com.dianping.cat.message.internal.DefaultMessageManager$TransactionHelper.migrateMessage(DefaultMessageManager.java:526)
```

这是项目中的代码：

```
public void test() {
        Transaction t = Cat.newTransaction("SQL", classMethod);
        Cat.logEvent("SQL.Statement", sql.substring(0, sql.indexOf(" ")), Message.SUCCESS, sql);

        Object obj;
        try {
            obj = invocation.proceed();
            t.setStatus(Message.SUCCESS);
        } catch (Exception e) {
            if (IS_LOG_ERROR) {
                Cat.logError(e);
            }
            throw e;
        } finally {
            t.complete();
        }
}
```

现在想确认下，如果  Cat.logEvent 这一行不在 try catch 块以内的话，Transaction 有可能报 StackOverflowError 吗？Cat 版本是 1.4.1

**Comment by wangyapu** [comment]
有可能会，如果出现异常会导致transaction t无法正常关闭。相同的函数被触发执行n次后会出现堆栈溢出。
