### ISSUE TITLE
启动home服务报错

### ISSUE THREAD

**Issue by yangzhi16888** [dianping/cat#1928]
Caused by: org.apache.xbean.recipe.ConstructionException: Composition failed of field null in object of type com.dianping.cat.message.internal.DefaultMessageManager because the requirement ComponentRequirement{role='com.dianping.cat.configuration.ClientConfigManager', roleHint='', fieldName='null'} was missing)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:413)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:517)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:385)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:300)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
	... 81 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'com.dianping.cat.configuration.ClientConfigManager', it could not be started.
      role: com.dianping.cat.configuration.ClientConfigManager
  roleHint: default
classRealm: plexus.core

**Comment by jialinsun** [comment]
按照文档做一遍呢？这样也没看出来什么线索。

**Comment by hantmac** [comment]
JDK 版本：

```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
遇到同样的问题🤔

**Comment by hantmac** [comment]
JDK 版本改为：
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
Solved.

**Comment by hantmac** [comment]
> 按照文档做一遍呢？这样也没看出来什么线索。

看下 client.xml 的格式是不是有问题
