### ISSUE TITLE
（application）应用页面无法访问。拜托了。本地

### ISSUE THREAD

**Issue by Codeprh** [dianping/cat#1929]
本地开发环境：mac os。首页能够正常访问，其他报错如下。

[01-09 08:05:46.744] [WARN] [DefaultClientConfigManager] error when connect cat server config url http://192.168.1.5:8888/cat/s/router?domain=cat&ip=192.168.1.5&op=json

[01-09 08:25:44.655] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/t
java.lang.RuntimeException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
	... 43 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.transaction.Handler.handleOutbound(com.dianping.cat.report.page.transaction.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.transaction.Context@a57b118])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 45 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:92)
	at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:34)
	at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 46 more

**Comment by Codeprh** [comment]
....无解，用2.0.0版本就行了。

**Comment by zhousiyuan0428** [comment]
Me too , 本地的话，2.0.0 就没问题
