### ISSUE TITLE
cat 告警  一直报File too large

### ISSUE THREAD

**Issue by NSBen** [dianping/cat#1972]
![image](https://user-images.githubusercontent.com/7847172/79184473-d08e0400-7e46-11ea-861b-0eeb40857322.png)
![image](https://user-images.githubusercontent.com/7847172/79184484-da176c00-7e46-11ea-8fa3-74ba449d0141.png)

E10:59:39.748 | Exception | java.io.IOException | ERROR | 172.16.65.89 java.io.IOException: File too largeat java.io.FileOutputStream.writeBytes(Native Method)at java.io.FileOutputStream.write(FileOutputStream.java:326)at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)at java.io.BufferedOutputStream.write(BufferedOutputStream.java:121)at java.io.DataOutputStream.write(DataOutputStream.java:107)at io.netty.buffer.UnpooledHeapByteBuf.getBytes(UnpooledHeapByteBuf.java:190)at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:734)at org.unidal.cat.message.storage.local.LocalBucket$DataHelper.write(LocalBucket.java:218)at org.unidal.cat.message.storage.local.LocalBucket$DataHelper.access$1200(LocalBucket.java:148)at org.unidal.cat.message.storage.local.LocalBucket.puts(LocalBucket.java:133)at org.unidal.cat.message.storage.internals.DefaultBlockWriter.processBlock(DefaultBlockWriter.java:96)at org.unidal.cat.message.storage.internals.DefaultBlockWriter.run(DefaultBlockWriter.java:120)at java.lang.Thread.run(Thread.java:748)at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
-- | -- | -- | -- | --

**Comment by NSBen** [comment]
不是很知道找你们
