### ISSUE TITLE
springboot接入cat后，启动正常，但访问接口报 java.lang.NoClassDefFoundError: DefaultMessageProducer

### ISSUE THREAD

**Issue by dengjfeng** [dianping/cat#1975]
java.lang.NoClassDefFoundError: Could not initialize class com.dianping.cat.message.internal.DefaultMessageProducer
at com.dianping.cat.Cat.initializeInternal(Cat.java:311)
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:72)
	at com.dianping.cat.Cat.getManager(Cat.java:196)
	at com.dianping.cat.servlet.CatFilter.logTransaction(CatFilter.java:234)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

**Comment by softxiang** [comment]
/data/appdatas/cat 里面的配置文件不对，或者没有配置文件

**Comment by yf718** [comment]
请问配置文件能指定路径吗？

**Comment by yf718** [comment]
> /data/appdatas/cat 里面的配置文件不对，或者没有配置文件

请问配置文件能指定路径吗？
