### ISSUE TITLE
埋点借口访问报错

### ISSUE THREAD

**Issue by admin185** [dianping/cat#2015]
java.lang.NoSuchMethodError: org.unidal.lookup.ContainerLoader.getDefaultContainer()Lorg/codehaus/plexus/PlexusContainer;
	at com.dianping.cat.Cat.initialize(Cat.java:178) ~[cat-client-3.0.0.jar:na]
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:75) ~[cat-client-3.0.0.jar:na]
	at com.dianping.cat.Cat.getProducer(Cat.java:157) ~[cat-client-3.0.0.jar:na]
	at com.dianping.cat.Cat.newTransaction(Cat.java:520) ~[cat-client-3.0.0.jar:na]

**Comment by admin185** [comment]
这个类只有一个jar包存在，怎么调用失败呢
