### ISSUE TITLE
linux环境下： Unable to get component: class com.dianping.cat.analysis.TcpSocketReceiver.

### ISSUE THREAD

**Issue by zyshengcoding** [dianping/cat#2085]
war来源：http://unidal.org/nexus/service/local/repositories/releases/content/com/dianping/cat/cat-home/3.0.0/cat-home-3.0.0.war

服务器java版本： 
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

报错信息：
错误一（路径：/data/appdatas/cat）
 [ERROR] [ChannelManager] Error when try connecting to /xx.xx.xx.xxx:2280
 Unable to get component: class com.dianping.cat.analysis.TcpSocketReceiver.
Caused by: java.lang.RuntimeException: Error when initializing modules! Exception: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.analysis.TcpSocketReceiver.
        at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:46)
        at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:24)
        at com.dianping.cat.servlet.CatServlet.initComponents(CatServlet.java:65)
        ... 17 more
Caused by: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.analysis.TcpSocketReceiver.
        at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:98)
        at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:90)
        at com.dianping.cat.CatHomeModule.setup(CatHomeModule.java:78)
        at org.unidal.initialization.DefaultModuleInitializer.expandAll(DefaultModuleInitializer.java:72)
        at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:38)
        ... 19 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'com.dianping.cat.analysis.TcpSocketReceiver', it could not be started.
      role: com.dianping.cat.analysis.TcpSocketReceiver
  roleHint: default
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

        at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:373)
        at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:388)
        at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:96)
        ... 23 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error constructing component role: 'com.dianping.cat.analysis.TcpSocketReceiver', implementation: 'com.dianping.cat.analysis.TcpSocketReceiver', role hint: 'default'
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:178)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:125)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
        at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
        at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
        ... 26 more
Caused by: org.apache.xbean.recipe.ConstructionException: Composition failed of field null in object of type com.dianping.cat.analysis.TcpSocketReceiver because the requirement ComponentRequirement{role='com.dianping.cat.analysis.MessageHandler', roleHint='', fieldName='null'} was missing)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:415)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
        at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
        at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:517)
        at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:385)
        at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:300)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:161)
        ... 30 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'com.dianping.cat.analysis.MessageHandler', it could not be started.
      role: com.dianping.cat.analysis.MessageHandler
  roleHint: default
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

错误二（tomcat的Catalina处）：java.lang.RuntimeException: Error when initializing modules! Exception: java.lang.RuntimeException: Unable to get component: class com.dianping.cat.analysis.TcpSocketReceiver

client配置：
<?xml version="1.0" encoding="utf-8"?>
<config mode="client">
    <servers>
        <server ip="xx.xx.xxx.xxx" port="2280" http-port="7071"/>
    </servers>
</config>

**Comment by zyshengcoding** [comment]
@gfreezy @seanlinwang @atell @nickevin    pls help me
