### ISSUE TITLE
你好。cat使用时server端日志报 [TcpSocketSender] Error when sending message over TCP socket! java.lang.NoClassDefFoundError: io/netty/buffer/PoolThreadCache

### ISSUE THREAD

**Issue by dionyang25** [dianping/cat#2100]
项目中cat-client包的netty和war包上的netty版本均为4.1.51.Final（一开始war包上的不一致，调整到4.1.51.Final），还是报这个错误。请教一下怎么解决

[02-20 17:01:00.534] [ERROR] [TcpSocketSender] Error when sending message over TCP socket!
java.lang.NoClassDefFoundError: io/netty/buffer/PoolThreadCache
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:458)
        at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:444)
        at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:177)
        at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:337)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
        at com.dianping.cat.message.spi.codec.NativeMessageCodec.encode(NativeMessageCodec.java:110)
        at com.dianping.cat.message.io.TcpSocketSender.sendInternal(TcpSocketSender.java:284)
        at com.dianping.cat.message.io.TcpSocketSender.processNormalMessage(TcpSocketSender.java:211)
        at com.dianping.cat.message.io.TcpSocketSender.run(TcpSocketSender.java:240)
        at java.lang.Thread.run(Thread.java:748)
        at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)

**Comment by flyingglass** [comment]
> 项目中cat-client包的netty和war包上的netty版本均为4.1.51.Final（一开始war包上的不一致，调整到4.1.51.Final），还是报这个错误。请教一下怎么解决
> 
> [02-20 17:01:00.534] [ERROR] [TcpSocketSender] Error when sending message over TCP socket!
> java.lang.NoClassDefFoundError: io/netty/buffer/PoolThreadCache
> at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:458)
> at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:444)
> at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:177)
> at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:142)
> at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:337)
> at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
> at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
> at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
> at com.dianping.cat.message.spi.codec.NativeMessageCodec.encode(NativeMessageCodec.java:110)
> at com.dianping.cat.message.io.TcpSocketSender.sendInternal(TcpSocketSender.java:284)
> at com.dianping.cat.message.io.TcpSocketSender.processNormalMessage(TcpSocketSender.java:211)
> at com.dianping.cat.message.io.TcpSocketSender.run(TcpSocketSender.java:240)
> at java.lang.Thread.run(Thread.java:748)
> at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)

cat可以repackage的

**Comment by zhisrc** [comment]
应该是你使用的 netty的版本有冲突吧。在 cat-client里面排除一下4.1.51.Final 试试
