### ISSUE TITLE
出问题CAT的服务端:[192.168.1.110]

### ISSUE THREAD

**Issue by hegphegp** [dianping/cat#2109]
![image](https://user-images.githubusercontent.com/26202719/115115496-521ef180-9fc7-11eb-85f2-4e92bd794239.png)
* 我百度和谷歌了几个小时，查看了几十上百篇博客，配置了各种参数，重启了无数次，改了无数次配置文件，还是显示 出问题CAT的服务端:[192.168.1.110]。一个链路追踪的软件，搞得比MySQL还要复杂，我现在都想放弃了，抗不住了。
* 参考博客有  https://www.freesion.com/article/589046467/
* 参考博客有  https://www.cnblogs.com/sky-chen/p/11316249.html

**Comment by hegphegp** [comment]
* 终于解决了，我给 JAVA_OPTS 配置了 -Dhost.ip=192.168.1.110 就可以了，不容易

**Comment by hegphegp** [comment]
* 脑阔疼，又冒出了一个问题，访问URL时，http的code=500，为啥会有各种问题
* 我平常开发的项目，如果出现这种问题，属于生产线上严重的bug，是不可以被接受的，整个项目团队都受影响
* http://127.0.0.1:8081/cat/r/t?domain=cat&ip=All&date=2021041723&reportType=day&op=view
![image](https://user-images.githubusercontent.com/26202719/115118116-5dc4e500-9fd4-11eb-9960-67d78d464819.png)
![image](https://user-images.githubusercontent.com/26202719/115118188-a8def800-9fd4-11eb-8889-658f57664fc2.png)
```
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.transaction.Handler.handleOutbound(com.dianping.cat.report.page.transaction.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.transaction.Context@79804ed1])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:52)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 43 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:92)
	at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:34)
	at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 44 more
[04-17 23:27:06.650] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-22) ...
[04-17 23:27:06.652] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/t
java.lang.RuntimeException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2486)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
	... 41 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.transaction.Handler.handleOutbound(com.dianping.cat.report.page.transaction.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.transaction.Context@4889752a])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:52)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 43 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:92)
	at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:34)
	at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 44 more
[04-17 23:28:00.507] [INFO] [DefaultModuleContext] Starting thread(cat-35) ...
[04-17 23:28:00.507] [INFO] [DefaultModuleContext] Starting thread(cat-36) ...
[04-17 23:28:00.507] [INFO] [DefaultModuleContext] Stopping thread(cat-35).
[04-17 23:28:00.509] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-23) ...
[04-17 23:28:00.511] [INFO] [DefaultModuleContext] Stopping thread(cat-36).

```

**Comment by hegphegp** [comment]
![image](https://user-images.githubusercontent.com/26202719/115119232-e3975f00-9fd9-11eb-8592-859f5b10468c.png)

**Comment by qmwu2000** [comment]
这是个bug，因为这个domain当前小时一直没有数据导致

发自我的iPhone

**Comment by hegphegp** [comment]
> 这是个bug，因为这个domain当前小时一直没有数据导致 发自我的iPhone
> […](#)
> 在 2021年4月18日，00:07，攻城狮 ***@***.***> 写道： ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

知道这个问题怎么解决吗？

**Comment by swabber-kun** [comment]
根本原因应该是transaction一直没收集到数据导致的？这个理论上不应该出现才对，希望解答一下疑惑

**Comment by jackie-beep** [comment]
> * 终于解决了，我给 JAVA_OPTS 配置了 -Dhost.ip=192.168.1.110 就可以了，不容易
牛🐂

**Comment by bruse-peng** [comment]
> > * 终于解决了，我给 JAVA_OPTS 配置了 -Dhost.ip=192.168.1.110 就可以了，不容易
> >   牛🐂

我也是报500，但是我加了后还是报500
