### ISSUE TITLE
本地搭建cat，transaction没有任何数据

### ISSUE THREAD

**Issue by swabber-kun** [dianping/cat#2129]
**Describe **
按官方文档搭建了单机版的cat，Dashboard显示CAT服务正常，但是没有任何的Transaction信息

**To Reproduce**

<img width="1370" alt="截屏2021-07-28 上午1 25 37" src="https://user-images.githubusercontent.com/4974393/127199886-a17fc901-257d-4d1c-89d7-6dafb0c8fec8.png">

<img width="889" alt="截屏2021-07-28 上午1 27 21" src="https://user-images.githubusercontent.com/4974393/127200107-26cc23b6-b983-415e-bfb1-1ed80eac82a6.png">

<img width="1208" alt="截屏2021-07-28 下午4 21 49" src="https://user-images.githubusercontent.com/4974393/127289402-d6b8cf8f-ec27-4fac-93a9-0a3c0e01b9dd.png">

查看了cat.log的日志报错：

`[07-28 01:28:00.627] [ERROR] [CatClientModule$CatThreadListener] Uncaught exception thrown out of thread(cat-114)
java.lang.NoClassDefFoundError: com/dianping/cat/consumer/util/InvidStringBuilder
	at com.dianping.cat.consumer.event.EventReportCountFilter.visitType(EventReportCountFilter.java:142)
	at com.dianping.cat.consumer.event.model.transform.BaseVisitor.visitMachine(BaseVisitor.java:27)
	at com.dianping.cat.consumer.event.EventReportCountFilter.visitMachine(EventReportCountFilter.java:113)
	at com.dianping.cat.consumer.event.model.transform.BaseVisitor.visitEventReport(BaseVisitor.java:16)
	at com.dianping.cat.consumer.event.EventReportCountFilter.visitEventReport(EventReportCountFilter.java:87)
	at com.dianping.cat.consumer.event.EventAnalyzer.cleanUpReports(EventAnalyzer.java:159)
	at com.dianping.cat.consumer.event.EventAnalyzer.access$000(EventAnalyzer.java:43)
	at com.dianping.cat.consumer.event.EventAnalyzer$1.run(EventAnalyzer.java:264)
	at java.lang.Thread.run(Thread.java:748)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)`

不知道这个报错是否会影响transaction的展示。我这是刚部署，没有修改任何的代码。希望可以解答一下，谢谢！

**Comment by swabber-kun** [comment]
机器重启后恢复正常，神奇
