### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by xionlylovesisi** [dianping/cat#2178]
(存储使用的hdfs)
异常堆栈:
```
java.io.FileNotFoundException: File does not exist: /user/tomcat/cat/dump/20220113/08/cat-10.55.41.187.dat.idx
at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1962)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106)
at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:73)
at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1144)
at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1132)
at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:1122)
at org.apache.hadoop.hdfs.DFSInputStream.fetchLocatedBlocksAndGetLastBlockLength(DFSInputStream.java:264)
at org.apache.hadoop.hdfs.DFSInputStream.openInfo(DFSInputStream.java:231)
at org.apache.hadoop.hdfs.DFSInputStream.<init>(DFSInputStream.java:224)
at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1295)
at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:300)
at org.apache.hadoop.hdfs.DistributedFileSystem$3.doCall(DistributedFileSystem.java:296)
at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:296)
at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:764)
at com.dianping.cat.hadoop.hdfs.MessageBlockReader.<init>(MessageBlockReader.java:39)
at com.dianping.cat.hadoop.hdfs.bucket.HdfsMessageBucket.initialize(HdfsMessageBucket.java:39)
at com.dianping.cat.hadoop.hdfs.bucket.HdfsMessageBucket.initialize(HdfsMessageBucket.java:44)
at com.dianping.cat.hadoop.hdfs.HdfsMessageBucketManager.readMessage(HdfsMessageBucketManager.java:197)
at com.dianping.cat.hadoop.hdfs.HdfsMessageBucketManager.loadMessage(HdfsMessageBucketManager.java:169)
at com.dianping.cat.report.page.logview.service.HistoricalMessageService.buildOldMessageModel(HistoricalMessageService.java:69)
at com.dianping.cat.report.page.logview.service.HistoricalMessageService.buildModel(HistoricalMessageService.java:61)
at com.dianping.cat.report.page.logview.service.HistoricalMessageService.buildModel(HistoricalMessageService.java:40)
at com.dianping.cat.report.service.BaseHistoricalModelService.invoke(BaseHistoricalModelService.java:62)
at com.dianping.cat.report.service.BaseCompositeModelService$1.run(BaseCompositeModelService.java:124)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /user/tomcat/cat/dump/20220113/08/cat-10.55.41.187.dat.idx
at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:158)
at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1962)
at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:755)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:439)
at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:528)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1070)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:999)
at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:927)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2915)

at org.apache.hadoop.ipc.Client.call(Client.java:1410)
at org.apache.hadoop.ipc.Client.call(Client.java:1363)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
at com.sun.proxy.$Proxy37.getBlockLocations(Unknown Source)
at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:219)
at sun.reflect.GeneratedMethodAccessor244.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:190)
at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:103)
at com.sun.proxy.$Proxy38.getBlockLocations(Unknown Source)
at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:1142)
... 27 more
```

该异常是在查看logview的时候发生的,从上面的报错已经能看出文件名"cat-10.55.41.187.dat.idx"是有问题的; 
主要涉及com.dianping.cat.report.page.logview.service.HistoricalMessageService的下面三个方法:
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/11381735/155456057-986ddefe-d299-453a-9e5e-38b8bdf7d442.png">

最终在初始化com.dianping.cat.hadoop.hdfs.MessageBlockReader时,文件名拼接异常
修改前
<img width="834" alt="image" src="https://user-images.githubusercontent.com/11381735/155459117-1261517a-ccab-46ae-a49a-6ff4a5b282ed.png">
修改后:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/11381735/155459204-7f77c9f3-c46d-4896-bce1-858d6f46d9a8.png">

经过这样调整之后虽然可以找到文件了,但是报了下面的异常:
```
java.lang.NegativeArraySizeException
at org.unidal.cat.message.storage.hdfs.HdfsBucket$DataHelper.read(HdfsBucket.java:149)
at org.unidal.cat.message.storage.hdfs.HdfsBucket.get(HdfsBucket.java:86)
at org.unidal.cat.message.storage.hdfs.HdfsBucketManager.readMessage(HdfsBucketManager.java:127)
at org.unidal.cat.message.storage.hdfs.HdfsBucketManager.loadMessage(HdfsBucketManager.java:87)
at com.dianping.cat.report.page.logview.service.HistoricalMessageService.buildNewMessageModel(HistoricalMessageService.java:82)
at com.dianping.cat.report.page.logview.service.HistoricalMessageService.buildModel(HistoricalMessageService.java:58)
at com.dianping.cat.report.page.logview.service.HistoricalMessageService.buildModel(HistoricalMessageService.java:40)
at com.dianping.cat.report.service.BaseHistoricalModelService.invoke(BaseHistoricalModelService.java:62)
at com.dianping.cat.report.service.BaseCompositeModelService$1.run(BaseCompositeModelService.java:124)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
```

哪位大神帮忙看下是什么原因啊?

**Comment by zhisrc** [comment]
有稳定复现的手段吗？

**Comment by zhisrc** [comment]
> 
有稳定复现的手段吗？

**Comment by xionlylovesisi** [comment]
> 

调整过MessageBlockReader的构造方法,下图标红的就是新增的代码
![image](https://user-images.githubusercontent.com/11381735/156306930-beea49b2-0d8f-4ab6-aef7-648787a9b0c7.png)
如果不调整的话只要进入HistoricalMessageService的buildOldMessageModel就会出现下面的异常:(从代码上看MessageBlockReader的这个构造方法是有问题的)
```
java.io.FileNotFoundException: File does not exist: /user/tomcat/cat/dump/20220113/08/cat-10.55.41.187.dat.idx
```

java.lang.NegativeArraySizeException这个异常是偶现的,目前还没找到复现的手段

**Comment by 1978625177** [comment]
看起来是消息错乱了，文件里对应的是一个长度，但是读出来是一个负数。如果经常出现这个问题，可能某些地方有问题

**Comment by xionlylovesisi** [comment]
关于com.dianping.cat.hadoop.hdfs.MessageBlockReader构造的时候,文件名拼接问题是否是代码问题呢?

<img width="898" alt="image" src="https://user-images.githubusercontent.com/11381735/160997382-4ddf11cf-144b-4fbd-903b-92769f343481.png">

**Comment by qmwu2000** [comment]
应该是bug

发自我的iPhone

**Comment by xionlylovesisi** [comment]
> 应该是bug 发自我的iPhone
> […](#)
> 在 2022年3月31日，15:07，charles ***@***.***> 写道： ﻿ 关于com.dianping.cat.hadoop.hdfs.MessageBlockReader构造的时候,文件名拼接问题是否是代码问题呢? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.
也不止是com.dianping.cat.hadoop.hdfs.MessageBlockReader,  com.dianping.cat.message.storage.MessageBlockReader也有同样的问题
<img width="742" alt="image" src="https://user-images.githubusercontent.com/11381735/162445252-18846d43-d28e-4779-8a0d-ab234467efd7.png">

**Comment by xionlylovesisi** [comment]
我提交了个PR #2208 , 大佬们帮忙review下
