### ISSUE TITLE
cat4.0-RC1部署后，没logview数据，点击侧栏菜单Event/Problem等500错误，NPE异常

### ISSUE THREAD

**Issue by YeLuoSC** [dianping/cat#2252]
本机环境：MAC
Tomcat 7.0
Java8
Mysql5.7

使用war包部署总是失败，使用idea跟了一下代码，发现在如下地方，有异常抛出，提示not in GZIP format
![image](https://user-images.githubusercontent.com/8948528/194842814-76733d13-db11-431e-bc81-e7c352c88fc4.png)
这个问题，会导致执行到此处时，一个npe，tomcat返回500
![image](https://user-images.githubusercontent.com/8948528/194843395-7573aa0b-6da7-41f8-a1f7-20c01f875f78.png)

我的一些配置：
![image](https://user-images.githubusercontent.com/8948528/194843561-0c194d69-2d8c-4fbb-b334-acbf65363ba1.png)

服务端配置
<?xml version="1.0" encoding="utf-8"?>
<server-config>
   <server id="default">
      <properties>
         <property name="local-mode" value="false"/>
         <property name="job-machine" value="false"/>
         <property name="send-machine" value="false"/>
         <property name="alarm-machine" value="false"/>
         <property name="hdfs-enabled" value="false"/>
         <property name="remote-servers" value="192.168.102.76:8080"/>
      </properties>
      <storage local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7" har-mode="true" upload-thread="5">
         <hdfs id="logview" max-size="128M" server-uri="hdfs://10.1.77.86/" base-dir="user/cat/logview"/>
         <hdfs id="dump" max-size="128M" server-uri="hdfs://10.1.77.86/" base-dir="user/cat/dump"/>
         <hdfs id="remote" max-size="128M" server-uri="hdfs://10.1.77.86/" base-dir="user/cat/remote"/>
      </storage>
      <consumer>
         <long-config default-url-threshold="1000" default-sql-threshold="100" default-service-threshold="50">
            <domain name="cat" url-threshold="500" sql-threshold="500"/>
            <domain name="OpenPlatformWeb" url-threshold="100" sql-threshold="500"/>
         </long-config>
      </consumer>
   </server>
   <server id="192.168.102.76">
      <properties>
         <property name="job-machine" value="true"/>
         <property name="alarm-machine" value="true"/>
         <property name="send-machine" value="true"/>
      </properties>
   </server>
</server-config>

客户端路由：
<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="192.168.102.76" backup-server-port="2280">
   <default-server id="192.168.102.76" weight="1.0" port="2280" enable="true"/>
   <network-policy id="default" title="默认" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="192.168.102.76"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="192.168.102.76" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>

完整堆栈信息：
[10-10 18:10:17.170] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/e
java.lang.RuntimeException: Error occured during handling outbound action(e)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:100)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:197)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:67)
	at org.unidal.web.MVC.service(MVC.java:76)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:105)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.support.servlet.CatFilter$Context.handle(CatFilter.java:294)
	at com.dianping.cat.support.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:142)
	at com.dianping.cat.support.servlet.CatFilter$Context.handle(CatFilter.java:292)
	at com.dianping.cat.support.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:235)
	at com.dianping.cat.support.servlet.CatFilter$Context.handle(CatFilter.java:292)
	at com.dianping.cat.support.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:125)
	at com.dianping.cat.support.servlet.CatFilter$Context.handle(CatFilter.java:292)
	at com.dianping.cat.support.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:105)
	at com.dianping.cat.support.servlet.CatFilter$Context.handle(CatFilter.java:292)
	at com.dianping.cat.support.servlet.CatFilter.doFilter(CatFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:319)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(e)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:32)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:123)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:195)
	... 41 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.event.Handler.handleOutbound(com.dianping.cat.report.page.event.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.event.Context@6118e333])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:52)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:25)
	... 43 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.event.transform.AllMachineMerger.visitEventReport(AllMachineMerger.java:49)
	at com.dianping.cat.report.page.event.transform.EventMergeHelper.mergeAllIps(EventMergeHelper.java:30)
	at com.dianping.cat.report.page.event.Handler.handleOutbound(Handler.java:222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 44 more

**Comment by YeLuoSC** [comment]
更新一下后续，Mac始终报错500，最后放弃了，在win环境做了一套；但是！！！4.0RC1这个版本在windows上，会有logview不显示的问题。最后在win上试了3.1.0版本，一切都美好了～

**Comment by qmwu2000** [comment]
最近有一个bug fix。我在mac上运行是正常的，jdk 11.0.13, mysql 8.0.27, tomcat 9.0.63。

**Comment by zhangyijun** [comment]
3.0.1版本也有这个问题

**Comment by duishancunzhang** [comment]
> 更新一下后续，Mac始终报错500，最后放弃了，在win环境做了一套；但是！！！4.0RC1这个版本在windows上，会有logview不显示的问题。最后在win上试了3.1.0版本，一切都美好了～

有没有试过在docker或者k8s上试过呢，同样版本我在windows正常（单节点ip地址都为本地局域网ip）
docker版本发现生成的dump目录下的dat文件的ip都是pod的动态ip，这块目前还没有解决，请问你有碰到类似问题吗？
