### ISSUE TITLE
搭建了，登陆界面可以出来，但是登陆后就报500

### ISSUE THREAD

**Issue by bruse-peng** [dianping/cat#2259]
java：
[root@VM-32-154-centos /data/appdatas/cat]# java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
[root@VM-32-154-centos /data/appdatas/cat]# 

tomcat:apache-tomcat-9.0.69.tar.gz 

cat的日志如下：
[11-23 18:36:31.085] [ERROR] [HttpServlet] Error occured when handling uri: /cat/s/login
java.lang.RuntimeException: Error occured during handling inbound action(login)!
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
        at org.unidal.web.MVC.service(MVC.java:90)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
        at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:82)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling inbound action(login)!
        at org.unidal.web.mvc.lifecycle.DefaultInboundActionHandler.handle(DefaultInboundActionHandler.java:88)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleInboundAction(DefaultRequestLifecycle.java:97)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:175)
        ... 40 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.system.page.login.Handler.handleInbound(com.dianping.cat.system.page.login.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.system.page.login.Context@13793bd0])
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
        at org.unidal.web.mvc.lifecycle.DefaultInboundActionHandler.handle(DefaultInboundActionHandler.java:76)
        ... 42 more
Caused by: java.lang.IllegalArgumentException: An invalid character [44] was present in the Cookie value
        at org.apache.tomcat.util.http.Rfc6265CookieProcessor.validateCookieValue(Rfc6265CookieProcessor.java:197)
        at org.apache.tomcat.util.http.Rfc6265CookieProcessor.generateHeader(Rfc6265CookieProcessor.java:123)
        at org.apache.catalina.connector.Response.generateCookieString(Response.java:1001)
        at org.apache.catalina.connector.Response.addCookie(Response.java:953)
        at org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:385)
        at com.dianping.cat.system.page.login.service.CookieManager.setCookie(CookieManager.java:55)
        at com.dianping.cat.system.page.login.service.TokenManager.setToken(TokenManager.java:53)
        at com.dianping.cat.system.page.login.service.SigninService.signin(SigninService.java:41)
        at com.dianping.cat.system.page.login.Handler.handleInbound(Handler.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
        ... 43 more
[11-23 18:37:00.823] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-48) ...
[11-23 18:37:00.825] [INFO] [DefaultModuleContext] Starting thread(cat-58) ...
[11-23 18:37:00.826] [INFO] [DefaultModuleContext] Starting thread(cat-57) ...
[11-23 18:37:00.826] [INFO] [DefaultModuleContext] Stopping thread(cat-57).
[11-23 18:37:00.848] [INFO] [DefaultModuleContext] Stopping thread(cat-58).
[11-23 18:37:00.862] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-49) ...
[11-23 18:38:00.827] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-50) ...
[11-23 18:38:00.849] [INFO] [DefaultModuleContext] Starting thread(cat-60) ...
[11-23 18:38:00.861] [INFO] [DefaultModuleContext] Starting thread(cat-59) ...
[11-23 18:38:00.866] [INFO] [DefaultModuleContext] Stopping thread(cat-60).
[11-23 18:38:00.879] [INFO] [DefaultModuleContext] Stopping thread(cat-59).
[11-23 18:38:00.894] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-51) ...
[11-23 18:39:00.999] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-52) ...
[11-23 18:39:01.002] [INFO] [DefaultModuleContext] Starting thread(cat-61) ...
[11-23 18:39:01.011] [INFO] [DefaultModuleContext] Starting thread(cat-62) ...
[11-23 18:39:01.011] [INFO] [DefaultModuleContext] Stopping thread(cat-62).
[11-23 18:39:01.017] [INFO] [DefaultModuleContext] Stopping thread(cat-61).
[11-23 18:39:01.026] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-53) ...
[11-23 18:40:01.006] [INFO] [DefaultModuleContext] Starting thread(cat-63) ...
[11-23 18:40:01.006] [INFO] [DefaultModuleContext] Stopping thread(cat-63).
[11-23 18:40:01.011] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-54) ...
[11-23 18:40:01.034] [INFO] [DefaultModuleContext] Starting thread(cat-64) ...
[11-23 18:40:01.056] [INFO] [DefaultModuleContext] Stopping thread(cat-64).
[11-23 18:40:01.085] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-55) ...
[11-23 18:40:08.418] [ERROR] [HttpServlet] Error occured when handling uri: /cat/s/login
java.lang.RuntimeException: Error occured during handling inbound action(login)!
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
        at org.unidal.web.MVC.service(MVC.java:90)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
        at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:82)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling inbound action(login)!
        at org.unidal.web.mvc.lifecycle.DefaultInboundActionHandler.handle(DefaultInboundActionHandler.java:88)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleInboundAction(DefaultRequestLifecycle.java:97)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:175)
        ... 40 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.system.page.login.Handler.handleInbound(com.dianping.cat.system.page.login.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.system.page.login.Context@201642f4])
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
        at org.unidal.web.mvc.lifecycle.DefaultInboundActionHandler.handle(DefaultInboundActionHandler.java:76)
        ... 42 more
Caused by: java.lang.IllegalArgumentException: An invalid character [44] was present in the Cookie value
        at org.apache.tomcat.util.http.Rfc6265CookieProcessor.validateCookieValue(Rfc6265CookieProcessor.java:197)
        at org.apache.tomcat.util.http.Rfc6265CookieProcessor.generateHeader(Rfc6265CookieProcessor.java:123)
        at org.apache.catalina.connector.Response.generateCookieString(Response.java:1001)
        at org.apache.catalina.connector.Response.addCookie(Response.java:953)
        at org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:385)
        at com.dianping.cat.system.page.login.service.CookieManager.setCookie(CookieManager.java:55)
        at com.dianping.cat.system.page.login.service.TokenManager.setToken(TokenManager.java:53)
        at com.dianping.cat.system.page.login.service.SigninService.signin(SigninService.java:41)
        at com.dianping.cat.system.page.login.Handler.handleInbound(Handler.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)

<img width="659" alt="image" src="https://user-images.githubusercontent.com/47881861/203526312-07125b6b-a7ef-4794-817b-721054d54726.png">

<img width="467" alt="image" src="https://user-images.githubusercontent.com/47881861/203526446-a9488943-38f1-40e0-b4ca-d3bfa9e45ee5.png">

**Comment by bruse-peng** [comment]
已经解决了，原因和大家同步下，大家没有问题主要是tomcat版本的问题，在日志/data/appdatas/cat/cat_20221124.log里面搜索关键报错“An invalid character [44] was present in the Cookie value ”找到文档https://www.lichenliang.top/tomcat-8-invalid-character-cookie-value.html，在context.xml  里面加下<CookieProcessor className="org.apache.tomcat.util.http.LegacyCookieProcessor" /> 就解决了

**Comment by phial3** [comment]
<img width="802" alt="image" src="https://github.com/dianping/cat/assets/27754514/e251d93e-45f8-444a-a557-02d60ba3a0d2">

请问楼上是怎么解决这个问题的呢，tomcat8 和 tomcat9 都是同样的问题

**Comment by phial3** [comment]
> <img alt="image" width="802" src="https://user-images.githubusercontent.com/27754514/248678053-e251d93e-45f8-444a-a557-02d60ba3a0d2.png">
> 请问楼上是怎么解决这个问题的呢，tomcat8 和 tomcat9 都是同样的问题

@bruse-peng
