### ISSUE TITLE
master 分支（c4715a6a）编译完成后无法正常启动

### ISSUE THREAD

**Issue by ityestop** [dianping/cat#2287]
**Describe the bug**
master 分支（c4715a6a） 编译后无法在 liunx centos7 中正常启用

**To Reproduce**
1.  git clone 代码，master 分支（c4715a6a）执行 mvn clean package -DskipTests
2. 进入cat-home/target ，复制cat-home.war
3. 下载 apache-tomcat-9.0.76.zip，并解压 apache-tomcat-9.0.76
4. 将 cat-home.war 复制到 apache-tomcat-9.0.76/webapps/ 目录下，并进行重命名  cat-home.war
5. 在 ~/.cat/ 下创建 datasources.xml 和 client.xml 。保证创建是没问题的
6. 运行后发现问题。apache-tomcat-9.0.76/logs/ localhost.2023-06-17.log 

在 catalina.2023-06-17.log 日志如下
```
17-Jun-2023 22:00:38.607 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
2023-06-17T14:00:38.607682128Z 17-Jun-2023 22:00:38.607 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/cat] startup failed due to previous errors
2023-06-17T14:00:38.609881753Z 17-Jun-2023 22:00:38.609 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [cat] appears to have started a thread named [Cat-ConfigureRefresher] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
2023-06-17T14:00:38.609902336Z  java.lang.Thread.sleep(Native Method)
2023-06-17T14:00:38.609906003Z  java.lang.Thread.sleep(Thread.java:342)
2023-06-17T14:00:38.609908253Z  java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
2023-06-17T14:00:38.609910378Z  com.dianping.cat.support.Threads.sleep(Threads.java:81)
2023-06-17T14:00:38.609912586Z  com.dianping.cat.configuration.DefaultConfigureManager$ConfigureRefresher.run(DefaultConfigureManager.java:275)
2023-06-17T14:00:38.609915086Z  java.lang.Thread.run(Thread.java:750)
2023-06-17T14:00:38.609938836Z  com.dianping.cat.support.Threads$RunnableThread.run(Threads.java:368)
2023-06-17T14:00:38.612400545Z 17-Jun-2023 22:00:38.612 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/cat.war] has finished in [2,428] ms
2023-06-17T14:00:38.613941753Z 
```
在 localhost.2023-06-17.log  如下
```
17-Jun-2023 22:05:00.743 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [permission-filter]
        java.lang.RuntimeException: Unable to get component: class com.dianping.cat.system.page.permission.UserConfigManager.
                at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:99)
                at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:91)
                at com.dianping.cat.system.page.permission.PermissionFilter.init(PermissionFilter.java:64)
                at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:262)
                at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:244)
                at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:97)
                at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4345)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4972)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:662)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1023)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1910)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
                at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:824)
                at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:474)
                at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1617)
                at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:318)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
                at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1328)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1318)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:923)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
        Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Error when initializing component!
      role: com.dianping.cat.system.page.permission.UserConfigManager
  roleHint: default
classRealm: none specified
                at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:236)
                at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47)
                at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103)
                at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:88)
                at org.unidal.lookup.container.MyPlexusContainer.lookup(MyPlexusContainer.java:174)
                at org.unidal.initialization.DefaultModuleContext.lookup(DefaultModuleContext.java:97)
                ... 46 more
        Caused by: java.lang.UnsatisfiedLinkError: failed to load the required native library
                at com.dianping.cat.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:81)
                at com.dianping.cat.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:56)
                at com.dianping.cat.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:186)
                at com.dianping.cat.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:37)
                at com.dianping.cat.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
                at com.dianping.cat.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
                at com.dianping.cat.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
                at com.dianping.cat.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
                at com.dianping.cat.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:114)
                at com.dianping.cat.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:101)
                at com.dianping.cat.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:78)
                at com.dianping.cat.network.ClientTransportManager.makeBootstrap(ClientTransportManager.java:87)
                at com.dianping.cat.network.ClientTransportManager.initialize(ClientTransportManager.java:64)
                at com.dianping.cat.component.DefaultComponentLifecycle.onStart(DefaultComponentLifecycle.java:33)
                at com.dianping.cat.component.DefaultComponentContext.lookup(DefaultComponentContext.java:111)
                at com.dianping.cat.component.DefaultComponentContext.lookup(DefaultComponentContext.java:55)
                at com.dianping.cat.CatBootstrap.initialize(CatBootstrap.java:157)
                at com.dianping.cat.message.context.TraceContextHelper.initialize(TraceContextHelper.java:51)
                at com.dianping.cat.message.context.TraceContextHelper.threadLocal(TraceContextHelper.java:75)
                at com.dianping.cat.Cat.newTransaction(Cat.java:320)
                at org.unidal.dal.jdbc.query.mysql.MysqlReadHandler.executeQuery(MysqlReadHandler.java:32)
                at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:21)
                at org.unidal.dal.jdbc.engine.DefaultQueryEngine.querySingle(DefaultQueryEngine.java:114)
                at com.dianping.cat.core.config.ConfigDao.findByName(ConfigDao.java:51)
                at com.dianping.cat.system.page.permission.UserConfigManager.initialize(UserConfigManager.java:74)
                at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:231)
                ... 51 more
        Caused by: java.lang.UnsatisfiedLinkError: Could not find prefix added to io.netty.util.internal.NativeLibraryLoader to get com.dianping.cat.netty.util.internal.NativeLibraryLoader. When shading, only adding a package prefix is supported
                at com.dianping.cat.netty.util.internal.NativeLibraryLoader.calculateMangledPackagePrefix(NativeLibraryLoader.java:143)
                at com.dianping.cat.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:156)
                at com.dianping.cat.netty.channel.epoll.Native.loadNativeLibrary(Native.java:323)
                at com.dianping.cat.netty.channel.epoll.Native.<clinit>(Native.java:85)
                at com.dianping.cat.netty.channel.epoll.Epoll.<clinit>(Epoll.java:40)
                ... 76 more
                Suppressed: java.lang.UnsatisfiedLinkError: Could not find prefix added to io.netty.util.internal.NativeLibraryLoader to get com.dianping.cat.netty.util.internal.NativeLibraryLoader. When shading, only adding a package prefix is supported
                        at com.dianping.cat.netty.util.internal.NativeLibraryLoader.calculateMangledPackagePrefix(NativeLibraryLoader.java:143)
                        at com.dianping.cat.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:156)
                        at com.dianping.cat.netty.channel.epoll.Native.loadNativeLibrary(Native.java:326)
                        ... 78 more
```

**Expected behavior**
正常启动后，cat会部署成功，并且可以通过路径访问，事实并非如此

**Server (please complete the following information):**
 - apache-tomcat-9.0.76
 - openjdk8
 - liunx centos7

**Comment by ityestop** [comment]
#2288

**Comment by jeremy7xu** [comment]
请问你这个问题解决了吗？ 我遇到跟你一样的问题

**Comment by qmwu2000** [comment]
拉一下最新版本
