### ISSUE TITLE
Error when initializing modules

### ISSUE THREAD

**Issue by fengxiaoxiao** [dianping/cat#254]
我想在DumpAnalyzer 里面注入一个类，报了一个异常。
我修改了 com.dianping.cat.consumer.build.ComponentsConfigurator 这个方法
    private Collection<Component> defineDumpComponents() {
        final List<Component> all = new ArrayList<Component>();
        all.add(C(MessageAnalyzer.class, DumpAnalyzer.ID, DumpAnalyzer.class).is(PER_LOOKUP) //
//增加引用            .req(MessageListContainer.class).req(ServerStatisticManager.class) //
              .req(MessageBucketManager.class, LocalMessageBucketManager.ID));
        return all;
    }
异常如下：
org.apache.xbean.recipe.MissingAccessorException: Unable to find a valid field for RequirementRecipe[fieldName=null, role=com.dianping.cat.analysis.MessageAnalyzer] in class com.dianping.cat.consumer.dump.DumpAnalyzer
    at org.apache.xbean.recipe.ReflectionUtil.findAllFieldsByType(ReflectionUtil.java:396)
    at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:390)
    at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:367)
    at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:282)
    at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)

**Comment by lining79355504** [comment]
all.add(A(
all.add(C(   啥区别 ?
