### ISSUE TITLE
启动后访问地址500，日志中有报错

### ISSUE THREAD

**Issue by dozer47528** [dianping/cat#418]
报错内容如下：

```
[07-27 12:58:48.605] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r
java.lang.RuntimeException: Error occured during creating instance of class org.unidal.web.mvc.ActionContext
        at org.unidal.lookup.util.ReflectUtils.createInstance(ReflectUtils.java:17)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.createActionContext(DefaultRequestLifecycle.java:47)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:248)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:155)
        at org.unidal.web.MVC.service(MVC.java:72)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
        at com.dianping.cat.servlet.DomainFilter.doFilter(DomainFilter.java:83)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:397)
        at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:228)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:395)
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:296)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:395)
        at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:211)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:395)
        at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:114)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:395)
        at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:53)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by greyby** [comment]
应该是 JDK 版本问题，用 JDK 8 就会报这个

**Comment by Jay-Fred** [comment]
用jdk 7同样报这个错
