### ISSUE TITLE
拉了新版本后，单机启动CAT报NullPointerException

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#738]
今天（2015-02-27）拉了github上新代码后，用TestServer.java单机启动CAT失败了：

java.lang.NullPointerException
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:102)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:53)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1115)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:361)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:417)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:320)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:534)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:864)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:533)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:207)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:403)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:522)

**Comment by huang--yijian** [comment]
我们这边cilent.xml配置有误造成了问题。不是bug。
