### ISSUE TITLE
cat-home运行报NoClassDefFoundError，是否需要自己添加依赖？

### ISSUE THREAD

**Issue by afredlyj** [dianping/cat#741]
根据文档，执行`mvn jetty:run`后，在logview中报错：

~~~~

java.lang.NoClassDefFoundError: com/mchange/v2/c3p0/ComboPooledDataSource 
at org.unidal.dal.jdbc.datasource.JdbcDataSource.initialize(JdbcDataSource.java:60) 
at org.unidal.dal.jdbc.datasource.DefaultDataSourceManager.getDataSource(DefaultDataSourceManager.java:34) 
at org.unidal.dal.jdbc.transaction.DefaultTransactionManager.getConnection(DefaultTransactionManager.java:82) 
at org.unidal.dal.jdbc.query.DefaultQueryExecutor.createPreparedStatement(DefaultQueryExecutor.java:52) 
at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeUpdate(DefaultQueryExecutor.java:140) 
at org.unidal.dal.jdbc.engine.DefaultQueryEngine.insertSingle(DefaultQueryEngine.java:100) 
at com.dianping.cat.core.dal.ProjectDao.insert(ProjectDao.java:78) 
at com.dianping.cat.service.ProjectService.insert(ProjectService.java:152) 
at com.dianping.cat.service.ProjectService.insertDomain(ProjectService.java:167) 
at com.dianping.cat.consumer.state.StateAnalyzer.process(StateAnalyzer.java:210) 
at com.dianping.cat.analysis.AbstractMessageAnalyzer.analyze(AbstractMessageAnalyzer.java:37) 
at com.dianping.cat.analysis.PeriodTask.run(PeriodTask.java:83) 
at java.lang.Thread.run(Thread.java:745) 
at org.unidal.helper.Threads$RunnableThread.run(Threads.java:292)

~~~~

程序日志也有错误：

~~~~  
[WARN] [StateAnalyzer] Error when insert domain cat info  
~~~~

**Comment by qmwu2000** [comment]
cat默认是依赖c3p0的，不需要手工加的。不过你可以在eclipse/idea中运行TestServer试试看。

**Comment by youyong205** [comment]
我感觉你应该是按照步骤来操作，其中要初始化会新建一个数据库的。
