### ISSUE TITLE
CAT启动报错是什么原因？

### ISSUE THREAD

**Issue by haqiaolong** [dianping/cat#750]
[03-07 15:35:06.325] [ERROR] [HeartbeatAnalyzer] Attribute name "PermGen" associated with an element type "extension" must be followed by the ' = ' character.
org.xml.sax.SAXParseException: Attribute name "PermGen" associated with an element type "extension" must be followed by the ' = ' character.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:174)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:388)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1411)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanAttribute(XMLDocumentFragmentScannerImpl.java:1520)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1314)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2740)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:645)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:508)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:807)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:737)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:107)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1205)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:522)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:395)
	at com.dianping.cat.status.model.transform.DefaultSaxParser.parseEntity(DefaultSaxParser.java:86)
	at com.dianping.cat.status.model.transform.DefaultSaxParser.parse(DefaultSaxParser.java:61)
	at com.dianping.cat.status.model.transform.DefaultSaxParser.parse(DefaultSaxParser.java:73)
	at com.dianping.cat.consumer.heartbeat.HeartbeatAnalyzer.buildHeartBeatInfo(HeartbeatAnalyzer.java:44)
	at com.dianping.cat.consumer.heartbeat.HeartbeatAnalyzer.processHeartbeat(HeartbeatAnalyzer.java:167)
	at com.dianping.cat.consumer.heartbeat.HeartbeatAnalyzer.processTransaction(HeartbeatAnalyzer.java:184)
	at com.dianping.cat.consumer.heartbeat.HeartbeatAnalyzer.process(HeartbeatAnalyzer.java:160)
	at com.dianping.cat.analysis.AbstractMessageAnalyzer.analyze(AbstractMessageAnalyzer.java:41)
	at com.dianping.cat.analysis.PeriodTask.run(PeriodTask.java:83)
	at java.lang.Thread.run(Thread.java:619)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:292)

**Comment by youyong205** [comment]
你可以把客户端和服务端升级到最新版本试试
