### ISSUE TITLE
接入CAT的公司方便可以在留下联系方式，公司+网址，为CAT推广出力。

### ISSUE THREAD

**Issue by youyong205** [dianping/cat#753]
大众点评+www.dianping.com

**Comment by chinaboard** [comment]
同程旅游+www.ly.com

**Comment by huang--yijian** [comment]
携程+www.ctrip.com

**Comment by jinweile** [comment]
尚品网+www.shangpin.com

**Comment by niufenjava** [comment]
中科软+www.sinosoft.com.cn

**Comment by junctioner** [comment]
能给个邮件地址，咨询几个技术问题么？baojw@whty.com.cn

**Comment by haqiaolong** [comment]
你好 我是国美在线的 准备接入CAT 
 请问 配置里的 比如 用户监控配置 应用监控配置 系统告警配置 
有没有详细使用说明？ 感谢尽快回复

**Comment by youyong205** [comment]
文档里面有一部分配置的文档，你们先参考下。

**Comment by jinweile** [comment]
你好，最近比较忙，很少看邮件，点评的兄弟给你回复了吗？如果没有，我明天有空整理一个简单的说明给你，你们用的是.net还是java？










在 2015-05-21 11:00:04，"haqiaolong" <notifications@github.com> 写道：


你好 我是国美在线的 准备接入CAT
请问 配置里的 比如 用户监控配置 应用监控配置 系统告警配置
有没有详细使用说明？ 感谢尽快回复

**Comment by emac** [comment]
微客来+www.vcooline.com

几点疑问：
1. 代码中没有任何注释，碰到问题时，很难从源码查找原因
2. Local模式默认只能查看2小时内的Transaction/Event，如何延长保留时间？（server.xml中已经申明local-report-storage-time="7" local-logivew-storage-time="7"）

**Comment by junphine** [comment]
虎扑网 www.hupu.com

**Comment by 4onni** [comment]
www.111.com.cn
医药网，先行调研一下，有没有文档地址？配置说明？

**Comment by anjingxz** [comment]
复方科技 www.fu-fang.com/

**Comment by longting** [comment]
壹捌无线  18.net

**Comment by karl7** [comment]
有cat的用户交流群吗？

**Comment by Percy0601** [comment]
CAT做的很不错，提个建议，升级依赖，升级JDK支持JDK8 Hadoop2.x。。。

**Comment by longgaoliu** [comment]
我是一名监控实施工程师，按readme搭建了环境，首页里面有些文档，但看不大明白，比如我要接入一个应用或web监控，要做那些配置，应用做那些修改等都没搞明白，有没有比较详细的文档或例子？

**Comment by wangshuai112** [comment]
有没有详细的文档？

**Comment by Percy0601** [comment]
宜信+www.creditease.cn

**Comment by GeeGee2006** [comment]
陆金所+www.lufax.com,  CAT是一个很好的应用监控工具，谢谢老吴和尤勇的努力和开源精神

**Comment by zcoson** [comment]
CAT应用监控好工具，告警怎么也用不起来。。。

**Comment by jialinsun** [comment]
告警，首先得配置告警服务端，以及配置告警规则。具体问题，请另外open issue讨论。

**Comment by liuyuzhong** [comment]
中兴软创+www.ztesoft.com 希望能提供一下植入的开发文档

**Comment by MinnieBest** [comment]
楼主能否建个交流讨论的QQ群，方便大家探讨

**Comment by MinnieBest** [comment]
楼主这两个包找不到
<dependency>
			<groupId>org.unidal.maven.plugins</groupId>
			<artifactId>common</artifactId>
			<version>2.0.3</version>
		</dependency>
		<dependency>
			<groupId>org.unidal.framework</groupId>
			<artifactId>foundation-service</artifactId>
		</dependency>

**Comment by chinaboard** [comment]
翻墙试一试



2015年8月18日 星期二 09:45 +0800 发件人 MinnieBest  <notifications@github.com>:

**Comment by renshui1983** [comment]
http://www.travelzen.com/home.html 真旅网

**Comment by happy295** [comment]
邦购网+www.banggo.com

**Comment by happy295** [comment]
邦购网 www.banggo.com

**Comment by 18721230141** [comment]
微屏科技 www.microbeam.cn    

已经搭建起来了，就是不知道怎么配置监控，能否发个配置监控的详细文档啊。  email：18721230141@163.com

**Comment by yfk** [comment]
远景能源 http://www.envisioncn.com/

**Comment by yunguangwang891017** [comment]
洋码头 http://www.ymatou.com/

**Comment by xifz** [comment]
盛付通 www.shengpay.com

**Comment by discovering** [comment]
豆子世界   www.douzi.com  

用过听云监控，想尝试使用一下cat

服务已搭建起来，就是不知怎么监控项目，web
不知有没有相关的配置，部署文档提供一下
sword1097@sina.com
感谢

**Comment by luoka** [comment]
天平派  www.tianpingpai.com
关注一段时间了，想尝试使用一下cat
可否提供一些相关（架构以及部署）文档呢？
zqm924@gmail.com
非常感谢

**Comment by livvyguo** [comment]
个人想学习一下   可否提供一下文档  livvyguo@gmail.com

**Comment by godaipl** [comment]
严东军　vobile公司
godaipl@gmail.com

最近在使用贵公司的产品，请给一些研发资料用于参考．万分感谢．

**Comment by credithc** [comment]
你好，我是北京恒昌的工程师，最近正在学习cat监控，做测试的时候发现，跨系统了消息树显示不完整。比如我在A系统某一个类里面埋点了，并调用B系统的接口，消息树可以正常显示A的消息情况，但是没有把B的消息串起来，要单独用B的domain-id才能看到。现在想在A的消息树里面把B接口里面接口的消息串起来，不知道怎么做。还请不吝赐教，谢谢了！

**Comment by tllen** [comment]
Caused by: org.apache.xbean.recipe.ConstructionException: Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.unidal.web.mvc.model.ModelManager for injection private org.unidal.web.mvc.model.ModelManager org.unidal.web.mvc.lifecycle.DefaultRequestContextBuilder.m_modelManager
        at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:472)
        at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:367)
        at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:282)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
        ... 70 more
Caused by: java.lang.RuntimeException: Duplicated name(home) found between handleInbound() and handleInbound() of class com.dianping.cat.report.ReportModule
        at org.unidal.web.mvc.model.ModelManager.buildInbound(ModelManager.java:105)
        at org.unidal.web.mvc.model.ModelManager.buildModuleFromMethods(ModelManager.java:196)
        at org.unidal.web.mvc.model.ModelManager.buildModuleFromHandlers(ModelManager.java:166)
        at org.unidal.web.mvc.model.ModelManager.buildModule(ModelManager.java:156)
        at org.unidal.web.mvc.model.ModelManager.build(ModelManager.java:79)
        at org.unidal.web.mvc.model.ModelManager.register(ModelManager.java:320)
        at org.unidal.web.mvc.model.ModelManager.initialize(ModelManager.java:303)
        at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
        at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:97)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:283)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:129)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
        at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
        at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
        at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
        at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
        at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:466)

**Comment by tllen** [comment]
启动遇到Duplicated name(home) found between handleInbound() and handleInbound() of class com.dianping.cat.report.ReportModule 错误，请问是什么问题导致的呢

**Comment by liubo1** [comment]
优艺   www.uyitv.com  demo跑起来了，配置老是出错，

**Comment by zhangzhenhuajack** [comment]
www.yaomaiche.com [要买车]

**Comment by HouZhiHouJue** [comment]
找钢网 + http://www.zhaogang.com/v 
个人参考Java客户端，修复了.net客户端的若干bug,并进行了进一步的功能补充。
不久后会把.net客户端开源出来。

**Comment by credithc** [comment]
北京恒昌+http://www.credithc.com

**Comment by HouZhiHouJue** [comment]
.NET客户端开源地址：https://github.com/HouZhiHouJue/Jasmine-CAT.NET  工业品质，稳定可靠。个人将在公司使用期间长期维护。

**Comment by 18916204759** [comment]
个人学习 了解后可能接入公司项目使用，cat home启动正常，home页的集成文档看了之后还不不懂具体接入流程，能否提供一下详细的文档，感谢！356155266@qq.com

**Comment by workwyz** [comment]
请大家加CAT群交流：522366725

**Comment by zxj19880903** [comment]
CAT应用交流群   478040828  目前有60人  都在测试接入阶段

**Comment by Donaldhan** [comment]
cat home启动正常，home页的集成文档看了，依赖包下载有问题，到您的仓库也下不下来？求解，shaoqinghanah@qq.com

**Comment by BenZhang5779** [comment]
我们是顺丰科技互联网部的运维部门，现在正在预研究服务监控这边的东西。Cat也是我们的参考的一个开源框架。但是github上的项目总是启动不起来，缺少好多包，不知能能否发一个完成的版本给我们。我的邮箱bension8708@163.com , thanks.

**Comment by zxj19880903** [comment]
请加入100人cat群   478040828

**Comment by zogwei** [comment]
阿拉互联网金融 www.51onion.com

**Comment by bfyxzls** [comment]
如何实现一台机器调用别一台机器呢，请说一下，您说的使用同一个MessageID也是不成功的
　　      Cat.GetManager().Setup();
         　string key = "BA_RMSTestJob - c0a83801 - 404552 - 7";
            Cat.GetManager().ThreadLocalMessageTree.MessageId = key;

**Comment by salever** [comment]
上海零库网-www.0ku.com

**Comment by lifuhua** [comment]
乐栈-www.lz517.com。学习中，server端搭建完成，java客户端集成不进去呀，源码导入到eclipse少程序，用maven依赖找不到库

**Comment by zcoson** [comment]
请问CAT-Client支持UDP吗

**Comment by ttkx1988** [comment]
你好，我是个人学习的，下了源码后缺了好多依赖包，不知能否完整的发一下邮箱，谢谢！

ttkx1988@sina.com

**Comment by qmwu2000** [comment]
请到mvn-repo分支下载。


发自我的 iPhone

**Comment by jianzhenchen** [comment]
周末去哪儿 -- www.wanzhoumo.com

**Comment by 517nalianpo** [comment]
www.517na.com 我都没搭建起来    进入cat-home目录：cd cat-home，运行mvn jetty:run 这个卡在中间了

**Comment by longyingan** [comment]
要跑来还是很麻烦！提示：
[WARNING] Error injecting: org.apache.maven.plugin.source.SourceJarNoForkMojo
java.lang.NoClassDefFoundError: org/codehaus/plexus/archiver/Archiver

估计很多人想使用都被挡在了编译之外了

**Comment by longyingan** [comment]
有没有谁 给个比较详细的部署文档 ，万分感谢

**Comment by sunnyhui2010** [comment]
http://unidal.org/cat/r/home?op=view&docName=index <http://unidal.org/cat/r/home?op=view&docName=index>

**Comment by ByronRen** [comment]
I have a question: Does it support JDK8 now? If not,what changes should i make to support JDK8.

**Comment by kala55** [comment]
达飞金融控股有限公司  www.dafyjk.com

**Comment by wuqingming** [comment]
你好，我是keep电商部门的，我们部门准备考虑用cat做监控，使用cat发现样例比较欠缺，看很多资料也只是一些文字描述，不知可否提供一些常用的样例代码（如跨系统服务调用链）

**Comment by qmwu2000** [comment]
我们有一个微信群，你可以先加我微信（qmwu2000），注明是cat用户，我把你拉入群。


发自我的 iPhone

**Comment by yxuqtr** [comment]
大神， 有QQ交流群吗? 文档太少了啊

**Comment by yxuqtr** [comment]
安装报错：
HTTP ERROR 503

Problem accessing /cat/r. Reason:

    org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------
Caused by:

javax.servlet.UnavailableException: org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

**Comment by qmwu2000** [comment]
有微信群，请加我微信：qmwu2000

发自我的 iPhone

**Comment by islin** [comment]
钱庄网[www.qian360.com](url)

**Comment by robin0695** [comment]
陆金所，想问下载配置里如何添加应用监控，看到sample是一个xml 但是具体配置的意义哪里能看到解释。谢谢了！

**Comment by topCoderzhangshuo** [comment]
Plugin execution not covered by lifecycle configuration: org.unidal.maven.plugins:plexus-maven-plugin:

为什么在eclipse引入大量报错呢？？比如：
Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.unidal.maven.plugins:plexus-maven-plugin:2.2.0:plexus (execution: generate plexus component descriptor, phase: process-classes)	pom.xml	/cat-client	line 67	Maven Project Build Lifecycle Mapping Problem


Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.unidal.maven.plugins:codegen-maven-plugin:2.3.2:dal-model (execution: generate report models, phase: generate-sources)	pom.xml	/cat-consumer	line 44	Maven Project Build Lifecycle Mapping Problem

**Comment by qmwu2000** [comment]
这是m2eclipse的bug，参见：https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html。

请在命令行在build，然后以普通文件方式倒入。

**Comment by topCoderzhangshuo** [comment]
```/data/appdatas/cat/client.xml```

   ```src\main\resources\META-INF\app.properties``` 

   ```src\main\resources\META-INF\cat\client.xml```


明明一个地方可以配置完，为什么要搞这么多配置文件呢？？比如我集成到业务系统A，那我只要在...src\main\resources\META-INF\cat\client.xml里把 client相关的属性全部配置完不就好了吗？为什么要搞三个。

请大神指点一下。。谢谢

我们公司，正在考虑引入分布式跟踪链的监控，正在技术选型预研。

**Comment by topCoderzhangshuo** [comment]
Transaction 类型里有个URL与URL.Forward
对应的源码应该是：			
	HttpServletRequest req = ctx.getRequest();
				boolean top = !Cat.getManager().hasContext();

				ctx.setTop(top);

				if (top) {
					ctx.setMode(detectMode(req));
					ctx.setType(CatConstants.TYPE_URL);

					setTraceMode(req);
				} else {
					ctx.setType(CatConstants.TYPE_URL_FORWARD);
				}

				ctx.handle();
			}

请问，URL与URLForward到底有什么却别？？为什么要这样区分类型？？

**Comment by topCoderzhangshuo** [comment]
CAT 有个Pigeon ？请问这个词怎么理解？？什么事Pigeon 服务？？

**Comment by topCoderzhangshuo** [comment]
为什么把我的问题删了？？？

**Comment by dreampaowj** [comment]
布丁小贷+www.bdxiaodai.com 准备使用cat来监控java项目

**Comment by lynnchae** [comment]
cat的微信群、qq群充斥着各种问题，很少有人解答，点评的人说：没有人义务为你解答问题，或者就是直接让你看code。一个好的开源产品，众人的力量是不可忽视的。cat在使用时存在各方面问题，而没有一个好的文档支持，虽然网上有部分人总结，但如果是开发者本身来弄自然是最好。谁造谁最清楚。

**Comment by qmwu2000** [comment]
其实我们有一个非常活跃的微信群，大家可以加微信：qmwu2000或youyong205，可以帮你拉入微信群。


发自我的 iPhone

**Comment by helloworldtang** [comment]
小蚁http://www.xiaoyi.com/

**Comment by bloodstars** [comment]
万达金融集团-大数据中心

**Comment by Silencesk** [comment]
云盛海宏信息技术(深圳)有限公司-供应链系统部-准备中。。。

**Comment by 469147521** [comment]
中电飞华通信股份有限公司-互动传媒部-移动学习平台-准备中

**Comment by lucifer1024** [comment]
汇通天下   http://www.g7.com.cn/

**Comment by caozhenak** [comment]
武汉天罡信息技术有限公司　扫多多智能服务平台　http:.//www.saoduoduo.com

**Comment by ahuazhu** [comment]
什么值得买 http://www.smzdm.com

**Comment by xieguohai** [comment]
家乐宝 www.jialebao.cc

**Comment by wanghao123456** [comment]
天津国药+www.sinopharmtj.cn

**Comment by CuZn13** [comment]
中国网库 www.99114.com

**Comment by fullstack-dev** [comment]
菠萝三维www.pineprint.com

**Comment by mclarenhao** [comment]
跨境电商 特维西科技 www.tvc-mall.com

**Comment by nellochen** [comment]
贵金属交易 联合黄金 http://www.bjlhhr.com/

**Comment by xueshijun** [comment]
cisco www.cisco.com

**Comment by hackland** [comment]
www.xinrongnews.com  腾信堂 准备中；

**Comment by qmwu2000** [comment]
特维西科技 http://www.tvc-mall.com

**Comment by hackland** [comment]
公司：腾信堂，www.xinrongnews.com



在 2016-12-28 21:42:44，"Frankie Wu" <notifications@github.com> 写道：


特维西科技 http://www.tvc-mall.com

**Comment by zeuskingzb** [comment]
自在客 http://www.zizaike.com

**Comment by NicholasQu** [comment]
米么金服 https://www.memedai.cn

**Comment by chengdongwei** [comment]
哆啦宝 http://open.duolabao.cn/

**Comment by major2015** [comment]
嗨动婚礼 http://www.hidongtv.com/

**Comment by laoshancun** [comment]
华律网 www.66law.cn

**Comment by i79627313** [comment]
51gif准备接入cat,求指导 www.51gif.com

**Comment by BigbigY** [comment]
智慧树 www.bbtree.com

**Comment by caozhenak** [comment]
北京统游

**Comment by woshiyjs123** [comment]
有利网 www.yooli.com

**Comment by gitSunny0501** [comment]
.Net监控，git地址在哪？谢谢！

**Comment by guyaqiongyan** [comment]
彩贝壳  www.caibeike.com

**Comment by major2015** [comment]
别样海淘 www.bybieyang.com/cn/ 准备接入cat。

**Comment by PGDream** [comment]
木仓科技  www.mucang.cn

**Comment by MarinFire** [comment]
中通快递http://www.zto.com/

**Comment by andersonme** [comment]
钱宝网 www.qbao.com

**Comment by visionsky1986** [comment]
资邦金服

**Comment by xupuchenxi** [comment]
上海亚太信息

**Comment by birdie7761** [comment]
上海吉祥航空 [www.juneyaoair.com](http://www.juneyaoair.com/)

**Comment by lebronye** [comment]
酷狗直播 www.fanxing.com 报到迟了，已经接入了2年，cat不错，帮了不少忙。

**Comment by yxw434** [comment]
广州至真 www.batmobi.net

**Comment by yxw434** [comment]
@lebronye 请求大神指点，能加下qq：441528959 指点一下吗？

**Comment by hngqy** [comment]
平安普惠  能加下qq吗？  1289855779，求指点下
现在部署在window上没问题，在linux里面，把cat.war部署进去tomcat就退了，没有任何报错信息，怎么回事？

**Comment by jinyingone** [comment]
有qq交流群吗

**Comment by seewoo** [comment]
上海猎鹰网络 http://www.lieying.cn/
部署了三个节点，2台处理监控请求，一台用于Job, 实际应用中发现，所有压力全在其中一台监控服务，负载均衡无效，不确定是我配置问题，还是开源版本中负载需要自己开发？

**Comment by qmwu2000** [comment]
应该是配置问题或者是项目监控数据不均衡所致，cat开源版本是支持负载均衡的。

发自我的 iPhone

**Comment by NumberSevens** [comment]
土巴兔 www.to8to.com QQ : 173060964

**Comment by linzhihaochina** [comment]
借贷宝 http://www.jiedaibao.com/

**Comment by qq317114793** [comment]
问下，存储方式可以使用其它方式吗，不只有mysql数据的形式进行存储

**Comment by xulayen** [comment]
xulayen@163.com个人想学习一下。有文档吗

**Comment by dreamyzhang** [comment]
深圳慧网基金  https://invesmart.cn   QQ : 775745576

**Comment by YanxiSir** [comment]
星云链 [http://www.nebulas.io](url)

**Comment by franparsunland** [comment]
捷越联合 https://www.jieyuechina.com/index.html

**Comment by MrTong0807** [comment]
北京雷鸣电商  leimingtech.com

**Comment by xho22** [comment]
哔哩哔哩游戏  www.biligame.com

**Comment by 747510350** [comment]
啄木鸟家庭维修 www.xiujiadian.com

**Comment by q1457797371** [comment]
![image](https://user-images.githubusercontent.com/16666310/45139880-d1c76b80-b1e3-11e8-8035-dc70f5235dad.png)
![image](https://user-images.githubusercontent.com/16666310/45139906-e1df4b00-b1e3-11e8-9d63-d1eb2f325670.png)
为什么部署好了， 但是发了消息cat监控平台有时候可以，有时候查不到消息。本人微信：liuxia8_com 麻烦加一下微信群，谢谢

**Comment by huanggreat** [comment]
物流源    http://www.wlyuan.com

**Comment by marskbt** [comment]
量富征信 http://www.liangfuzhengxin.com/

**Comment by ljj18** [comment]
魔谐软件 https://www.aladingbank.com

**Comment by njkfei** [comment]
金汇金融　https://www.jinhui365.com

**Comment by songlijiang** [comment]
票牛网  www.piaoniu.com

**Comment by xburning** [comment]
驴妈妈旅游网  www.lvmama.com

**Comment by bryan31** [comment]
野兽派 www.thebeastshop.com

**Comment by fuhao009** [comment]
杭州叁点零易货交易所 www.ehuoo.com

**Comment by lycenway** [comment]
什么值得买 www.smzdm.com

**Comment by lining-github** [comment]
bilibili www.bilibili.com

**Comment by maleeeei** [comment]
麦田守望收银管理系统 www.goodsfans.com

**Comment by pkunray** [comment]
信用飞 www.xinyongfei.cn

**Comment by yxyx520** [comment]
yealink www.yealink.com
搭建好了，不知道怎么接入。比如c程序，java程序等

**Comment by zman911** [comment]
91porn.com
pornhub.com
就问你服不服~

**Comment by stdrickforce** [comment]
> 91porn.com
> pornhub.com
> 就问你服不服~

我觉得搞技术的人没必要这么 low 吧。

**Comment by foamfish** [comment]
华夏信财股权投资管理有限公司 https://www.huaxiafinance.com/

CAT是一个很好的应用监控工具，谢谢老吴和尤勇的努力和开源精神

希望能多多交流~

**Comment by leavecu** [comment]
卓越教育 牛师帮 http://niushibang.gaofen.com/

**Comment by ai-hes** [comment]
神州租车 http://www.zuche.com/

**Comment by grayglj** [comment]
华住酒店    https://www.huazhu.com/

**Comment by tomatofrommars** [comment]
头等仓 https://www.toodc.cn

**Comment by superheizai** [comment]
中通快递， https://www.zto.cn/

**Comment by MonkeyOn** [comment]
qq:908758019

**Comment by ZhaoFJ** [comment]
星星充电，http://www.starcharge.com/

**Comment by yangfanchuhai** [comment]
小影，http://www.xiaoying.tv/

**Comment by kame000** [comment]
小E微店，http://www.xedaojia.com

**Comment by IReallyWantYou** [comment]
车兔宝 http://www.chetubao.cn/

**Comment by michaelyf1** [comment]
汇添富基金 http://www.99fund.com

**Comment by lenaryfun** [comment]
来三斤 http://www.laisanjn.cn

**Comment by EdwinLi** [comment]
网易传媒 www.163.com

**Comment by sslovett** [comment]
团子出行  www.tz12306.com

**Comment by yab** [comment]
云幂信息 www.yunmicloud.com

**Comment by njkfei** [comment]
金汇金融 www.jinhui365.com

**Comment by weijeuye** [comment]
驴妈妈旅游网 [www.lvmama.com](url)

**Comment by zxjllll** [comment]
> 大众点评 [www.dianping.com](http://www.dianping.com)
> 
> 不要在此issue里面提各种问题，谢谢配合。

方欣科技 http://www.foresee.com.cn/

**Comment by albertflyer** [comment]
太美医疗 http://www.taimeitech.com/

**Comment by lcyswxy** [comment]
乐心 http://www.lifesense.com/

**Comment by bigfanofcpp** [comment]
款等科技 http://www.kuandeng.com

**Comment by woxiangwoxiangxiang** [comment]
保驾出行 http://www.baojia.com 
您好我想请问您一个问题：咱们的cat在添加告警的时候，点击提交后会出现400错误。18611426746@163.com

**Comment by javaXiaoHan** [comment]
合康智能 http://www.hiconics-zn.com/

**Comment by wasiker** [comment]
圆通速递 http://www.yto.net.cn/

**Comment by wasiker** [comment]
圆通速递 http://www.yto.net.cn/    xzsftaotao@126.com

**Comment by javaXiaoHan** [comment]
请问发圆通链接给我 是干什么的




------------------ 原始邮件 ------------------
发件人: "wasiker"<notifications@github.com>; 
发送时间: 2019年5月24日(星期五) 上午9:55
收件人: "dianping/cat"<cat@noreply.github.com>; 
抄送: "卡卡西"<820685073@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [dianping/cat] 接入CAT的公司留下联系方式，公司+网址，谢谢。 (#753)




圆通速递 http://www.yto.net.cn/    xzsftaotao@126.com

**Comment by madlouse** [comment]
360金融 https://www.360jinrong.net/

**Comment by javaXiaoHan** [comment]
武汉合康智能电气有限公司
http://www.hiconics-zn.com/





------------------ 原始邮件 ------------------
发件人: "Jeking.Hwang"<notifications@github.com>; 
发送时间: 2019年5月29日(星期三) 下午5:02
收件人: "dianping/cat"<cat@noreply.github.com>; 
抄送: "卡卡西"<820685073@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [dianping/cat] 接入CAT的公司留下联系方式，公司+网址，谢谢。 (#753)




360金融 https://www.360jinrong.net/

**Comment by xmgddk** [comment]
广州致景科技有限公司
https://www.baibu.la

**Comment by javaXiaoHan** [comment]
机器人吗？



------------------ 原始邮件 ------------------
发件人: "xmgddk"<notifications@github.com>; 
发送时间: 2019年5月29日(星期三) 下午5:30
收件人: "dianping/cat"<cat@noreply.github.com>; 
抄送: "卡卡西"<820685073@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [dianping/cat] 接入CAT的公司留下联系方式，公司+网址，谢谢。 (#753)




广州致景科技有限公司
 https://www.baibu.la

**Comment by HanWang945** [comment]
百果园
http://www.pagoda.com.cn/

**Comment by jiaxinxuan** [comment]
晓圈科技   www.iquanwai.com

**Comment by jackzhangyk** [comment]
马蜂窝 www.mafengwo.com

**Comment by zhangshl** [comment]
贝壳找房 ke.com

**Comment by guxsun** [comment]
服务端进行告警配置，输入账号密码admin后点登陆没反应

**Comment by singgel** [comment]
雪球财经
www.ke.com

**Comment by Lovnx** [comment]
G7（北京汇通天下物联科技有限公司）
https://www.g7.com.cn/

**Comment by lingjiaju** [comment]
中油碧辟石油有限公司
http://www.bppc.com.cn

**Comment by lghuntfor** [comment]
伙伴集团
http://www.zhaoshang800.cn

**Comment by webCoderJ** [comment]
客如云
[www.keruyun.com](www.keruyun.com)

**Comment by yuyulab** [comment]
神州优车 http://www.ucarinc.com
瑞幸咖啡 http://www.luckincoffee.com
宝沃汽车 http://www.borgward.com.cn/

**Comment by tbdpmi** [comment]
鑫互联  https://www.leadscloud.com/

**Comment by WildWolfBang** [comment]
360金融 https://www.360jinrong.net/

**Comment by weyoung3350** [comment]
八维通 www.bwton.com
谢谢

**Comment by yangfanchuhai** [comment]
小影 http://www.xiaoying.tv/

**Comment by baobeidade** [comment]
凹凸租车

**Comment by tbdpmi** [comment]
鑫互联 https://www.leadscloud.com/

**Comment by cndjhsb** [comment]
用友网络 www.yonyou.com

**Comment by fengzihua** [comment]
cat怎么创建其他登录用户，和权限分配

**Comment by fengzihua** [comment]
我是个人




| |
fengzihua54
|
|
邮箱：fengzihua54@163.com
|

Signature is customized by Netease Mail Master

在2019年11月13日 17:49，fengzihua 写道：

cat怎么创建其他登录用户，和权限分配

**Comment by suiyuan121** [comment]
> 尚品网 [www.shangpin.com](http://www.shangpin.com)

公司居然不在了，时间太可怕了

**Comment by firmament2008** [comment]
> 我是个人 | | fengzihua54 | | 邮箱：fengzihua54@163.com | Signature is customized by Netease Mail Master 在2019年11月13日 17:49，fengzihua 写道： cat怎么创建其他登录用户，和权限分配 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

只有管理后台。写入CAT的信息都是开发自行维护的。

**Comment by TaXueWWL** [comment]
爱奇艺，https://www.iqiyi.com/

**Comment by YoungRainyDay** [comment]
卓健科技，http://zhuojianchina.com

**Comment by compilerduck** [comment]
当当网，http://www.dangdang.com

**Comment by zhangzc0419** [comment]
麻袋财富，www.madaicaifu.com

**Comment by SuperBaBa** [comment]
圆通速递， http://www.yto.net.cn/

**Comment by goMatchHtc** [comment]
微洱科技，https://weierai.com/

**Comment by kingyiu87** [comment]
喜百年供应链 [https://www.xbnwl.com](https://www.xbnwl.com)

**Comment by sunOnly** [comment]
武汉小药药  http://www.ybm100.com/

**Comment by chrisptang** [comment]
乐其电商：https://www.leqee.com/

**Comment by pengxingsong** [comment]
晨光科力普 https://www.colipu.com/

**Comment by lmx110522** [comment]
**天眼查**   www.tianyancha.com

**Comment by zhj12388** [comment]
有讨论群号吗？想加一个

**Comment by wusb** [comment]
小红书 www.xiaohongshu.com

**Comment by YouthAndra** [comment]
湖南快乐通宝小额贷款有限公司 www.kltb.com.cn

**Comment by albedel** [comment]
韵达快递 http://www.yundaex.com/

**Comment by bigcoder84** [comment]
头等仓：https://www.toodc.cn

**Comment by WenTao-Love** [comment]
爱奇艺乐道中台

**Comment by vince002** [comment]
广东百慧科技有限公司 http://www.gdbyway.com

**Comment by situgmail** [comment]
前期调研，准备接入。
广州悦行旅行社有限公司 https://www.heycars.cn

**Comment by gaoxinfu** [comment]
海尔消费金融 https://www.haiercash.com/

**Comment by sunqinbo** [comment]
东奥会计在线 https://www.dongao.com 2017年接入

**Comment by zyy** [comment]
致诚信用 https://www.zhichengcredit.com/

**Comment by peterpanzsy** [comment]
淡水泉投资 https://www.springs-capital.com/#/

**Comment by xiejuntao** [comment]
上海畅指网络科技有限公司 https://www.ldmnq.com/about.html

**Comment by duchaos** [comment]
我爱我家集团
duchao@5i5j.com
