### ISSUE TITLE
cat 部署tomcat 出错

### ISSUE THREAD

**Issue by haqiaolong** [dianping/cat#757]
您好，我直接把war包 部署在 tomcat6 下 JDK也是6就报错。。
 麻烦指教。。运行TestServer就是没有问题的
java.lang.RuntimeException: Error occured during handling outbound action(dependency)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:84)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:183)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:60)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:304)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:400)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:224)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:310)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:207)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:115)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:240)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:164)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:462)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:562)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:395)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:250)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:188)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:166)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:302)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(dependency)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:34)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:106)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:181)
	... 35 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.dependency.Handler.handleOutbound(com.dianping.cat.report.page.dependency.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.dependency.Context@778b3fee])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:27)
	... 37 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.state.StateBuilder.buildStateMessage(StateBuilder.java:45)
	at com.dianping.cat.report.page.dependency.Handler.handleOutbound(Handler.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 38 more

**Comment by afredlyj** [comment]
搞定了吗？

**Comment by haqiaolong** [comment]
搞定了。。是我的tomcat端口8080
 调用API 还是2081 没该过来

**Comment by youyong205** [comment]
默认是2281，自己在server.xml 修改，具体文档里面有部署文档，你们如果生产环境部署，可以参考。
