### ISSUE TITLE
查看前一天当前小时的数据报500

### ISSUE THREAD

**Issue by afredlyj** [dianping/cat#759]
日志如下：

~~~~

[03-12 10:22:34.843] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-8) ...
[03-12 10:22:34.882] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/p
java.lang.RuntimeException: Error occured during handling outbound action(p)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:181)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:277)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:155)
	at org.unidal.web.MVC.service(MVC.java:72)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:83)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:400)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:224)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:310)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:207)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:115)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:53)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(p)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:34)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:202)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:275)
	... 34 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.problem.Handler.handleOutbound(com.dianping.cat.report.page.problem.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.problem.Context@ef0e024])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:27)
	... 36 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.consumer.problem.model.transform.BaseVisitor.visitProblemReport(BaseVisitor.java:52)
	at com.dianping.cat.report.page.problem.Handler.handleOutbound(Handler.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 37 more

~~~~

**Comment by youyong205** [comment]
你check下mysql 服务器里面report以及dailyreport是否有数据。
