### ISSUE TITLE
cat启动初始化操作

### ISSUE THREAD

**Issue by dlyss** [dianping/cat#771]
你好，cat启动是会初始化n多的操做，不知这块儿是否能有文档说明，大致执行了什么，谢谢。

**Comment by qmwu2000** [comment]
基本上，CAT启动时会显式地初始化配置，为各报表analyzer创建独立线程，启动后台管理线程，建立数据库连接和HDFS连接等。step by step，在log中应该都看得到。

**Comment by youyong205** [comment]
这个有兴趣可以多看源码，这应该是了解问题的最快的方式。

**Comment by dlyss** [comment]
[03-20 18:46:58.238] [ERROR] [CatHomeModule] failed to create a child event loop
java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:56)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:48)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:41)
	at com.dianping.cat.message.spi.core.TcpSocketReceiver.startServer(TcpSocketReceiver.java:100)
	at com.dianping.cat.message.spi.core.TcpSocketReceiver.init(TcpSocketReceiver.java:77)
	at com.dianping.cat.CatHomeModule.setup(CatHomeModule.java:100)
	at org.unidal.initialization.DefaultModuleInitializer.expandAll(DefaultModuleInitializer.java:72)
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:38)
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:24)
	at com.dianping.cat.servlet.CatServlet.initComponents(CatServlet.java:48)

**Comment by dlyss** [comment]
这个问题有碰到吗？谢谢

**Comment by youyong205** [comment]
这个还没遇到过，能给出你运行时候环境信息么，操作系统等等信息
