### ISSUE TITLE
Error occured during handling outbound action(router)

### ISSUE THREAD

**Issue by dlyss** [dianping/cat#779]
你好，以下的错误是什么原因哪？少配置？以下为访问url

http://192.168.11.36:8080/cat/s/router?domain=cat&ip=192.168.253.1

[03-25 15:17:31.611] [ERROR] [HttpServlet] Error occured when handling uri: /cat/s/router
java.lang.RuntimeException: Error occured during handling outbound action(router)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:86)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:185)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:62)
        at org.unidal.web.MVC.service(MVC.java:90)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:400)
        at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:224)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:310)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
        at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:207)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
        at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:115)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
        at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:619)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(router)
        at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:108)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:183)
        ... 32 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.system.page.router.Handler.handleOutbound(com.dianping.cat.system.page.router.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.system.page.router.Context@661e855f])
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
        at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
        ... 34 more
Caused by: java.lang.ArithmeticException: / by zero
        at com.dianping.cat.system.config.RouterConfigManager.queryServersByDomain(RouterConfigManager.java:137)
        at com.dianping.cat.system.page.router.Handler.handleOutbound(Handler.java:79)
        at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)

**Comment by fengjx** [comment]
+1，按文档搭建的单机版就是有问题，很多error

**Comment by zhouzongbo** [comment]
我单机构建的时候也遇到很多问题. 首先datasource.xml都读不了
