### ISSUE TITLE
消息发不出或收不到？

### ISSUE THREAD

**Issue by dlyss** [dianping/cat#783]
可以确认的是：1、客户端正常生成消息 2、服务端正常部署，未见error，就是在服务端看不到消息，如何定位或如何再客户端 服务端打日志定位？求助。
1、客户端日志：
[03-28 20:39:47.931] [INFO] [TcpSocketSender] sendInternal start ......
[03-28 20:39:47.932] [INFO] [TcpSocketSender] sendInternal buf size 36103
[03-28 20:39:47.932] [INFO] [TcpSocketSender] sendInternal channel [id: 0xe7129416, /192.168.11.11:60661 => /192.168.11.36:2280]
2、服务端暂未打日志
请问再在那个类打日志来定位原因？

**Comment by afredlyj** [comment]
Sender的日志，是在`sendInternal`方法中打印的吗？

看一下channel是不是连接你的服务器？

另外就是TcpSocketReceiver类可以加日志。

**Comment by qmwu2000** [comment]
查看一下配置文件client.xml，其中的server指向对不对

发自我的 iPhone

**Comment by dlyss** [comment]
感谢各位，client的配置是指向服务端的2280端口的。这个没有错。
客户端日志：
[03-29 10:50:34.584] [INFO] [ChannelManager] Connected to CAT server at /192.168.11.36:2280
[03-29 10:50:34.584] [INFO] [ChannelManager] close channel /192.168.11.36:2280
服务端日志：
[03-29 10:51:26.602] [INFO] [ChannelManager] Connected to CAT server at /192.168.11.36:2280
[03-29 10:51:26.602] [INFO] [ChannelManager] close channel null
我看下TcpSocketReceiver的日志定位。
一般诡异问题的背后都是一个比较二的原因，哈哈。

**Comment by dlyss** [comment]
TcpSocketReceiver.startServer  错误，日志如下：

[03-29 18:28:58.535] [ERROR] [CatHomeModule] failed to create a child event loop
java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:56)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:48)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:41)
	at com.dianping.cat.message.spi.core.TcpSocketReceiver.startServer(TcpSocketReceiver.java:101)
	at com.dianping.cat.message.spi.core.TcpSocketReceiver.init(TcpSocketReceiver.java:78)
	at com.dianping.cat.CatHomeModule.setup(CatHomeModule.java:100)
	at org.unidal.initialization.DefaultModuleInitializer.expandAll(DefaultModuleInitializer.java:72)
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:38)
	at org.unidal.initialization.DefaultModuleInitializer.execute(DefaultModuleInitializer.java:24)
	at com.dianping.cat.servlet.CatServlet.initComponents(CatServlet.java:48)
	at org.unidal.web.AbstractContainerServlet.init(AbstractContainerServlet.java:51)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5262)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5550)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.RuntimeException: Error during epoll_create1(...): Function not implemented
	at io.netty.channel.epoll.Native.epollCreate(Native Method)
	at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:70)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:71)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	... 29 more

**Comment by youyong205** [comment]
你默认启动内存多少

**Comment by dlyss** [comment]
jvm配置：

JAVA_OPTS="-Xms1024m -Xmx1024m -Xss512K -XX:MaxPermSize=256m"

**Comment by dlyss** [comment]
弱弱的问句：cat 的2280端口是在tomcat 的ajp那个配置项配的吧？原始的端口是8009

**Comment by youyong205** [comment]
2280 是cat自己启动的端口，用来tcp数据传输

**Comment by dlyss** [comment]
server端创建receiver时底层会使用Linux的epoll？Linux2.6内核中正式引入的，如下：
Error during epoll_create1(...): Function not implemented
at io.netty.channel.epoll.Native.epollCreate(Native Method)
是这样吗？

**Comment by dlyss** [comment]
初步确认，linux环境下对epoll有要求，否则2280端口起不来，会报：
Caused by: java.lang.RuntimeException: Error during epoll_create1(...): Function not implemented
at io.netty.channel.epoll.Native.epollCreate(Native Method)
错误，绕过去的方式是在receiver端将系统改为非linux环境，不使用epoll。

**Comment by dlyss** [comment]
初步确认，linux环境下对epoll有要求，否则2280端口起不来，会报：
Caused by: java.lang.RuntimeException: Error during epoll_create1(...): Function not implemented
at io.netty.channel.epoll.Native.epollCreate(Native Method)
错误，绕过去的方式是在receiver端将系统改为非linux环境，不使用epoll。

**Comment by dlyss** [comment]
初步确认，linux环境下对epoll有要求，否则2280端口起不来，会报：
Caused by: java.lang.RuntimeException: Error during epoll_create1(...): Function not implemented
at io.netty.channel.epoll.Native.epollCreate(Native Method)
错误，绕过去的方式是在receiver端将系统改为非linux环境，不使用epoll。
