### ISSUE TITLE
AppAlert报错，app数据源没有定义？

### ISSUE THREAD

**Issue by afredlyj** [dianping/cat#812]
```java

java.lang.RuntimeException: No data source(app) defined! 
at org.unidal.dal.jdbc.datasource.DefaultDataSourceManager.getDataSource(DefaultDataSourceManager.java:30) 
at org.unidal.dal.jdbc.transaction.DefaultTransactionManager.getConnection(DefaultTransactionManager.java:82) 
at org.unidal.dal.jdbc.query.DefaultQueryExecutor.createPreparedStatement(DefaultQueryExecutor.java:52) 
at org.unidal.dal.jdbc.query.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:80) 
at org.unidal.dal.jdbc.engine.DefaultQueryEngine.queryMultiple(DefaultQueryEngine.java:108) 
at com.dianping.cat.app.AppCommandDataDao.findDataByMinuteCode(AppCommandDataDao.java:62) 
at com.dianping.cat.report.service.app.AppDataService.queryValue(AppDataService.java:393) 
at com.dianping.cat.report.task.alert.app.AppAlert.fetchDatas(AppAlert.java:82) 
at com.dianping.cat.report.task.alert.app.AppAlert.processRule(AppAlert.java:146) 
at com.dianping.cat.report.task.alert.app.AppAlert.run(AppAlert.java:241) 
at java.lang.Thread.run(Thread.java:662) 
at org.unidal.helper.Threads$RunnableThread.run(Threads.java:292) 

```

**Comment by youyong205** [comment]
/data/appdatas/cat/datasources.xml  自己定义一份
