### ISSUE TITLE
按文档步骤配置好后，浏览器打开报503错误

### ISSUE THREAD

**Issue by chaiziqi** [dianping/cat#820]
1、按文档步骤配置好后，使用mvn jetty:run命令运行，在浏览器中打开报503错误，发布到TomCat同样报错，请教解决方案。
2、在.Net系统中如何来实现Cat集成？

HTTP ERROR 503

Problem accessing /cat/r. Reason: 
    org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core

realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

Caused by:
javax.servlet.UnavailableException: org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core

realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

	at org.mortbay.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:415)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:451)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:736)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.jetty.plugin.Jetty6PluginWebAppContext.doStart(Jetty6PluginWebAppContext.java:115)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.plugin.AbstractJettyRunMojo.restartWebApp(AbstractJettyRunMojo.java:458)
	at org.mortbay.jetty.plugin.AbstractJettyRunMojo$1.filesChanged(AbstractJettyRunMojo.java:419)
	at org.mortbay.util.Scanner.reportBulkChanges(Scanner.java:486)
	at org.mortbay.util.Scanner.reportDifferences(Scanner.java:352)
	at org.mortbay.util.Scanner.scan(Scanner.java:280)
	at org.mortbay.util.Scanner$1.run(Scanner.java:232)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by youyong205** [comment]
你check下你本机的/data/appdatas/cat/ 有木有对应的几个config文件

**Comment by chaiziqi** [comment]
共3个配置文件都在的，一开始默认端口一样的错误，改了端口发布到TomCat还是一样报错

**Comment by chaiziqi** [comment]
下面是使用mvn jetty:run命令运行  其中有[ERROR] 错误：

[INFO] Reload Mechanic: automatic
[INFO] Classes = D:\cat-master\cat-master\cat-home\target\classes
[INFO] Logging to org.slf4j.impl.SimpleLogger(org.mortbay.log) via org.mortbay.l
og.Slf4jLog
[INFO] Context path = /cat
[INFO] Tmp directory =  determined at runtime
[INFO] Web defaults = org/mortbay/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = D:\cat-master\cat-master\cat-home\src\main\webapp\WEB-INF\
web.xml
[INFO] Webapp directory = D:\cat-master\cat-master\cat-home\src\main\webapp
[INFO] Starting jetty 6.1.26 ...
[INFO] jetty-6.1.26
[INFO] No Transaction manager found - if your webapp requires one, please config
ure one.
Logger file D:\data\applogs\cat\cat_20150530.log
log4j:WARN No appenders could be found for logger (io.netty.util.internal.loggin
g.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
[05-30 15:10:42.042] [WARN] [cat] Cat is lazy initialized!
[ERROR] unavailable
org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLif
ecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.life
cycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

**Comment by youyong205** [comment]
要不你pull下code，重新来一次，刚刚还有个人用docker顺利解决了。

**Comment by youyong205** [comment]
https://github.com/dianping/cat/issues/822
