### ISSUE TITLE
CatFilter会支持Servlet 3.0的异步处理接口吗？

### ISSUE THREAD

**Issue by yiming187** [dianping/cat#823]
目前如果对servlet启动<async-supported>true</async-supported>,加载CatFilter之后，会有如下报错。
Jersey版本2.17，servlet-api 3.10，jetty-webapp 9.2.11，去掉CatFilter则没有问题，因此判断是CatListener暂不支持asynchronous request。
应用REST接口定义中，使用了 @Suspended

```
javax.servlet.ServletException: javax.ws.rs.ProcessingException: Attempt to suspend a connection of an asynchronous request failed in the underlying container.
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:421)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:400)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:224)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:310)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:207)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:115)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:398)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:53)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.ws.rs.ProcessingException: Attempt to suspend a connection of an asynchronous request failed in the underlying container.
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:328)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401)
	... 33 more
```

**Comment by yiming187** [comment]
忽略我的问题，是配置问题。如下配置可行。
	<filter>
		<filter-name>cat-filter</filter-name>
		<filter-class>com.dianping.cat.servlet.CatFilter</filter-class>
		<async-supported>true</async-supported>
	</filter>
