### ISSUE TITLE
访问“实时”/cat/r/t的时候一直报错

### ISSUE THREAD

**Issue by wn905** [dianping/cat#832]
使用 tomcat 7.0.62
linux ubuntu环境下，maven install成功，mysql安装成功。
启动tomcat后，文档/离线/配置都可以正常访问，只有“实时”一直报错。在/data/中的日志如下：

[06-21 20:13:06.006] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-18) ...
[06-21 20:13:06.014] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/t
java.lang.RuntimeException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:86)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:185)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:62)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:395)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:305)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:202)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:110)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:108)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:183)
	... 38 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.transaction.Handler.handleOutbound(com.dianping.cat.report.page.transaction.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.transaction.Context@1bd4207d])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 40 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:70)
	at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:14)
	at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 41 more

**Comment by wn905** [comment]
一个奇怪的现象。如果访问历史数据，可以正常显示，如果访问当前2小时内的数据，则报错。
如果访问： http://localhost:8080/cat/r/e?op=view&domain=cat&date=2015062112，则可以，虽然没有数据。
如果访问：http://localhost:8080/cat/r/e?op=view&domain=cat&date=2015062119，则报错

**Comment by youyong205** [comment]
在本地运行mvn eclipse:eclipse 然后作为普通项目倒入eclipse，然后运行cat-home里面的testserver试试

**Comment by zcoson** [comment]
可能是使用端口的问题，在client.xml、server.xml文件中

**Comment by ajcheng** [comment]
我的是因为jdk问题，还有server.xml没有配置好（默认是2281端口，我改用tomcat跑的）
$ java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

**Comment by CmZhangxin** [comment]
我的同样是这个问题，请问最后有解决方案吗？

**Comment by 1455066227** [comment]
有解决办法吗，同样的，当前时间两小时内的就报错，之前的历史就可以访问

**Comment by huyanfu** [comment]
请问解决了吗？ 我这是选择now的时候报错，访问其他的是没有问题的。

**Comment by zdf068** [comment]
我删除了一下buket 文件夹恢复正常啦

**Comment by songhx** [comment]
> 有解决办法吗，同样的，当前时间两小时内的就报错，之前的历史就可以访问

大家都怎么解决的

**Comment by csm19910701** [comment]
有解决办法吗？我也遇到这种情况
