### ISSUE TITLE
 按着readme 步骤 运行 mvn jetty:run 出错

### ISSUE THREAD

**Issue by moujian** [dianping/cat#855]
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error constructing component role: 'org.unidal.web.mvc.lifecycle.RequestContextBuilder', implementation: 'org.unidal.web.mvc.lifecycle.DefaultRequestContextBuilder', role hint: 'default'
  at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:176)
  at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:123)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
  at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
  at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
  ... 37 more
Caused by: org.apache.xbean.recipe.ConstructionException: Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.unidal.web.mvc.model.ModelManager for injection private org.unidal.web.mvc.model.ModelManager org.unidal.web.mvc.lifecycle.DefaultRequestContextBuilder.m_modelManager
  at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:472)
  at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:367)
  at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:282)
  at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
  at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
  at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
  at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
  ... 41 more
Caused by: java.lang.RuntimeException: Duplicated name(home) found between handleInbound() and handleInbound() of class com.dianping.cat.report.ReportModule
  at org.unidal.web.mvc.model.ModelManager.buildInbound(ModelManager.java:105)
  at org.unidal.web.mvc.model.ModelManager.buildModuleFromMethods(ModelManager.java:196)
  at org.unidal.web.mvc.model.ModelManager.buildModuleFromHandlers(ModelManager.java:166)
  at org.unidal.web.mvc.model.ModelManager.buildModule(ModelManager.java:156)
  at org.unidal.web.mvc.model.ModelManager.build(ModelManager.java:79)
  at org.unidal.web.mvc.model.ModelManager.register(ModelManager.java:320)
  at org.unidal.web.mvc.model.ModelManager.initialize(ModelManager.java:303)
  at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
  at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:97)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
  at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:283)
  at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:129)
  at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
  at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
  at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
  at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
  at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
  at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
  at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
  at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
  at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:466)
  ... 47 more

**Comment by moujian** [comment]
换了Mac, centos 都是这样。

**Comment by moujian** [comment]
求助 @youyong205

**Comment by jialinsun** [comment]
我在我本机和别人全新的环境下，重新试了一遍是没有问题的。你看看你在install的时候，有没有报什么错误。实在不行，导入项目到Eclipse启动cat-home TestServer启动，或者在mvn install之后把cat-home/target/下的war包放到tomcat里启动试试。先确定一下你是否拉到了所有的依赖jar包。

**Comment by jialinsun** [comment]
我在我本机和别人全新的环境下，重新试了一遍是没有问题的。你看看你在install的时候，有没有报什么错误。实在不行，导入项目到Eclipse启动cat-home TestServer启动，或者在mvn install之后把cat-home/target/下的war包放到tomcat里启动试试。先确定一下你是否拉到了所有的依赖jar包。

**Comment by moujian** [comment]
jdk8 有问题。

**Comment by jialinsun** [comment]
不要用JDK8，我们验证过7是可以的，但是我们主要还是用6。
