### ISSUE TITLE
配置－>项目基本信息->添加/删除操作，都报空指针异常

### ISSUE THREAD

**Issue by heytong** [dianping/cat#857]
其他功能都正常使用，就这里报错。请问下，是哪里有问题呢？

[ERROR] [HttpServlet] Error occured when handling uri: /cat/s/config
java.lang.RuntimeException: Error occured during handling outbound action(config)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:395)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:305)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:202)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:110)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(config)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:186)
	... 40 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.system.page.config.Handler.handleOutbound(com.dianping.cat.system.page.config.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.system.page.config.Context@488e8613])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 42 more
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1125)
	at com.dianping.cat.service.ProjectService.update(ProjectService.java:194)
	at com.dianping.cat.system.page.config.processor.GlobalConfigProcessor.updateProject(GlobalConfigProcessor.java:208)
	at com.dianping.cat.system.page.config.processor.GlobalConfigProcessor.process(GlobalConfigProcessor.java:82)
	at com.dianping.cat.system.page.config.Handler.handleOutbound(Handler.java:125)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 43 more

**Comment by chinaboard** [comment]
在数据库里把自带的报警项删掉就好了，我忘了具体是哪个了

**Comment by jdzwhy** [comment]
我也遇到了这个问题，请问能说一下要删除哪个表的那条记录吗？我把config_modification全删除了也不行

**Comment by jialinsun** [comment]
这是添加项目信息submit的时候报的异常，但是这个方法已经不再用了，页面上也没有触发点，是已经弃用的。项目信息是不应该需要添加的，都是自动添加的。这个我猜测是手动拼的URL去触发的，手动拼的URL没法模拟post数据，因为project这个对象的Domain信息为空，所以NPE了。至于删除的异常，我没有遇到过，可以再把删除出现的异常堆栈信息贴一下。

**Comment by zxj19880903** [comment]
@jialinsun 
我的也是添加项目报错链接没找到
![qq20150911-1 2x](https://cloud.githubusercontent.com/assets/7284550/9814710/b7b42a12-58c2-11e5-9980-493948667653.png)

**Comment by youyong205** [comment]
不需要添加项目，项目是当客户端练上去，自动会有的。

**Comment by tom2ling** [comment]
@heytong 这个问题解决了吗？有没有添加监控机的具体文档。第一次安装很多都不了解。谢谢
