### ISSUE TITLE
单机部署cat，【实时】无法进入。

### ISSUE THREAD

**Issue by zxh** [dianping/cat#875]
单机本地tomcat部署。
可以访问http://localhost:8080/cat/r/home。可以访问其他菜单。
点击【实时】，访问http://localhost:8080/cat/r/t?domain=cat&ip=&date=2015090717&reportType=day&op=view，报错。

[09-07 17:31:15.377] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-14) ...
[09-07 17:31:15.379] [ERROR] [HttpServlet] Error occured when handling uri: /cat/r/t
java.lang.RuntimeException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:395)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:305)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:202)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:110)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:393)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(t)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:186)
	... 39 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.transaction.Handler.handleOutbound(com.dianping.cat.report.page.transaction.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.transaction.Context@537c3243])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 41 more
Caused by: java.lang.NullPointerException
	at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:70)
	at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:14)
	at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
	... 42 more
[09-07 17:34:23.585] [INFO] [DefaultModuleContext] Starting thread(Cat-ModelService-15) ...

**Comment by zhangcunxin** [comment]
你cat-agent启动了嘛？我也是刚研究这玩意

**Comment by youyong205** [comment]
cat-agent没用的，你在拉最新code试试

**Comment by zhangcunxin** [comment]
你是按照
![image](https://cloud.githubusercontent.com/assets/10124042/9899968/f94dbdbe-5c8f-11e5-95dd-8bc93e2eb3ff.png)ze这个做的吗？ 我可以跑起来，但是好多不懂

**Comment by youyong205** [comment]
恩，这个蛮全的

**Comment by zxh** [comment]
单机部署有问题，问题可以复现。多台部署，没有上面提到的问题。但是还是有tcp链接不释放的问题。不用cat了。

**Comment by qmwu2000** [comment]
不应该有这个问题的。你可以详细一点描述一下你那边的问题吗？


发自我的 iPhone

**Comment by csm19910701** [comment]
> 不应该有这个问题的。你可以详细一点描述一下你那边的问题吗？
> 
> 发自我的 iPhone
> 
> > 在 2015年9月25日，16:00，zhuxuehan [notifications@github.com](mailto:notifications@github.com) 写道：
> > 单机部署有问题，问题可以复现。多台部署，没有上面提到的问题。但是还是有tcp链接不释放的问题。不用cat了。
> > ―
> > Reply to this email directly or view it on GitHub.

我也遇到这个问题了，大佬

**Comment by csm19910701** [comment]
Error occured when handling uri: /cat/r/t
java.lang.RuntimeException: Error occured during handling outbound action(t)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:190)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
        at org.unidal.web.MVC.service(MVC.java:90)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:105)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)
        at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)
        at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)
        at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(t)
        at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
        at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
        ... 43 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.report.page.transaction.Handler.handleOutbound(com.dianping.cat.report.page.transaction.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.report.page.transaction.Context@60e29937])
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
        at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
        ... 45 more
Caused by: java.lang.NullPointerException
        at com.dianping.cat.report.page.transaction.transform.AllMachineMerger.visitTransactionReport(AllMachineMerger.java:92)
        at com.dianping.cat.report.page.transaction.transform.TransactionMergeHelper.mergeAllMachines(TransactionMergeHelper.java:34)
        at com.dianping.cat.report.page.transaction.Handler.handleOutbound(Handler.java:238)
        at sun.reflect.GeneratedMethodAccessor304.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)
