### ISSUE TITLE
jetty-plugin:6.1.26:run (default-cli) @ cat-home Run Error

### ISSUE THREAD

**Issue by dyjiangjh** [dianping/cat#892]
[INFO] <<< maven-jetty-plugin:6.1.26:run (default-cli) < test-compile @ cat-home <<<
[INFO]
[INFO] --- maven-jetty-plugin:6.1.26:run (default-cli) @ cat-home ---
[WARNING] Error injecting: org.mortbay.jetty.plugin.Jetty6RunMojo
java.lang.NoClassDefFoundError: org/mortbay/util/Attributes
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

**Comment by scudy** [comment]
这个问题怎么解决的？ 现在我本地也有这个问题
