### ISSUE TITLE
master的拉下来报错，启动的时候，启动不起来

### ISSUE THREAD

**Issue by zhangzhenhuajack** [dianping/cat#900]
[INFO] Web overrides =  none
[INFO] web.xml file = /Users/jack/git_hub/cat/cat-home/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /Users/jack/git_hub/cat/cat-home/src/main/webapp
[INFO] Starting jetty 6.1.26 ...
[INFO] jetty-6.1.26
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
Logger file /data/applogs/cat/cat_20151102.log
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
[11-02 19:29:45.045] [WARN] [cat] Cat is lazy initialized!
[ERROR] unavailable
org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

	at org.unidal.web.AbstractContainerServlet.lookup(AbstractContainerServlet.java:74)
	at org.unidal.web.MVC.initComponents(MVC.java:35)
	at org.unidal.web.AbstractContainerServlet.init(AbstractContainerServlet.java:51)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:736)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
	at org.mortbay.jetty.plugin.Jetty6PluginWebAppContext.doStart(Jetty6PluginWebAppContext.java:115)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
	at org.mortbay.jetty.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:156)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.plugin.Jetty6PluginServer.start(Jetty6PluginServer.java:132)
	at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:454)
	at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:396)
	at org.mortbay.jetty.plugin.AbstractJettyRunMojo.execute(AbstractJettyRunMojo.java:210)
	at org.mortbay.jetty.plugin.Jetty6RunMojo.execute(Jetty6RunMojo.java:184)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:373)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:388)
	at org.unidal.web.AbstractContainerServlet.lookup(AbstractContainerServlet.java:72)
	... 47 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error constructing component role: 'org.unidal.web.lifecycle.RequestLifecycle', implementation: 'org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle', role hint: 'mvc'
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:176)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:123)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	... 50 more
Caused by: org.apache.xbean.recipe.ConstructionException: Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.unidal.web.mvc.lifecycle.RequestContextBuilder for injection private org.unidal.web.mvc.lifecycle.RequestContextBuilder org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.m_builder
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:472)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:367)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:282)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
	... 54 more
Caused by: org.apache.xbean.recipe.ConstructionException: Composition failed of field null in object of type org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle because the requirement ComponentRequirement{role='org.unidal.web.mvc.lifecycle.RequestContextBuilder', roleHint='', fieldName='null'} was missing)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:413)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:466)
	... 60 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.unidal.web.mvc.lifecycle.RequestContextBuilder', it could not be started.
      role: org.unidal.web.mvc.lifecycle.RequestContextBuilder
  roleHint: default
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:373)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
	... 63 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error constructing component role: 'org.unidal.web.mvc.lifecycle.RequestContextBuilder', implementation: 'org.unidal.web.mvc.lifecycle.DefaultRequestContextBuilder', role hint: 'default'
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:176)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:123)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	... 66 more
Caused by: org.apache.xbean.recipe.ConstructionException: Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.unidal.web.mvc.model.ModelManager for injection private org.unidal.web.mvc.model.ModelManager org.unidal.web.mvc.lifecycle.DefaultRequestContextBuilder.m_modelManager
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:472)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:367)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:282)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
	... 70 more
Caused by: java.lang.RuntimeException: Duplicated name(home) found between handleInbound() and handleInbound() of class com.dianping.cat.report.ReportModule
	at org.unidal.web.mvc.model.ModelManager.buildInbound(ModelManager.java:105)
	at org.unidal.web.mvc.model.ModelManager.buildModuleFromMethods(ModelManager.java:196)
	at org.unidal.web.mvc.model.ModelManager.buildModuleFromHandlers(ModelManager.java:166)
	at org.unidal.web.mvc.model.ModelManager.buildModule(ModelManager.java:156)
	at org.unidal.web.mvc.model.ModelManager.build(ModelManager.java:79)
	at org.unidal.web.mvc.model.ModelManager.register(ModelManager.java:320)
	at org.unidal.web.mvc.model.ModelManager.initialize(ModelManager.java:303)
	at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
	at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:97)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:283)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:129)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:466)
	... 76 more
[INFO] Started SelectChannelConnector@0.0.0.0:2281
[INFO] Started Jetty Server
[INFO] Starting scanner at interval of 10 seconds.

**Comment by copoo** [comment]
java 8支持问题，用1.7以下即可

**Comment by zhangzhenhuajack** [comment]
ackdeMacBook-Pro:cat-home jack$ pwd
/Users/jack/git_hub/cat/cat-home
jackdeMacBook-Pro:cat-home jack$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by zhangzhenhuajack** [comment]
[root@ssapp01 ~]# java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
[root@ssapp01 ~]# mvn -version
Apache Maven 3.0.4 (r1232337; 2012-01-17 16:44:56+0800)
Maven home: /data/www/apache-maven-3.0.4
Java version: 1.6.0_45, vendor: Sun Microsystems Inc.
Java home: /data/www/jdk1.6.0_45/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-431.el6.x86_64", arch: "amd64", family: "unix"


####现在ok了，和maven和jdk的版本都有关系，换完版本之后，所有的命令从新执行一遍就OK了！

**Comment by chlliu** [comment]
client端启动后没有报 netty write buffer is full 这个错误码？

**Comment by yalida** [comment]
agent  和 client  是什么关系啊，我要使用的话，是使用agent还是client？

**Comment by jialinsun** [comment]
agent目前我们是没有用的，可以先忽略掉，主要是用来采集一些定制化机器信息的。
正常使用是用client jar包，agent和client没什么直接关系。

**Comment by yalida** [comment]
谢谢你的热心帮助，我现在已经安装好了cat，可是，我不知道怎么实现rpc监控，需要配置什么东西么？还有我的dependency中的拓扑图也没显示

**Comment by youyong205** [comment]
rpc 等监控看公司内部框架，需要在框架中使用cat的api埋点。具体埋点可以参考一些cat-home的一些埋点的sample

**Comment by dankes** [comment]
比方哪个sample？
