### ISSUE TITLE
服务端报错

### ISSUE THREAD

**Issue by Slayerdoomsday** [dianping/cat#907]
拉master最新的代码，服务端配置好并成功启动，查看log，发现在不停的报下面的错误，这是什么原因？

```

[11-09 17:55:00.703] [ERROR] [AbstractSender] test
java.net.UnknownHostException: test
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1092)
	at com.dianping.cat.report.alert.sender.sender.AbstractSender.httpPostSend(AbstractSender.java:78)
	at com.dianping.cat.report.alert.sender.sender.AbstractSender.httpSend(AbstractSender.java:112)
	at com.dianping.cat.report.alert.sender.sender.MailSender.sendEmail(MailSender.java:59)
	at com.dianping.cat.report.alert.sender.sender.MailSender.send(MailSender.java:30)
	at com.dianping.cat.report.alert.sender.sender.SenderManager.sendAlert(SenderManager.java:39)
	at com.dianping.cat.report.alert.sender.AlertManager.send(AlertManager.java:165)
	at com.dianping.cat.report.alert.sender.AlertManager.access$600(AlertManager.java:34)
	at com.dianping.cat.report.alert.sender.AlertManager$SendExecutor.run(AlertManager.java:277)
	at java.lang.Thread.run(Thread.java:745)
	at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)

```

**Comment by chlliu** [comment]
报警配置里的url写的是test

**Comment by youyong205** [comment]
最终的邮件和短信需要使用者去config一个http的接口。
