### ISSUE TITLE
项目配置信息->项目基本信息 无法成功配置，一提交就HTTP 500错误

### ISSUE THREAD

**Issue by lovewhll** [dianping/cat#911]
错误信息如下：

[ERROR] [HttpServlet] Error occured when handling uri: /cat/s/config
java.lang.RuntimeException: Error occured during handling outbound action(config)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleException(DefaultRequestLifecycle.java:89)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)
	at org.unidal.web.MVC.service(MVC.java:90)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:404)
	at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:219)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
	at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:314)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
	at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:202)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
	at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:110)
	at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:402)
	at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.unidal.web.mvc.ActionException: Error occured during handling outbound action(config)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:36)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)
	at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:186)
	... 35 more
Caused by: java.lang.RuntimeException: Error occured during invoking method: public void com.dianping.cat.system.page.config.Handler.handleOutbound(com.dianping.cat.system.page.config.Context) throws javax.servlet.ServletException,java.io.IOException with parameters([com.dianping.cat.system.page.config.Context@537a6bb0])
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:51)
	at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)
	... 37 more
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1125)
	at com.dianping.cat.service.ProjectService.update(ProjectService.java:194)
	at com.dianping.cat.system.page.config.processor.GlobalConfigProcessor.updateProject(GlobalConfigProcessor.java:214)
	at com.dianping.cat.system.page.config.processor.GlobalConfigProcessor.process(GlobalConfigProcessor.java:87)
	at com.dianping.cat.system.page.config.Handler.handleOutbound(Handler.java:129)
	at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)

**Comment by liubo1** [comment]
我的也是

**Comment by youyong205** [comment]
这个其实是不让新增project的，后面基本的project信息都会自动insert到数据库。

这个bug我已经fix，暂还没同步来

**Comment by zhangzhenhuajack** [comment]
项目信息怎么新增进来呢？
