### ISSUE TITLE
 Duplicated name(home) found between handleInbound()

### ISSUE THREAD

**Issue by tllen** [dianping/cat#918]
Caused by: org.apache.xbean.recipe.ConstructionException: Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.unidal.web.mvc.model.ModelManager for injection private org.unidal.web.mvc.model.ModelManager org.unidal.web.mvc.lifecycle.DefaultRequestContextBuilder.m_modelManager
        at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:472)
        at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:367)
        at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:282)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
        ... 70 more
Caused by: java.lang.RuntimeException: Duplicated name(home) found between handleInbound() and handleInbound() of class com.dianping.cat.report.ReportModule
        at org.unidal.web.mvc.model.ModelManager.buildInbound(ModelManager.java:105)
        at org.unidal.web.mvc.model.ModelManager.buildModuleFromMethods(ModelManager.java:196)
        at org.unidal.web.mvc.model.ModelManager.buildModuleFromHandlers(ModelManager.java:166)
        at org.unidal.web.mvc.model.ModelManager.buildModule(ModelManager.java:156)
        at org.unidal.web.mvc.model.ModelManager.build(ModelManager.java:79)
        at org.unidal.web.mvc.model.ModelManager.register(ModelManager.java:320)
        at org.unidal.web.mvc.model.ModelManager.initialize(ModelManager.java:303)
        at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
        at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:97)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:283)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:129)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
        at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
        at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
        at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
        at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
        at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:466)
        ... 76 more

**Comment by moujian** [comment]
你不要用jdk8，换成oracle jdk 1.7就应该没问题了。

**Comment by qmwu2000** [comment]
jdk8 issues fixed, please verify, thanks
