### ISSUE TITLE
Could not create an Appender of type [com.dianping.cat.log4j.CatAppender]. 

### ISSUE THREAD

**Issue by tllen** [dianping/cat#919]
16:52:49,921 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.dianping.cat.log4j.CatAppender]
16:52:49,923 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [com.dianping.cat.log4j.CatAppender]. ch.qos.logback.core.util.IncompatibleClassException
	at ch.qos.logback.core.util.IncompatibleClassException
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:62)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:48)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:275)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:147)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:129)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)

**Comment by youyong205** [comment]
这个应该是引入的包有问题了。
