### ISSUE TITLE
java 8支持问题

### ISSUE THREAD

**Issue by copoo** [dianping/cat#928]
请问jdk8的支持是否已完全修复，我们测试使用是还是会报错。

报错信息如下：
Exception in thread "main" java.lang.NoSuchMethodError: org.codehaus.plexus.ContainerConfiguration.getLifecycleHandlerManager()Lorg/codehaus/plexus/lifecycle/LifecycleHandlerManager;
	at org.unidal.lookup.ContainerLoader.preConstruction(ContainerLoader.java:145)
	at org.unidal.lookup.ContainerLoader.getDefaultContainer(ContainerLoader.java:104)
	at org.unidal.lookup.ContainerLoader.getDefaultContainer(ContainerLoader.java:89)
	at com.dianping.cat.Cat.initialize(Cat.java:105)
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:48)
	at com.dianping.cat.Cat.getProducer(Cat.java:98)
	at com.dianping.cat.Cat.newTransaction(Cat.java:315)
	at com.envision.java8.lamda.main(lamda.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)、

maven和jdk版本如下：

Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-12T04:58:10+08:00)
Maven home: /opt/apache_maven_default
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"

编译cat时jdk是8，运行测试程序时引用jdk8 编译的cat-core，测试程序运行时也是jdk8

**Comment by copoo** [comment]
问题已解决，1.3.6版本是支持jdk8，原因是测试程序中有其他代码段引用到sisu的类plexus容器导致冲突

**Comment by Gyoung** [comment]
我昨天下的版本，jdk8下仍然还会报这个错误
org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.

**Comment by lixuegang** [comment]
表示jdk1.8 并没有启动 报错和楼上一样： 
org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.

**Comment by zzjhacn** [comment]
完美解决JDK8问题：

1、增加ant依赖，
		<dependency>
			<groupId>org.apache.ant</groupId>
			<artifactId>ant</artifactId>
			<version>1.9.6</version>
		</dependency>

2、把jetty和jetty-util版本升到6.1.26
3、把jsp-api-2.1，和jsp-2.1版本升到6.1H.14.1

done

**Comment by 247687009** [comment]
HTTP ERROR 503

Problem accessing /cat/r. Reason:

    org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------
Caused by:

javax.servlet.UnavailableException: org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T19:57:3
7+08:00)
Maven home: D:\java\tools\apache-maven-3.3.3\bin\..
Java version: 1.8.0_66, vendor: Oracle Corporation

**Comment by Percy0601** [comment]
这个问题是Maven版本的问题，在unidal这个组件中要求Maven版本必须大于3.2.3 但是使用Maven3.3.x 这个版本部支持JDK1.6.x 然后最主要的问题就是编译后运行时报错，如何解决：
JDK 1.6.0_25
JDK 1.7.x
Maven 3.2.5(大于3.2.3, 小于3.3.x)
编译就可以了  至于所缺依赖在478040828 的QQ群共享中就可以找到

**Comment by jialechan** [comment]
@zzjhacn 
你的方法试过，问题依旧存在

**Comment by nv6** [comment]
mac下，以下动作重新做一遍OK了（换成1.7）

```
export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
mvn clean install -DskipTests
mvn cat:install
cd cat-home;mvn jetty:run
```

> [INFO] Context path = /cat
[INFO] Tmp directory =  determined at runtime
[INFO] Web defaults = org/mortbay/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = /Volumes/Data/Weacar/project/cat/cat-home/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /Volumes/Data/Weacar/project/cat/cat-home/src/main/webapp
[INFO] Starting jetty 6.1.26 ...
[INFO] jetty-6.1.26
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
Logger file /data/applogs/cat/cat_20160322.log
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
[03-22 17:53:50.050] [WARN] [cat] Cat is lazy initialized!
[INFO] Started SelectChannelConnector@0.0.0.0:2281
[INFO] Started Jetty Server
[INFO] Starting scanner at interval of 10 seconds.
[INFO] Working directory is /Volumes/Data/Weacar/project/cat/cat-home
[INFO] War root is /Volumes/Data/Weacar/project/cat/cat-home/src/main/webapp

**Comment by walterlife** [comment]
将org.unidal.framework 中的web-framework，foundation-service升级到3.1.0 即可。
org.unidal.framework 需要从github https://github.com/unidal/frameworks下载最新代码并编译。

**Comment by radishlee** [comment]
Connected to the target VM, address: '127.0.0.1:50000', transport: 'socket'
Disconnected from the target VM, address: '127.0.0.1:50000', transport: 'socket'
Exception in thread "main" java.lang.NoSuchMethodError: org.codehaus.plexus.ContainerConfiguration.getLifecycleHandlerManager()Lorg/codehaus/plexus/lifecycle/LifecycleHandlerManager;
	at org.unidal.lookup.ContainerLoader.preConstruction(ContainerLoader.java:145)
	at org.unidal.lookup.ContainerLoader.getDefaultContainer(ContainerLoader.java:104)
	at org.unidal.lookup.ContainerLoader.getDefaultContainer(ContainerLoader.java:89)
	at com.dianping.cat.Cat.initialize(Cat.java:178)
	at com.dianping.cat.Cat.checkAndInitialize(Cat.java:75)
	at com.dianping.cat.Cat.getManager(Cat.java:141)
	at com.beaconhp.common.log.CatLogbackAppender.append(CatLogbackAppender.java:18)
	at com.beaconhp.common.log.CatLogbackAppender.append(CatLogbackAppender.java:13)



jdk8
maven3.6
springboot2.0
cat3.0-alpha

在用logback插件时候 报错 项目不能启动

**Comment by radishlee** [comment]
@Percy0601 @youyong205  大牛有时间帮忙看一下

**Comment by 565444118** [comment]
正解可能是这个：https://www.jianshu.com/p/7998212c8314
