### ISSUE TITLE
用tomcat部署war包，JDK版本8，项目跑起来实时里面最近两小时的数据都会出现500，控制台每隔一分钟出现一个io异常

### ISSUE THREAD

**Issue by smile326** [dianping/cat#950]
tomcat的控制台每隔50秒左右会出现一个下面的异常。。
[WARN ] [2016-01-14 16:41:16,297] io.netty.channel.DefaultChannelPipeline io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151) - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
 java.io.IOException: ????????????????????
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:25)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:202)
	at sun.nio.ch.IOUtil.read(IOUtil.java:169)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:243)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:662)

然后点击实时，如果是最近两个小时的都是500：
![image](https://cloud.githubusercontent.com/assets/14938265/12321164/b233967c-bae7-11e5-8dc4-693c08da947b.png)

集思广益，希望cat越来越棒！

**Comment by smile326** [comment]
windows环境有这个问题，Linux环境不会出现
