### ISSUE TITLE
cat 微信群  申请者加微信18616671676，注明公司和cat用户。

### ISSUE THREAD

**Issue by youyong205** [dianping/cat#959]
申请者加微信18616671676，注明公司和cat用户，后面会拉你进群。

**Comment by sunnyhui2010** [comment]
有没有qq群？微信不是很方便呢

**Comment by qmwu2000** [comment]
请加微信(@qmwu2000或youyong205), 注明cat用户，我们会加你入CAT微信群

**Comment by wangchenQQ** [comment]
你好 有几个问题 是否有空解答 谢谢了
1、cat2和cat是否有区别，目前更新的是哪个项目？
2、http://unidal.org是否和cat是同一个版本

**Comment by JaryZhen** [comment]
QQ群是不是更方便一些

**Comment by maodouchen** [comment]
有页面截图么    可以直观的看到统计到的数据  前端部分

**Comment by Knight-Wu** [comment]
你好, 加了微信没反应啊

**Comment by FebruaryBird1** [comment]
cat python客户端为什么使用会报错


[Running] python3.7 -u "/Users/neil/Desktop/python/2.py"
cat sdk has not been initialized!
cat sdk has not been initialized!
Traceback (most recent call last):
  File "/Users/neil/Desktop/python/2.py", line 22, in <module>
    test()
  File "/usr/local/lib/python3.7/site-packages/cat/transaction.py", line 107, in wraps
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cat/transaction.py", line 99, in __exit__
    self.complete()
  File "/usr/local/lib/python3.7/site-packages/cat/transaction.py", line 46, in complete
    self._trans.complete(self._trans)
AttributeError: 'NoneType' object has no attribute 'complete'
