### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by zhengxiaoxue** [dianping/cat#973]
16/03/16 14:10:44 WARN channel.DefaultChannelPipeline: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

为什么会出现这种错误,并且我们两个客户端连(配置完全一样,环境完全一样)只有一个会出现这种问题,并且数据全部丢失.

**Comment by qmwu2000** [comment]
这个是正常的。此exception表示CAT客户端主动断开连接。

**Comment by zhengxiaoxue** [comment]
可是我的数据都丢了就不应该叫正常了啊,为什么他主动断开

**Comment by qmwu2000** [comment]
如果量比较大，请检查下网络稳定性，有没有丢包出现。


发自我的 iPhone

**Comment by zhengxiaoxue** [comment]
那我怎么能把客户端的日志打成debug的?
