### ISSUE TITLE
Java1.6 环境变量配好好，还是无法编译，

### ISSUE THREAD

**Issue by huoxudong125** [dianping/cat#974]
E:\GitHub\cat>java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

E:\GitHub\cat>mvn clean install -DskipTests
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by huoxudong125** [comment]
We should install java 6 and [maven 3.2.5](https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/)(**not the latest version 3.3.9**).

Take care of the versions.Maybe should add these problems in readme.md for beginner.

**Comment by bicey** [comment]
这个应该是安装环境的问题，

**Comment by youyong205** [comment]
这个是你maven版本的问题，你可以尝试使用jdk7

**Comment by huoxudong125** [comment]
@youyong205 诡异，不知道除了JAVA_HOME,PATH 配置JAVA路径外，是不是IDEA 自己也给做了手脚（猜测，后来发现IDEA还给装了1.8）。

------------------------------------------
处理过程：
>刚开始java -version显示JDK 1.7 的版本时，执行mvn 命令还是报错.
>后来直接卸载JDK1.7，才可以用到早已配置好的JDK1.6 环境变量。

不知大牛们**有没在windows 10 中碰到过这种同时安装 1.6 和1.7，会导致JAVA_HOME,Path 环境变量无法指定到1.6的JDK上**。
