### ISSUE TITLE
mvn jetty:run出错

### ISSUE THREAD

**Issue by davideuler** [dianping/cat#976]
在cat-home项目下面运行 mvn jetty:run出错：
[ERROR] unavailable
org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

	at org.unidal.web.AbstractContainerServlet.lookup(AbstractContainerServlet.java:74)
	at org.unidal.web.MVC.initComponents(MVC.java:35)
	at org.unidal.web.AbstractContainerServlet.init(AbstractContainerServlet.java:51)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:736)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)

Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:373)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:388)
	at org.unidal.web.AbstractContainerServlet.lookup(AbstractContainerServlet.java:72)
	... 47 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error constructing component role: 'org.unidal.web.lifecycle.RequestLifecycle', implementation: 'org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle', role hint: 'mvc'
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:176)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:123)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	... 50 more
Caused by: org.apache.xbean.recipe.ConstructionException: Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.unidal.web.mvc.lifecycle.RequestContextBuilder for injection private org.unidal.web.mvc.lifecycle.RequestContextBuilder org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.m_builder
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:503)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:371)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:286)

**Comment by davideuler** [comment]
war包放到 tomcat里面跑也是页面出错。
/data/appdatas/cat目录下面有 server.xml, client.xml, datasources.xml.
jetty:run跑的详细信息如下：
Caused by: org.apache.xbean.recipe.ConstructionException: Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.unidal.web.mvc.lifecycle.RequestContextBuilder for injection private org.unidal.web.mvc.lifecycle.RequestContextBuilder org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.m_builder
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:503)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:371)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:286)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
	... 54 more
Caused by: org.apache.xbean.recipe.ConstructionException: Composition failed of field null in object of type org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle because the requirement ComponentRequirement{role='org.unidal.web.mvc.lifecycle.RequestContextBuilder', roleHint='', fieldName='null'} was missing)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:413)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:497)
	... 60 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.unidal.web.mvc.lifecycle.RequestContextBuilder', it could not be started.
      role: org.unidal.web.mvc.lifecycle.RequestContextBuilder
  roleHint: default
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:373)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
	... 63 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error constructing component role: 'org.unidal.web.mvc.lifecycle.RequestContextBuilder', implementation: 'org.unidal.web.mvc.lifecycle.DefaultRequestContextBuilder', role hint: 'default'
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:176)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:123)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	... 66 more
Caused by: org.apache.xbean.recipe.ConstructionException: Unable to convert property value from org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe to org.unidal.web.mvc.model.ModelManager for injection private org.unidal.web.mvc.model.ModelManager org.unidal.web.mvc.lifecycle.DefaultRequestContextBuilder.m_modelManager
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:503)
	at org.apache.xbean.recipe.ObjectRecipe.setProperties(ObjectRecipe.java:371)
	at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:286)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
	... 70 more
Caused by: java.lang.RuntimeException: Duplicated name(home) found between handleInbound() of class com.dianping.cat.report.page.home.Handler and handleInbound() of class com.dianping.cat.report.ReportModule
	at org.unidal.web.mvc.model.ModelManager.buildInbound(ModelManager.java:105)
	at org.unidal.web.mvc.model.ModelManager.buildModuleFromMethods(ModelManager.java:197)
	at org.unidal.web.mvc.model.ModelManager.buildModuleFromHandlers(ModelManager.java:167)
	at org.unidal.web.mvc.model.ModelManager.buildModule(ModelManager.java:157)
	at org.unidal.web.mvc.model.ModelManager.build(ModelManager.java:79)
	at org.unidal.web.mvc.model.ModelManager.register(ModelManager.java:321)
	at org.unidal.web.mvc.model.ModelManager.initialize(ModelManager.java:304)
	at org.codehaus.plexus.personality.plexus.lifecycle.phase.InitializePhase.execute(InitializePhase.java:33)
	at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:96)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.start(AbstractComponentManager.java:167)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.startComponentLifecycle(XBeanComponentBuilder.java:283)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:129)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
	at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
	at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
	at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:393)
	at org.codehaus.plexus.component.builder.XBeanComponentBuilder$RequirementRecipe.internalCreate(XBeanComponentBuilder.java:402)
	at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
	at org.apache.xbean.recipe.RecipeHelper.convert(RecipeHelper.java:167)
	at org.apache.xbean.recipe.ObjectRecipe.setProperty(ObjectRecipe.java:497)
	... 76 more
[INFO] Started SelectChannelConnector@0.0.0.0:2281
[INFO] Started Jetty Server
[INFO] Starting scanner at interval of 10 seconds.

**Comment by davideuler** [comment]
#836 重复，回头我再试试

**Comment by davideuler** [comment]
试了换  JDK 1.7，无果。 回头再试试到eclipse里面运行TestServer

**Comment by 8241796** [comment]
我也是这个问题。JDK1.7 和 JDK1.8都不行。MAVEN换成3.2.5也不成。

兼容性做的不好。基本的测试都不行。社区也不活跃，是不是有很多公司在用呢？

**Comment by youyong205** [comment]
8241796 建议你不要玩了
